Set UserAgent and network settings for the msbuild restore task
NuGet/NuGet.Client pull request #1022
Opened 2016-11-14 19:30 UTC by emgarten

Set UserAgent and network settings for the msbuild restore task

Copying XPlat network settings over to the MSBuild RestoreTask. This includes:
* UserAgent
* Allowed SSL protocols
* Connection limit

Fixes https://github.com/NuGet/Home/issues/3905

//cc @joelverhagen @mishra14 @alpaix @drewgil @dtivel @jainaashish @zhili1208

2016-11-14 19:39 UTC, alpaix commented on src/NuGet.Core/NuGet.Protocol.Core.v3/Utility/ProtocolUtility.cs
> +        public static void SetConnectionLimit()
Can this be a method of `NetworkProtocolUtility` instead?

2016-11-14 19:41 UTC, mishra14 requested changes

2016-11-14 19:41 UTC, mishra14 commented on src/NuGet.Core/NuGet.CommandLine.XPlat/Utility/XPlatUtility.cs
>              UserAgent.SetUserAgentString(new UserAgentStringBuilder("NuGet xplat"));
Please add Copyright and Licensing information to this file.

2016-11-14 19:41 UTC, mishra14 commented on src/NuGet.Core/NuGet.Build.Tasks/BuildTasksUtility.cs
>  ﻿using System.Collections.Generic;
Please add Copyright and Licensing information to this file.

2016-11-14 19:41 UTC, mishra14 commented on src/NuGet.Core/NuGet.Protocol.Core.v3/Utility/ProtocolUtility.cs
> +#if !IS_CORECLR
does this not apply to `CORECLR` ?

2016-11-14 19:52 UTC, dtivel commented on src/NuGet.Core/NuGet.Build.Tasks/BuildTasksUtility.cs
> +using NuGet.Protocol.Core.Types;
The changes to this file appear to be unnecessary.

2016-11-14 19:58 UTC, dtivel commented on src/NuGet.Core/NuGet.Protocol.Core.v3/Utility/ProtocolUtility.cs
> +        public static void SetConnectionLimit()
Can [NuGet.CommandLine.Program.MainCore(...)](https://github.com/NuGet/NuGet.Client/blob/4cccb13833ad29d6a0bcff055460d964f1b49cfe/src/NuGet.Clients/NuGet.CommandLine/Program.cs#L70) be updated to use this?

2016-11-14 19:58 UTC, dtivel commented on src/NuGet.Core/NuGet.Protocol.Core.v3/Utility/ProtocolUtility.cs
> +    public class ProtocolUtility
`static`?

2016-11-14 20:07 UTC, dtivel commented on src/NuGet.Core/NuGet.Build.Tasks/RestoreTask.cs
> +                .WithOSDescription(RuntimeInformation.OSDescription));
[`RuntimeInformation`](https://docs.microsoft.com/en-us/dotnet/core/api/system.runtime.interopservices.runtimeinformation) is in the `System.Runtime.InteropServices` namespace, and yet I do not see a `using` directive for it.  I expect a compilation error here when `IS_CORECLR` is defined.

2016-11-14 20:43 UTC, emgarten commented on src/NuGet.Core/NuGet.Protocol.Core.v3/Utility/ProtocolUtility.cs
> +        public static void SetConnectionLimit()
Good idea, I'll move it over there.

2016-11-14 20:45 UTC, emgarten commented on src/NuGet.Core/NuGet.Protocol.Core.v3/Utility/ProtocolUtility.cs
> +    public class ProtocolUtility
Good catch, it should have been. This will get moved over to NetworkProtocolUtility

2016-11-14 21:51 UTC, emgarten commented on src/NuGet.Core/NuGet.CommandLine.XPlat/Utility/XPlatUtility.cs
>              UserAgent.SetUserAgentString(new UserAgentStringBuilder("NuGet xplat"));
@mishra14 please open an issue to track automating this process as part of build.ps1/build.sh to avoid noise in PRs. Thanks.

2016-11-14 22:58 UTC, dtivel approved these changes

2016-11-14 23:20 UTC, mishra14 commented on src/NuGet.Core/NuGet.CommandLine.XPlat/Utility/XPlatUtility.cs
>              UserAgent.SetUserAgentString(new UserAgentStringBuilder("NuGet xplat"));
https://github.com/NuGet/Home/issues/3946

2016-11-14 23:21 UTC, mishra14 approved these changes

2016-11-14 23:32 UTC, alpaix approved these changes

2016-11-15 01:06 UTC, emgarten commented on src/NuGet.Core/NuGet.Build.Tasks/RestoreTask.cs
> +                .WithOSDescription(RuntimeInformation.OSDescription));
The CI agrees :smile:

2016-11-15 01:07 UTC, merged