Repair package spec for legacy csproj
NuGet/NuGet.Client pull request #1033
Opened 2016-11-23 02:56 UTC by drewgil

Package spec generated by legacy csproj had some gaps for supporting UWP restores.
@emgarten

2016-11-23 02:59 UTC, drewgil commented
Note that it would be good to add some unit tests for this--but I'd like a build for running scenarios tonight, so I'll get onto the unit test coverage next.

2016-11-23 07:08 UTC, emgarten requested changes
LegacyPackageRef should be NETCore output type. UAP is just for project.json.

2016-11-23 07:08 UTC, emgarten commented on src/NuGet.Clients/PackageManagement.VisualStudio/ProjectSystems/LegacyCSProjPackageReferenceProject.cs
> +                    OutputType = RestoreOutputType.UAP,
This should stay as NETCore, only the UWPProjectJson should use this type from how I understand the goal.

2016-11-23 07:08 UTC, emgarten commented on src/NuGet.Clients/PackageManagement.VisualStudio/ProjectSystems/LegacyCSProjPackageReferenceProject.cs
> +                Version = new NuGetVersion(1, 0, 0, 0, (string)null, string.Empty),
This should read the Version property from the project file. ProjectVersion may override it. This all needs to match pack behavior.

2016-11-23 07:08 UTC, emgarten commented on src/NuGet.Clients/PackageManagement.VisualStudio/ProjectSystems/LegacyCSProjPackageReferenceProject.cs
> +                IsDefaultVersion = true,
I would skip setting this

2016-11-23 07:08 UTC, emgarten commented on src/NuGet.Clients/PackageManagement.VisualStudio/ProjectSystems/LegacyCSProjPackageReferenceProject.cs
> +                        .Select(tfi => tfi.FrameworkName?.GetShortFolderName())
This should never be null, right?
Also, if it were null you would need to filters those out

2016-11-23 22:42 UTC, drewgillies commented on src/NuGet.Clients/PackageManagement.VisualStudio/ProjectSystems/LegacyCSProjPackageReferenceProject.cs
> +                Version = new NuGetVersion(1, 0, 0, 0, (string)null, string.Empty),
Discussed offline--will circle back to this.

2016-11-23 22:46 UTC, drewgillies commented
Some rebasing here so the iteration won't be obvious, @emgarten. however, it's just the addressing of your feedback (small delta) and the reverting of the UAP test and spec validation changes, as these are no longer needed after changing the output type.

2016-11-24 00:31 UTC, emgarten commented on src/NuGet.Clients/PackageManagement.VisualStudio/ProjectSystems/LegacyCSProjPackageReferenceProject.cs
>              var packageTargetFallback = _project.PackageTargetFallback?.Split(new[] { ';' })
This should use https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Commands/RestoreCommand/Utility/MSBuildRestoreUtility.cs#L405

That can be fixed as part of the trimming issue later if needed

2016-11-24 00:32 UTC, emgarten approved these changes
LGTM

2016-11-24 01:00 UTC, merged