Add -dependencyVersion CLI switch for install command
NuGet/NuGet.Client pull request #1044
Opened 2016-12-01 20:52 UTC by billboyletrintech

Partial Fix for NuGet/Home#1806

2016-12-01 20:52 UTC, dnfclas commented
Hi __@billboyletrintech__, I'm your friendly neighborhood .NET Foundation Pull Request Bot (You can call me DNFBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla2.dotnetfoundation.org.
    </span>

TTYL, DNFBOT;

2016-12-01 21:31 UTC, dnfclas commented
__@billboyletrintech__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, DNFBOT;

2016-12-16 05:15 UTC, emgarten commented
@billboyletrintech thanks for the PR!  Why is this a partial fix, what else is needed to fix the issue?

Also, this change would require tests. You can find the other nuget.exe tests under NuGet.Commandline.Tests

2016-12-16 15:46 UTC, billboyletrintech commented
The scope of the issue this PR references is to add the commandline switch to install, update, and restore, as well as respecting the setting in nuget.config.  This PR only adds the switch to install as that's the use case I need in our continuous integration workflow.  I'll add the tests for install dependency resolution, didn't see that test project, sorry.

2016-12-16 19:43 UTC, emgarten commented
Restore would be a much larger change to the resolver where this flag isn't supported today. Update should be very similar to install, does it look straight forward to add this there also?

2016-12-16 20:08 UTC, billboyletrintech commented
It looked more complex because it appears that the current default behavior is to take the highest package with the same major/minor as the current downloaded package.  To me its a little unclear (without digging through the powershell implementation) what the correct behavior would be for all the different resolution options.  I'd rather someone more familiar with the code/logic/history does it.

2016-12-16 20:59 UTC, emgarten commented
Update has ``-safe`` which applies to the package being updated. DependencyVersion may only be needed for dependencies. Ideally powershell and everything else would be consistent in how they treated this.

For install does the DependencyVersion actually change which top level package is being installed? Or is it always the latest?

2016-12-16 21:52 UTC, billboyletrintech commented
No, my change only affects dependency resolution, top level is always latest if not specified.  It was actually a very simple fix, look at the diff.  The test was significantly more effort.

2017-02-08 21:43 UTC, serbrech commented
Is there any plans around this?
I am hitting a similar use-case.
I want to update a package to the latest, but keep its dependencies to the lowest. that's not possible today it seems :(

2017-02-08 22:35 UTC, emgarten requested changes

2017-02-08 22:35 UTC, emgarten commented on src/NuGet.Clients/NuGet.CommandLine/Commands/InstallCommand.cs
> +                depBehavior = DependencyBehavior.Lowest;
@billboyletrintech I think this should read the value from the settings if it was not passed in.

2017-02-08 22:37 UTC, emgarten commented
@serbrech would you add your scenario to https://github.com/NuGet/Home/issues/1806 to open a new issue if that one doesn't cover it?

2017-02-24 15:31 UTC, billboyletrintech commented
You can pull and build my fork if you like, I don't expect them to merge this in anytime soon.

2017-03-02 01:04 UTC, emgarten commented
:bell: @billboyletrintech are you able to make the changes needed to read this value from the config? 

I would like to make a decision on this PR soon, and to go into NuGet this needs to be a complete solution.

2017-03-02 07:54 UTC, serbrech commented
@billboyletrintech I did not expand on my use case here, since it was described in the the orleans reference just below my message.

2017-03-02 18:38 UTC, billboyletrintech commented
@emgarten ok I've added your requested changes

2017-04-06 23:06 UTC, mishra14 commented
@emgarten can you review/close this?

2017-04-07 18:12 UTC, emgarten commented
@rrelyea

2017-06-21 18:33 UTC, erick-thompson commented
Is this PR still under development? If not, I'd be happy to take it over and complete it. The issue that this PR addresses is a huge pain point.

2017-07-05 22:24 UTC, emgarten commented
I think this PR is ready, my main concern here is that this is updating a legacy command that causes confusion for users. *Install* for example doesn't not handle packages with multiple target frameworks, it just picks one group at random and continues downloading packages. This is because no project framework is provided to make a decision against.

2017-07-05 23:56 UTC, erick-thompson commented
I'm not what you mean about the confusion. The change is scoped to what
approach is taken when resolving dependencies. I wouldn't think anything
changes except the logic when a presented with a range. It doesn't change
anything about how project framework is used (or not).

On Wed, Jul 5, 2017 at 3:24 PM, Justin Emgarten <notifications@github.com>
wrote:

> I think this PR is ready, my main concern here is that this is updating a
> legacy command that causes confusion for users. *Install* for example
> doesn't not handle packages with multiple target frameworks, it just picks
> one group at random and continues downloading packages. This is because no
> project framework is provided to make a decision against.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/NuGet/NuGet.Client/pull/1044#issuecomment-313243570>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAk2TPhCGSxF4lnlhqmMcX4ykJw8DINOks5sLA0KgaJpZM4LB4II>
> .
>

2017-07-30 22:08 UTC, emgarten approved these changes

2017-07-30 22:09 UTC, emgarten commented on src/NuGet.Clients/NuGet.CommandLine/Commands/InstallCommand.cs
> +            if (!Enum.TryParse<DependencyBehavior>(depSetting, out ret))
This should use ignore case when parsing the enum
https://msdn.microsoft.com/en-us/library/dd991317(v=vs.110).aspx

2017-07-30 22:10 UTC, emgarten commented on src/NuGet.Clients/NuGet.CommandLine/Commands/InstallCommand.cs
> +                if (!Enum.TryParse<DependencyBehavior>(DependencyVersion, out depBehavior))
Parse with ignore case set to true
https://msdn.microsoft.com/en-us/library/dd991317(v=vs.110).aspx

2017-07-30 22:16 UTC, emgarten requested changes
Some clean up is needed on this. Please also rebase it against the current dev branch and it will be considered for the next release

2017-07-30 22:16 UTC, emgarten commented on src/NuGet.Clients/NuGet.CommandLine/Commands/InstallCommand.cs
> +            DependencyBehavior depBehavior = GetSettingsDependencyBehavior(Settings);
This does not need to be read if the command line flag is set, it should be moved to an else after that check below

2017-07-30 22:16 UTC, emgarten commented on src/NuGet.Clients/NuGet.CommandLine/Commands/InstallCommand.cs
> +                ret = DependencyBehavior.Lowest; // if fails, set to default behavior
It seems like this one should fail also, you can create a common method that handles parsing the flag or failing with the new exception message.

2017-07-30 22:16 UTC, emgarten commented on src/NuGet.Clients/NuGet.CommandLine/NuGetCommand.resx
> +    <value>Overrides the default dependency resolution behavior</value>
Add a `.` to the end, this is a complete sentence.

2017-07-30 22:16 UTC, emgarten commented on src/NuGet.Clients/NuGet.CommandLine/NuGetCommand.resx
> +    <value>Unknown Dependency Resolution Behavior for -dependencyVersion</value>
Casing, and this could be simplified to
`Invalid value given for -DependencyVersion`

2017-08-09 00:49 UTC, WardenGnaw commented
I'm interested in this PR going through and is blocking a couple work items for me. If @billboyletrintech does not make the changes in a couple days, can I take this over to get this going through?

2017-08-09 02:49 UTC, billboyletrintech commented
I'm not going to have time to work on this I'm wrapping up a release at work.  Its been 8 months since my initial pull request and I've already made changes once.  Suddenly I need to make a bunch of changes within days?  Honestly I regret attempting to contribute.  Whoever wants to can feel free to take my work and 'finish' it.

2017-08-09 03:00 UTC, WardenGnaw commented
@billboyletrintech. Sorry, I did not mean my comment to force a deadline on you. I thought that this PR may have been forgotten and was wondering if it was ok for someone else to resolve the last few comments if you were busy. 

Thank you for taking the initiative on fixing the issue.

2017-08-09 03:11 UTC, emgarten commented
@billboyletrintech sorry you feel that way, I do appreciate the contribution.

@WardenGnaw feel free to fork and add to these changes, I can help you with with any additional feedback from there.

2017-08-10 04:27 UTC, emgarten commented
Fixed with https://github.com/NuGet/NuGet.Client/commit/6f8d529312187fa1b6734da8d4ed9dc3442b916c

2017-08-10 04:27 UTC, closed without merging