Fix VS perf issue for solution load
NuGet/NuGet.Client pull request #1047
Opened 2016-12-07 18:05 UTC by jainaashish

Instead of initializing core MEF objects at solution load/new which caused this regression, we'll lazy initialize them whenever they are actually needed.

Fix VS issue# 297627

@alpaix @emgarten @rrelyea

2016-12-07 18:44 UTC, alpaix commented on src/NuGet.Clients/PackageManagement.VisualStudio/IDE/VSSolutionManager.cs
> +                    EnsureCacheInitialized();
I don't think full cache initialization is needed here. This operation can be extremely heavy.

2016-12-07 18:45 UTC, alpaix commented on src/NuGet.Clients/PackageManagement.VisualStudio/IDE/VSSolutionManager.cs
> +                EnsureCacheInitialized();
Same here.

2016-12-07 18:53 UTC, alpaix commented on src/NuGet.Clients/PackageManagement.VisualStudio/SolutionRestore/SolutionRestoreWorker.cs
> +            if (!_initialized)
Consider thread-safe solution for initialization check
```c#
if (!Interlocked.CompareExchange(ref _initialized, true, false))
{
}
```

2016-12-07 18:56 UTC, alpaix requested changes
Address the feedback

2016-12-07 19:12 UTC, jainaashish commented on src/NuGet.Clients/PackageManagement.VisualStudio/IDE/VSSolutionManager.cs
> +                    EnsureCacheInitialized();
I wanted to keep it consistent with existing behavior, and more so initialization will anyway be done at similar time frame. Also without it, we'll be partially initializing here and then at some point, again call for full initialization, which will not be good idea. What do you think?

2016-12-07 19:16 UTC, jainaashish commented on src/NuGet.Clients/PackageManagement.VisualStudio/SolutionRestore/SolutionRestoreWorker.cs
> +            if (!_initialized)
I thought about that but then saw it will never be used in multi-thread scenario... But anyways I'll make it thread-safe to be on safer side.

2016-12-07 22:03 UTC, alpaix approved these changes
Looking ✨!

2016-12-08 19:37 UTC, alpaix commented on src/NuGet.Clients/NuGet.SolutionRestoreManager/RestoreManagerPackage.cs
> +            var componentModel = await GetServiceAsync(typeof(SComponentModel)) as IComponentModel;
How does this change improve the perf?

2016-12-08 19:42 UTC, jainaashish commented on src/NuGet.Clients/NuGet.SolutionRestoreManager/RestoreManagerPackage.cs
> +            var componentModel = await GetServiceAsync(typeof(SComponentModel)) as IComponentModel;
Current code change only improves 10ms out of 50ms regression, which is why I'm trying out few other approaches. Essentially I want to get rid of ServiceProviderExtensions APIs which is the root cause. I'm not sure this will improve it further or not, but giving it a try.

2016-12-13 17:20 UTC, alpaix commented on src/NuGet.Clients/NuGet.SolutionRestoreManager/RestoreManagerPackage.cs
> +    [PackageRegistration(UseManagedResourcesOnly = true, AllowsBackgroundLoading = false)]
Is this necessary?

2016-12-13 17:21 UTC, alpaix commented on src/NuGet.Clients/NuGet.SolutionRestoreManager/RestoreManagerPackage.cs
> +            await ThreadHelper.JoinableTaskFactory.SwitchToMainThreadAsync();
Is it correct to switch and leave the calling thread on the UI thread?

2016-12-13 17:33 UTC, jainaashish commented on src/NuGet.Clients/NuGet.SolutionRestoreManager/RestoreManagerPackage.cs
> +            await ThreadHelper.JoinableTaskFactory.SwitchToMainThreadAsync();
Trying out multiple things, this is still not finalized code. Although this one left out by mistake, thanks for pointing!

2016-12-13 18:11 UTC, merged