add ability to specify contentTargetFolders in a project to determine where the content would go in a nupkg
NuGet/NuGet.Client pull request #1049
Opened 2016-12-08 21:03 UTC by rohit21agrawal

Fixes : https://github.com/NuGet/Home/issues/3718

Updated spec for ContentTargetFolders property : https://github.com/NuGet/Home/issues/3718

@emgarten @joelverhagen @rrelyea @alpaix

2016-12-08 21:05 UTC, joelverhagen commented on src/NuGet.Core/NuGet.Build.Tasks.Pack.Library/PackTask.cs
> +#if DEBUG
This doesn't seem like a good default for debug builds. Most people don't care about attaching the debugger to this bit of code.

Also, it's useful to have a `Console.WriteLine` which displays the PID.

I think this should be commented out by default.

2016-12-08 21:06 UTC, joelverhagen commented on src/NuGet.Core/NuGet.Build.Tasks.Pack.Library/IPackTaskRequest.cs
>          string BuildOutputFolder { get; }
Do we want to support the same here? Tracking issue perhaps?

2016-12-08 21:07 UTC, joelverhagen commented on src/NuGet.Core/NuGet.Build.Tasks.Pack.Library/PackTask.cs
> +                ContentTargetFolders = MSBuildUtility.TrimAndExcludeNullOrEmpty(ContentTargetFolders),
Check the unit tests for this code. I think they need to be modified to expect this new property.

2016-12-08 21:07 UTC, joelverhagen requested changes
⌚️

2016-12-08 22:02 UTC, rohit21agrawal commented on src/NuGet.Core/NuGet.Build.Tasks.Pack.Library/PackTask.cs
> +#if DEBUG
oh i put it for testing purposes and forgot to remove it. thanks for catching this.

2016-12-08 22:16 UTC, rohit21agrawal commented on src/NuGet.Core/NuGet.Build.Tasks.Pack.Library/IPackTaskRequest.cs
>          string BuildOutputFolder { get; }
talked to @rrelyea about this, we don't want this flexibility for the DLLs

2016-12-08 23:35 UTC, rohit21agrawal commented on src/NuGet.Core/NuGet.Build.Tasks.Pack.Library/PackTask.cs
> +                ContentTargetFolders = MSBuildUtility.TrimAndExcludeNullOrEmpty(ContentTargetFolders),
fixed. and added a new unit test too.

2016-12-08 23:37 UTC, rohit21agrawal commented
@joelverhagen changes made as per feedback.

2016-12-09 01:34 UTC, joelverhagen commented on src/NuGet.Core/NuGet.Build.Tasks.Pack.Library/IPackTaskRequest.cs
>          string BuildOutputFolder { get; }
Sounds good.

2016-12-09 20:37 UTC, joelverhagen commented on src/NuGet.Core/NuGet.Build.Tasks.Pack.Library/PackTaskLogic.cs
> +            targetPaths = contentTargetFolders.Where(f=>!f.EndsWith(Path.DirectorySeparatorChar.ToString())).
nit: spacing around `=>`
nit: new line per LINQ method

2016-12-09 21:29 UTC, rohit21agrawal commented on src/NuGet.Core/NuGet.Build.Tasks.Pack.Library/PackTaskLogic.cs
> +            targetPaths = contentTargetFolders.Where(f=>!f.EndsWith(Path.DirectorySeparatorChar.ToString())).
@joelverhagen fixed.

2016-12-09 23:35 UTC, joelverhagen approved these changes

2016-12-09 23:37 UTC, merged