Pack targetPath always use forward slash
NuGet/NuGet.Client pull request #1050
Opened 2016-12-08 21:11 UTC by zhili1208

https://github.com/NuGet/Home/issues/4073

2016-12-08 21:14 UTC, joelverhagen commented on src/NuGet.Core/NuGet.Packaging/PackageCreation/Authoring/PhysicalPackageFile.cs
>                  if (String.Compare(_targetPath, value, StringComparison.OrdinalIgnoreCase) != 0)
super confusing line, this is `!StringComparer.OrdinalIgnoreCase.Equals(a, b)`

2016-12-08 21:20 UTC, joelverhagen commented on src/NuGet.Core/NuGet.Packaging/PackageCreation/Authoring/PhysicalPackageFile.cs
> +                    _targetPath = value.Replace("\\", "/");
We should have a unit test for this 

1. assign `TargetPath`
1. get and validate:
    1. `TargetPath`
    1. `TargetFramework`
    1. `EffectivePath`

2016-12-08 21:20 UTC, joelverhagen requested changes
⌚️

2016-12-14 00:51 UTC, rohit21agrawal commented on src/NuGet.Core/NuGet.Packaging/PackageCreation/Authoring/PhysicalPackageFile.cs
> +                    _targetPath = value.Replace("\\", "/");
this doesn't seem like it's right. what if the user actually meant "\" to be a part of his targetPath on a unix system?

2017-03-02 01:07 UTC, emgarten commented
🔔 @zhili1208 @rohit21agrawal is this still needed for pack? Can someone merge or close this?

2017-04-06 23:01 UTC, mishra14 commented
🔔  @zhili1208

2017-04-07 22:15 UTC, zhili1208 commented
close it

2017-04-07 22:15 UTC, closed without merging