Auto-Restore UI normalization
NuGet/NuGet.Client pull request #1052
Opened 2016-12-10 03:07 UTC by alpaix

Resolves NuGet/Home#3633, NuGet/Home#3789, NuGet/Home#3835,
NuGet/Home#3884.

The purpose of this change is to make consistent UX in all restore
scenarios: auto-restore, on-build restore, and solution restore. At the
same time each scenario has some nuances, whereas:
- Auto-restore and solution restore should write log messages in PM console
output window.
- On-build restore writes inline log messages in build output window.

Introduced new console type: `BuildOutputConsole`. It allows writing into
the VS build output window via `IOutputConsole` abstraction API.

Moved `SolutionRestoreCommand` into the solutuion restore package. As the
latter loads on solution open so the restore command should be available
at this point. At the same time the command invokation shouldn't trigger
loading of the legacy package.

Also had to do some refactoring in order to consume `VsConsole` API in
Solution Restore implementation classes:
- Moved all `SolutionRestore*` artifacts into
  `NuGet.SolutionRestoreManager` project.

Eliminated dead code including remnants of debug console and standalone
console.

//cc @emgarten @jainaashish @mishra14 @rohit21agrawal @rrelyea

2016-12-13 00:54 UTC, emgarten commented on src/NuGet.Clients/NuGet.SolutionRestoreManager/NuGet.SolutionRestoreManager.csproj
> +    <Reference Include="envdte80, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a">
Is this needed? envdte 8.0.0.0 is referenced above it? I think these names may be dupes but I'm unsure.

2016-12-13 00:56 UTC, jainaashish commented
`Moved SolutionRestoreCommand into the solutuion restore package. As the
latter loads on solution open so the restore command should be available
at this point. At the same time the command invokation shouldn't trigger
loading of the legacy package.

Also had to do some refactoring in order to consume VsConsole API in
Solution Restore implementation classes:

Moved all SolutionRestore* artifacts into
NuGet.SolutionRestoreManager project.`

before starting with the code review, I would advice to see if this part had any perf regression with current solution load time since we're already dealing with a perf regression in same area and this change may make it worse.

2016-12-13 01:55 UTC, emgarten approved these changes
Glad to see these scenarios all working in the same way!

2016-12-13 17:05 UTC, alpaix commented
@jainaashish Will arrange a perf test run to verify whether this change increase startup time.

2016-12-13 17:11 UTC, alpaix commented on src/NuGet.Clients/NuGet.SolutionRestoreManager/NuGet.SolutionRestoreManager.csproj
> +    <Reference Include="envdte80, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a">
`EnvDTE80.DTE2` is needed in certain cases to get access to advanced extensibility functionality.

2016-12-13 17:47 UTC, jainaashish requested changes
waiting for the perf test result

2016-12-14 18:30 UTC, alpaix commented
Performance test ValBuild Dev15 $/DevDiv/auxsrc/vs/d15rel.26013.00.alpanov.161213.160152 RPS V3 DDRIT TH2 did not discover any regressed scenarios.

2016-12-14 22:58 UTC, jainaashish approved these changes

2016-12-14 23:17 UTC, merged