added allowprereleasedependencies flag in pack
NuGet/NuGet.Client pull request #1073
Opened 2016-12-21 23:27 UTC by rohit21agrawal

Fixes : https://github.com/NuGet/Home/issues/3938

For dotnet pack scenarios, the flag is set to true by default, thus this would be an opt-out behavior. The corresponding msbuild property that controls this behavior is : $(AllowPrereleaseDependencies)

For nuget.exe scenarios, the flag is set to false, so this will be an opt-in behavior. The command line option is -AllowPrereleaseDependencies

What this basically does is allow you to control whether you can have prerelease dependencies in a stable version of a package when executing pack.

CC: @emgarten @alpaix @jainaashish @joelverhagen @mishra14 @rrelyea @yishaigalatzer

2016-12-28 21:05 UTC, emgarten commented on src/NuGet.Core/NuGet.Build.Tasks.Pack.Library/Pack.targets
> +    <AllowPrereleaseDependencies Condition=" '$(AllowPrereleaseDependencies)' == '' ">true</AllowPrereleaseDependencies>
I would expect this to be false by default

2016-12-28 21:05 UTC, emgarten commented on src/NuGet.Core/NuGet.Commands/CommandArgs/PackArgs.cs
> +        public bool AllowPrereleaseDependenciesInProductionPackage { get; set; }
how about ``AllowPrereleaseDependenciesInStablePackage``?

I'm not sure Production is the opposite of pre-release.

2016-12-28 21:06 UTC, emgarten requested changes
waiting on default

2016-12-29 22:57 UTC, rohit21agrawal commented
@emgarten as per our discussion, i have changed this to a package analysis rule.

2016-12-30 01:19 UTC, emgarten commented on src/NuGet.Core/NuGet.Commands/Rules/AnalysisResources.resx
> +    <value>Either modify the version spec of dependency "{0}" or update the version field in the nuspec.</value>
nit: typically single quotes are used around fields like this

2016-12-30 01:22 UTC, emgarten approved these changes

2016-12-30 01:25 UTC, merged

2017-04-05 07:58 UTC, Henrik-R commented
When will this fix be released?

2017-11-22 15:35 UTC, shytikov commented
Ok, guys, haven't you considered that this function (to fail pack project with pre-release dependencies) is actually used by someone in production?

Is it possible to create switch to keep old behavior untouched?