Use IProjectThreadingService in NuGetUIThreadHelper
NuGet/NuGet.Client pull request #1118
Opened 2017-01-12 00:38 UTC by emgarten

Update the NuGetUIThreadHelper to use IProjectThreadingService for VS 2017 and IThreadHandling for VS 2015. These JoinableTaskFactories are able to work with the CPS project system used by .NETCore projects and avoid hangs.

NuGetUIThreadHelper will now get a JTF from the ProjectService based on the version of VS.

Everywhere I could find that might access a CPS project has been moved to use NuGetUIThreadHelper, and in my testing this fixes the hang.

Other places in the code still use the shell JTF for UI only operations.

Fixes https://github.com/NuGet/Home/issues/4185

//cc @jviau @alpaix @zhili1208 @rrelyea @jainaashish @mishra14 @rohit21agrawal @AArnott

2017-01-12 04:15 UTC, AArnott approved these changes
Looks reasonable.

2017-01-12 04:15 UTC, AArnott commented on src/NuGet.Clients/NuGet.VisualStudio.Implementation/Extensibility/VsPackageInstaller.cs
> +using NuGet.PackageManagement.UI;
Ordering?

2017-01-12 04:15 UTC, AArnott commented on src/NuGet.Clients/NuGet.VisualStudio.Implementation/Extensibility/VsPackageInstallerServices.cs
> +using NuGet.PackageManagement.UI;
Sorting again

2017-01-12 04:35 UTC, alpaix commented on src/NuGet.Clients/VisualStudio.Facade/NuGetUIThreadHelper.cs
> +            ProjectService projectService = projectServiceAccessor.GetProjectService();
use `var`

2017-01-12 04:40 UTC, alpaix commented on src/NuGet.Clients/NuGet.Tools/NuGetPackage.cs
> +            NuGetUIThreadHelper.SetJoinableTaskFactoryFromService(ServiceLocator.PackageServiceProvider);
don't use `ServiceLocator`. `PackageServiceProvider` is just `NuGetPackage` so simply pass `this`.
And also `componentModel` is fetched already, consider passing it instead.

2017-01-12 04:42 UTC, alpaix requested changes
`NuGetUIThreadHelper` should be initialized by the `RestoreManagerPackage` as well. Whichever package is loaded first.

And then consider lazy initialization of the helper as this change can bring perf down again.

2017-01-12 20:23 UTC, jviau commented on src/NuGet.Clients/VisualStudio.Facade/NuGetUIThreadHelper.cs
> +            _joinableTaskFactory = service.AsyncPump;
Did you mean to use `threadHandling` here and not `service` ?

2017-01-12 20:38 UTC, jainaashish commented on src/NuGet.Clients/VisualStudio.Facade/NuGetUIThreadHelper.cs
> +            IProjectService projectService = projectServiceAccessor.GetProjectService();
Couldn't we take `projectService` and `threadHandling `out of this codition and just use `AsyncPump `or `JoinableTaskFactory `based on VS version?

2017-01-12 20:40 UTC, jainaashish commented on src/NuGet.Clients/VsConsole/PowerShellHost/NuGetConsole.Host.PowerShell.csproj
> +    <ProjectReference Include="..\..\VisualStudio.Facade\NuGet.VisualStudio.Facade.csproj">
why do we need to add this ProjectReference? I don't see any other change in PowerShellHost project...

2017-01-13 00:30 UTC, emgarten commented on src/NuGet.Clients/VisualStudio.Facade/NuGetUIThreadHelper.cs
> +            IProjectService projectService = projectServiceAccessor.GetProjectService();
That API isn't currently in our dev14 build. Also, the threading docs say to use this for dev15.

2017-01-13 00:30 UTC, emgarten commented on src/NuGet.Clients/VsConsole/PowerShellHost/NuGetConsole.Host.PowerShell.csproj
> +    <ProjectReference Include="..\..\VisualStudio.Facade\NuGet.VisualStudio.Facade.csproj">
``NuGetUIThreadHelper`` moved

2017-01-13 00:31 UTC, emgarten commented on src/NuGet.Clients/VisualStudio.Facade/NuGetUIThreadHelper.cs
> +            _joinableTaskFactory = service.AsyncPump;
yes, good catch!

2017-01-13 00:41 UTC, emgarten commented on src/NuGet.Clients/VisualStudio.Facade/NuGetUIThreadHelper.cs
> +            ProjectService projectService = projectServiceAccessor.GetProjectService();
I'm going to leave this as is. With the compiler flags it is harder to determine these types and there is a key difference in that one is ``ProjectService`` and the other is ``IProjectService``

2017-01-13 02:03 UTC, emgarten commented on src/NuGet.Clients/NuGet.Tools/NuGetPackage.cs
> +            NuGetUIThreadHelper.SetJoinableTaskFactoryFromService(ServiceLocator.PackageServiceProvider);
Good call, I've updated this to use the already created componentModel reference

2017-01-13 02:08 UTC, jainaashish approved these changes

2017-01-13 02:16 UTC, alpaix approved these changes

2017-01-13 18:14 UTC, closed without merging