Fixed UI version list sync
NuGet/NuGet.Client pull request #1125
Opened 2017-01-14 00:40 UTC by zhili1208

fixed https://github.com/NuGet/Home/issues/4198
@jainaashish @alpaix

2017-01-14 01:29 UTC, alpaix commented on src/NuGet.Clients/PackageManagement.UI/Feeds/MultiSourcePackageMetadataProvider.cs
> +                completed = tasks.Where(m => m != null && !m.IsFaulted && m.Result != null).Select(m => m.Result);
`m` is a `Task` so no need to check for null.
Check if it `IsCompleted` and not `IsFaulted` and not `IsCancelled`.

2017-01-14 01:30 UTC, alpaix commented on src/NuGet.Clients/PackageManagement.UI/Feeds/MultiSourcePackageMetadataProvider.cs
> +                return new List<VersionInfo>();
`Enumerable.Empty<VersionInfo>()`

2017-01-14 01:31 UTC, alpaix commented on src/NuGet.Clients/PackageManagement.UI/Feeds/MultiSourcePackageMetadataProvider.cs
> +                completed = tasks.Where(m => m != null && !m.IsFaulted && m.Result != null).Select(m => m.Result);
Convert it `.ToList()` as you enumerate the sequence more than once.

2017-01-14 01:31 UTC, alpaix commented on src/NuGet.Clients/PackageManagement.UI/Feeds/MultiSourcePackageMetadataProvider.cs
> +                    .Where(m => m != null);
`ToList()`

2017-01-14 01:32 UTC, alpaix commented on src/NuGet.Clients/PackageManagement.UI/Feeds/MultiSourcePackageMetadataProvider.cs
> +            IEnumerable<IPackageSearchMetadata> completed = null;
change to `List<...>`

2017-01-14 01:33 UTC, alpaix commented on src/NuGet.Clients/PackageManagement.UI/Feeds/MultiSourcePackageMetadataProvider.cs
> +            if (completed.Count() == 0)
use `List.Count` property

2017-01-14 01:33 UTC, emgarten commented on src/NuGet.Clients/PackageManagement.UI/Feeds/MultiSourcePackageMetadataProvider.cs
> +                completed = (await Task.WhenAll(tasks))
if this throws does it still wait for all tasks to complete?

2017-01-14 01:34 UTC, emgarten commented on src/NuGet.Clients/PackageManagement.UI/Feeds/MultiSourcePackageMetadataProvider.cs
> +                completed = (await Task.WhenAll(tasks))
it might be easier to just do a foreach on the tasks, await each yourself in a try/catch and append the result to a list

2017-01-14 01:35 UTC, alpaix commented on src/NuGet.Clients/PackageManagement.UI/Models/DetailControlModel.cs
> +            InfiniteScrollList packageList)
Don't pass the entire control to a model. The only bit needed here is `SelectedItem`.

2017-01-14 01:37 UTC, jainaashish commented
Please give some background about the PR, what was the current issue vs the solution. otherwise it becomes difficult to connect the dots.

2017-01-14 02:08 UTC, alpaix commented on src/NuGet.Clients/PackageManagement.UI/Feeds/MultiSourcePackageMetadataProvider.cs
> +                completed = (await Task.WhenAll(tasks))
If the idea is to ignore errors here then I'd suggest creating "safe" individual tasks
```cs
try
{
  return r.GetPackageMetadataAsync(identity, includePrerelease, cancellationToken);
}
catch
{
  return null;
}```

2017-01-14 02:18 UTC, alpaix commented on src/NuGet.Clients/PackageManagement.UI/Models/DetailControlModel.cs
> +            InfiniteScrollList packageList)
In case you need a predicate then use `Func<PackageItemListViewModel>` as argument

2017-01-14 02:23 UTC, alpaix commented on src/NuGet.Clients/PackageManagement.UI/Models/DetailControlModel.cs
> +            var versions = await searchResultPackage.GetVersionsAsync();
start/create the task at the beginning of the method, and await it here.

2017-01-14 02:25 UTC, alpaix requested changes
Address the comments.

2017-01-17 21:50 UTC, alpaix commented on src/NuGet.Clients/PackageManagement.UI/Feeds/MultiSourcePackageMetadataProvider.cs
> +            List<IPackageSearchMetadata> completed = new List<IPackageSearchMetadata>();
nit: use `var`

2017-01-17 22:00 UTC, alpaix commented on src/NuGet.Clients/PackageManagement.UI/Feeds/MultiSourcePackageMetadataProvider.cs
> +                    if (task.IsCompleted && result != null)
no need to check `task.IsCompleted` after it's been awaited.

2017-01-17 22:04 UTC, alpaix approved these changes
Couple of minor notes, then :shipit:

2017-01-17 22:37 UTC, jainaashish approved these changes

2017-01-20 17:53 UTC, rrelyea commented on src/NuGet.Clients/PackageManagement.UI/Feeds/MultiSourcePackageMetadataProvider.cs
> +                    var result = await task;
triage question - are we going from parallel to non-parallel version of this. don't make enumerate slower/worse.

2017-01-20 18:12 UTC, zhili1208 commented on src/NuGet.Clients/PackageManagement.UI/Feeds/MultiSourcePackageMetadataProvider.cs
> +                    var result = await task;
No, I think we are still parallel, all tasks are already started at line 194. Here we just fetch the result one by one

2017-01-24 18:46 UTC, rrelyea commented
@emgarten, @alpaix - can you please look at that last change?

2017-01-24 20:56 UTC, alpaix approved these changes

2017-01-25 22:15 UTC, closed without merging