add output message when nupkg is packed successfully
NuGet/NuGet.Client pull request #1130
Opened 2017-01-18 01:02 UTC by rohit21agrawal

Fixes: https://github.com/NuGet/Home/issues/4294

CC: @emgarten @rrelyea @alpaix @mishra14 @zhili1208 @jainaashish @nkolev92

2017-01-18 01:16 UTC, emgarten requested changes
questions on localization

2017-01-18 01:16 UTC, emgarten commented on src/NuGet.Core/NuGet.Build.Tasks.Pack.Library/Pack.targets
> +    <Message Text="Project packed successfully. Output available at $(PackageOutputAbsolutePath)" Importance="High"/>
Should this be localized?

2017-01-18 01:16 UTC, emgarten commented on src/NuGet.Core/NuGet.Build.Tasks.Pack.Library/Pack.targets
> +      <Output TaskParameter="AbsolutePaths" PropertyName="PackageOutputAbsolutePath" />
should ``PackageOutputPath="$(PackageOutputPath)"`` be changed also?

2017-01-19 20:03 UTC, rohit21agrawal commented on src/NuGet.Core/NuGet.Build.Tasks.Pack.Library/Pack.targets
> +      <Output TaskParameter="AbsolutePaths" PropertyName="PackageOutputAbsolutePath" />
fixed

2017-01-19 20:04 UTC, rohit21agrawal commented
@emgarten i used the underlying msbuild logger to workaround the localization issue, thanks for your suggestion :)

2017-01-19 22:51 UTC, emgarten approved these changes

2017-01-19 22:54 UTC, merged