add pri files to the build outputs for pack in uwp related projects
NuGet/NuGet.Client pull request #1133
Opened 2017-01-18 20:13 UTC by rohit21agrawal

Fixes: https://github.com/NuGet/Home/issues/4136

Adds the Pri file that is generated in projects targeting uap10.0 / win8 etc. We figure out the existence of this file using the msbuild property $(IncludeProjectPriFile) and then add it to our item group using the $(ProjectPriFullPath) property.

Also added .pri to the list of extensions that can be included in the lib folder.

CC: @emgarten @alpaix @rrelyea @mishra14 @nkolev92 @jainaashish @zhili1208

2017-01-18 20:32 UTC, emgarten requested changes
this fix looks safe, how about an e2e test?

2017-01-18 21:03 UTC, rohit21agrawal commented
@emgarten since targets for UWP apps do not lie inside the dotnet sdk directory, our tests aren't currently equipped to handle this. once we have that infrastructure in place in the future, we will add tests for specific frameworks too.

2017-01-18 21:13 UTC, emgarten approved these changes

2017-01-18 21:15 UTC, merged

2017-01-31 13:13 UTC, onovotny commented
Is this supposed to be in RC3 or only RTM? I just tested RC3 and don't see the pri's in the package

2017-01-31 18:26 UTC, emgarten commented
@onovotny RTM