Improve DownloadTimeoutStream reads
NuGet/NuGet.Client pull request #1134
Opened 2017-01-19 08:40 UTC by emgarten

This change avoids calls to DownloadTimeoutStream.Read by reading streams into MemoryStreams using CopyToStreamAsync which uses DownloadTimeoutStream.ReadAsync instead.

I tried a build with DownloadTimeoutStream.Read set to throw an exception if used and was able to use the UI, install, and restore from v2, v3, and various project types. 

In some scenarios .Read may still be used such as direct download. There could also be edge where this is still needed by the command line so I am going to leave this method as is instead of removing support for it.

Fixes https://github.com/NuGet/Home/issues/4266

//cc @joelverhagen @alpaix @jainaashish @rrelyea

2017-01-19 16:04 UTC, joelverhagen approved these changes
Yup, this looks right. A couple unit tests verifying these callers indeed don't call `Stream.Read` would be beneficial though.

2017-01-19 17:16 UTC, alpaix commented on src/NuGet.Core/NuGet.Protocol.Core.v3/Providers/ServiceIndexResourceV3Provider.cs
> +        private async Task<ServiceIndexResourceV3> ConsumeServiceIndexStream(Stream stream, DateTime utcNow)
`ConsumeServiceIndexStreamAsync`

2017-01-19 17:17 UTC, alpaix commented on src/NuGet.Core/NuGet.Protocol.Core.v3/RemoteRepositories/HttpFileSystemBasedFindPackageByIdResource.cs
> +        private async Task<SortedDictionary<NuGetVersion, PackageInfo>> ConsumeFlatContainerIndex(Stream stream, string id, string baseUri)
the same

2017-01-19 17:20 UTC, alpaix commented on src/NuGet.Core/NuGet.Protocol.Core.v3/Utility/StreamExtensions.cs
> +            if (stream?.CanSeek != false)
return `null` if `stream` is null for better readability.

2017-01-19 17:22 UTC, alpaix commented on src/NuGet.Core/NuGet.Protocol.Core.v3/Utility/StreamExtensions.cs
> +                stream.Position = 0;
...and this IS actually a bug - it'll throw when stream is null

2017-01-19 17:23 UTC, alpaix commented on src/NuGet.Core/NuGet.Protocol.Core.v3/Utility/StreamExtensions.cs
> +                    using (stream)
would prefer explicit `stream.Dispose()`

2017-01-19 17:24 UTC, alpaix requested changes
Address the feedback. Please add tests.

2017-01-19 18:14 UTC, emgarten commented on src/NuGet.Core/NuGet.Protocol.Core.v3/Utility/StreamExtensions.cs
> +                stream.Position = 0;
good catch, I'll update this

2017-01-20 01:14 UTC, emgarten commented
Updated based on feedback.

I'm still investigating how to inject a test stream to verify that other readers aren't calling ``.Read``

2017-01-20 01:43 UTC, emgarten commented
🔔  tests added, I've updated *TestHttpSource* to optionally wrap all streams. This lets the test stream verify that .Read was not called.

2017-01-20 02:12 UTC, alpaix approved these changes
LG2M ✨ !

2017-01-20 02:18 UTC, joelverhagen approved these changes
Nice!

2017-01-20 02:29 UTC, merged