AutoReferenced support
NuGet/NuGet.Client pull request #1158
Opened 2017-01-31 18:52 UTC by emgarten

Add support for AutoReferenced package references.

https://github.com/NuGet/Home/issues/4044

//cc @rrelyea

2017-01-31 19:41 UTC, Meir017 commented on src/NuGet.Clients/PackageManagement.UI/Common/PackageCollection.cs
> +                    .GroupBy(e => e.PackageIdentity)
can join `group by` and `select` into a single `group by`

`.GroupBy(e => e.PackageIdentity, (key, group) =>new PackageCollectionItem(key.Id, key.Version, group) )`

2017-01-31 19:57 UTC, emgarten commented on src/NuGet.Clients/PackageManagement.UI/Common/PackageCollection.cs
> +                    .GroupBy(e => e.PackageIdentity)
I like it, thanks :smile:

2017-02-01 00:38 UTC, rohit21agrawal commented on src/NuGet.Clients/PackageManagement.UI/Models/DetailControlModel.cs
> +            var projects = _nugetProjects.Where(project => !(project is ProjectKNuGetProjectBase)).ToArray();
can you add a comment explaining what kind of projects you are filtering out?

2017-02-01 00:42 UTC, rohit21agrawal commented on src/NuGet.Clients/PackageManagement.UI/Xamls/ProjectView.xaml
> -      Visibility="{Binding InstalledVersion, Converter={StaticResource NullToVisibilityConverter}, Mode=OneWay}"
we want to make it always visible?

2017-02-01 01:03 UTC, emgarten commented on src/NuGet.Clients/PackageManagement.UI/Xamls/ProjectView.xaml
> -      Visibility="{Binding InstalledVersion, Converter={StaticResource NullToVisibilityConverter}, Mode=OneWay}"
maybe it could have both thinking about it now. I think for installed packages that cannot be uninstalled disabled is more clear.

2017-02-01 05:28 UTC, emgarten commented
🔔  @rohit21agrawal updated

2017-02-01 15:42 UTC, rohit21agrawal commented on src/NuGet.Clients/PackageManagement.PowerShellCmdlets/Cmdlets/GetPackageCommand.cs
> +            return (reference as BuildIntegratedPackageReference)?.Dependency?.AutoReferenced == true;
nit: no need for == true.

2017-02-01 15:42 UTC, rohit21agrawal commented on src/NuGet.Core/NuGet.LibraryModel/LibraryDependency.cs
> +        public bool AutoReferenced { get; set; }
IsAutoReferenced instead of AutoReferenced?

2017-02-01 15:50 UTC, rohit21agrawal commented on src/NuGet.Clients/PackageManagement.UI/Models/DetailControlModel.cs
> +            if (blockedVersions.Length > 0)
>blockedVersions [](start = 16, length = 15)

null check?

2017-02-01 15:50 UTC, rohit21agrawal commented on src/NuGet.Clients/PackageManagement.UI/Models/DetailControlModel.cs
> +                OptionsBlockedUrl = new Uri("https://go.microsoft.com/fwlink/?linkid=841238");
this link redirects to : [https://docs.microsoft.com/en-gb/](https://docs.microsoft.com/en-gb/) ..doesn't seem right.

2017-02-01 15:53 UTC, rohit21agrawal commented on src/NuGet.Core/NuGet.LibraryModel/LibraryDependency.cs
> +        public bool AutoReferenced { get; set; }
IsAutoReferenced instead of AutoReferenced?

2017-02-01 15:54 UTC, rohit21agrawal commented on src/NuGet.Clients/PackageManagement.UI/Xamls/ProjectView.xaml
> -      Visibility="{Binding InstalledVersion, Converter={StaticResource NullToVisibilityConverter}, Mode=OneWay}"
yes, so i wouldn't remove the Visibility property from here. For projects that are AutoReferenced, the InstalledVersion won't be null, right?

---
In reply to: [98809702](https://github.com/NuGet/NuGet.Client/pull/1158#discussion_r98809702) [](ancestors = 98809702)

2017-02-01 19:23 UTC, emgarten commented on src/NuGet.Clients/PackageManagement.UI/Models/DetailControlModel.cs
> +                OptionsBlockedUrl = new Uri("https://go.microsoft.com/fwlink/?linkid=841238");
the doc hasn't been written yet

2017-02-01 19:24 UTC, emgarten commented on src/NuGet.Clients/PackageManagement.PowerShellCmdlets/Cmdlets/GetPackageCommand.cs
> +            return (reference as BuildIntegratedPackageReference)?.Dependency?.AutoReferenced == true;
this returns a ``bool?`` since it uses ``?``, ``== true`` converts ``bool? -> bool``

2017-02-01 19:30 UTC, emgarten commented on src/NuGet.Core/NuGet.LibraryModel/LibraryDependency.cs
> +        public bool AutoReferenced { get; set; }
I'm going to keep everything consistent with the project property name, I think this name works as is.

2017-02-01 19:52 UTC, emgarten commented on src/NuGet.Clients/PackageManagement.UI/Models/DetailControlModel.cs
> +            if (blockedVersions.Length > 0)
this can't be null, since this isn't a public method I think the expectation that this is already valid within the class is fine. thoughts?

2017-02-01 20:10 UTC, rohit21agrawal commented on src/NuGet.Clients/PackageManagement.UI/Models/DetailControlModel.cs
> +            if (blockedVersions.Length > 0)
yeah, just checked the code for possible codepaths..seems fine

2017-02-01 20:11 UTC, rohit21agrawal commented
LGTM
:shipit:

2017-02-01 20:13 UTC, rohit21agrawal approved these changes

2017-02-01 21:23 UTC, alpaix commented on src/NuGet.Clients/NuGet.SolutionRestoreManager/VsSolutionRestoreService.cs
> +        private static bool GetPropertyBoolOrDefault(
nit: `GetPropertyBoolOrFalse` for clarity

2017-02-01 21:26 UTC, alpaix commented on src/NuGet.Clients/PackageManagement.UI/Common/PackageCollectionItem.cs
> +﻿using NuGet.Packaging;
+ header

2017-02-01 21:26 UTC, alpaix commented on src/NuGet.Clients/PackageManagement.UI/Common/PackageCollectionItem.cs
> +using System.Collections.Generic;
`System` on top

2017-02-01 21:28 UTC, alpaix commented on src/NuGet.Clients/PackageManagement.UI/Common/PackageCollection.cs
> +        public static bool IsAutoReferenced(this PackageCollectionItem package)
why not `PackageCollectionItem.IsAutoReferenced` class (not extension) method?

2017-02-01 23:49 UTC, emgarten commented on src/NuGet.Clients/PackageManagement.UI/Common/PackageCollection.cs
> +        public static bool IsAutoReferenced(this PackageCollectionItem package)
It could be either, I think it fits better here with the rest of the helper methods for these classes.

2017-02-02 00:02 UTC, emgarten commented on src/NuGet.Clients/PackageManagement.UI/Common/PackageCollectionItem.cs
> +using System.Collections.Generic;
Dev15 needs to stop losing that setting :smile:

2017-02-02 00:40 UTC, emgarten commented
🔔 @alpaix updated

2017-02-02 00:53 UTC, jainaashish commented on src/NuGet.Clients/NuGet.SolutionRestoreManager/VsSolutionRestoreService.cs
> +            }
Could it also throw InvalidCastException as we saw in case of TargetFramework/ TargetFrameworks properties value?

2017-02-02 00:56 UTC, emgarten commented on src/NuGet.Clients/NuGet.SolutionRestoreManager/VsSolutionRestoreService.cs
> +            }
Shouldn't be possible, we are only dealing with this as a string.
https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Commands/Utility/MsBuildStringUtility.cs#L66

2017-02-02 01:03 UTC, jainaashish approved these changes
Looks good

2017-02-02 02:17 UTC, alpaix approved these changes

2017-02-02 19:41 UTC, mishra14 requested changes
Some nit changes and comments.

2017-02-02 19:41 UTC, mishra14 commented on src/NuGet.Clients/NuGet.SolutionRestoreManager/VsSolutionRestoreService.cs
> +            }
Why are we ignoring these exceptions?

2017-02-02 19:41 UTC, mishra14 commented on src/NuGet.Clients/PackageManagement.UI/Common/PackageCollection.cs
> +        public static bool IsAutoReferenced(this PackageCollectionItem package)
@alpaix : considering that we also have `VersionCollectionExtensions ` in here, this seems fine. if we move this class into `PackageCollectionItem`, we should address the `VersionCollectionExtensions ` as well.

2017-02-02 19:41 UTC, mishra14 commented on src/NuGet.Clients/PackageManagement.UI/Models/DetailControlModel.cs
> +                        var constaint = new ProjectVersionConstraint()
nit: `var constraint`

2017-02-02 19:41 UTC, mishra14 commented on src/NuGet.Clients/PackageManagement.UI/Models/DetailControlModel.cs
> +                        _projectVersionConstraints.Add(constaint);
nit: `_projectVersionConstraints.Add(constraint);`

2017-02-02 19:41 UTC, mishra14 commented on src/NuGet.Clients/PackageManagement.UI/Models/DetailControlModel.cs
> +                        var constaint = new ProjectVersionConstraint()
nit: `var constraint`

2017-02-02 19:41 UTC, mishra14 commented on src/NuGet.Clients/PackageManagement.UI/Models/DetailControlModel.cs
> +                        _projectVersionConstraints.Add(constaint);
nit: `var constraint`

2017-02-02 19:41 UTC, mishra14 commented on src/NuGet.Clients/PackageManagement.UI/Models/DetailControlModel.cs
> +
nit: don't need this line :P

2017-02-02 19:41 UTC, mishra14 commented on src/NuGet.Clients/PackageManagement.UI/Models/DetailControlModel.cs
> +                OnPropertyChanged(nameof(OptionsBlockedMessage));
Why are we calling `OnPropertyChanged(nameof(OptionsBlockedMessage));` on setting `OptionsBlockedUrl` ?

2017-02-02 19:41 UTC, mishra14 commented on src/NuGet.Clients/PackageManagement.UI/Models/PackageDetailControlModel.cs
> +                _versions.Add(new DisplayVersion(version, string.Empty, isCurrentInstalled: installed, autoReferenced: autoReferenced));
nit: (new DisplayVersion(version, **additionalInfo**: string.Empty, isCurrentInstalled: installed, autoReferenced: autoReferenced));

2017-02-02 19:41 UTC, mishra14 commented on src/NuGet.Clients/PackageManagement.UI/Models/PackageStatus.cs
> +        // The package is installed but may not be managed.
👍

2017-02-02 19:41 UTC, mishra14 commented on src/NuGet.Clients/PackageManagement.UI/Xamls/DetailControl.xaml
> +
nit: clear spaces.

2017-02-02 19:41 UTC, mishra14 commented on src/NuGet.Core/NuGet.ProjectManagement/BuildIntegratedPackageReference.cs
> +            return dependency.LibraryRange?.VersionRange;
Where do we handle the case if this is null?

2017-02-02 19:41 UTC, mishra14 commented on test/NuGet.Clients.Tests/NuGet.PackageManagement.UI.Test/Feeds/UpdatePackageFeedTests.cs
> +            var testPackageIdentity = new PackageCollectionItem("FakePackage", new NuGetVersion("1.0.0"), null);
please make the null arg as a named parameter to make the call clearer.

2017-02-02 19:41 UTC, mishra14 commented on test/NuGet.Core.Tests/NuGet.ProjectModel.Test/compiler/resources/PackageSpecWriter_Write_SerializesMembersAsJson.json
> +    "crossTargeting": true,
👍

2017-02-02 20:23 UTC, emgarten commented on src/NuGet.Clients/NuGet.SolutionRestoreManager/VsSolutionRestoreService.cs
> +            }
These are possible exceptions from IVsReferenceItem. We want to check if the property exists as true here, all other scenarios should result in false.

2017-02-02 20:24 UTC, emgarten commented on src/NuGet.Clients/PackageManagement.UI/Models/DetailControlModel.cs
> +                OnPropertyChanged(nameof(OptionsBlockedMessage));
The two are combined later on, if we update the url the UI should also update the message.

2017-02-02 20:26 UTC, emgarten commented on src/NuGet.Core/NuGet.ProjectManagement/BuildIntegratedPackageReference.cs
> +            return dependency.LibraryRange?.VersionRange;
We want to return null here, the UI handles null which is the default.

2017-02-02 20:26 UTC, emgarten commented on test/NuGet.Clients.Tests/NuGet.PackageManagement.UI.Test/Feeds/UpdatePackageFeedTests.cs
> +            var testPackageIdentity = new PackageCollectionItem("FakePackage", new NuGetVersion("1.0.0"), null);
test code

2017-02-02 20:30 UTC, mishra14 approved these changes
Besides nit changes, signing off.

2017-02-02 20:43 UTC, emgarten commented on src/NuGet.Clients/PackageManagement.UI/Models/DetailControlModel.cs
> +
clarity of code :smile:

2017-02-02 22:16 UTC, closed without merging