Upgrade VSIX V2->V3 - Closes #4196
NuGet/NuGet.Client pull request #1164
Opened 2017-02-01 20:49 UTC by nkolev92

This closes NuGet/Home#4196

As of D15, VS Team plans to drop support for VSIX V2.
V3 VSIX adds some new requirements to both csproj and the manifest.

V3 also dropped supports for ShortcutPath, that MSBuild uses. 
Due to that we have to install NuGet in a static location in CommonExtensions/Microsoft/NuGet.

By doing that though we lose the ability to upgrade our VSIX easily. We cannot simply uninstall an AllUsers VSIX because it'll break workflows that depend on NuGet. Due to that they don't support uninstalling of VSIXs. 

To alleviate this, we will build another VSIX that's experimental.
This allows it to be installed a user's location. However the drawback of this is that MSBuild will still use the CommonExtensions/Microsoft/NuGet version. There's currently no way to support both scenarios.

To minimize changes to our current workflows, the 
/artifacts/VS15/NuGet.Tools.vsix version is an experimental. That it meant to be used in private build and will be the one that's wrapped in the 1ES package.
/artifacts/VS15/Insertable/NuGet.Tools.vsix is an AllUsers one. In WSR-TC this will be spit out at the /VSIX/15Ins/ location. 

As the VS insertion depends on a <packageId>.json file that's generated next to a VSIX now, we propagate that to our NuGetCi drop.

2017-02-01 22:10 UTC, alpaix commented on scripts/e2etests/InstallNuGetVSIX.ps1
> -
Revert if there's no actual changes

2017-02-01 22:13 UTC, alpaix commented on src/NuGet.Clients/NuGet.Tools/NuGet.Tools.csproj
> +  <PropertyGroup Condition="'$(VisualStudioVersion)' == '15.0' AND '$(Insertable)' == 'true'">
Rename to `$(IsInsertable)` similar to `$(IsProductComponent)`

2017-02-01 22:16 UTC, alpaix commented on src/NuGet.Clients/NuGet.Tools/NuGet.Tools.csproj
> +    <Message Text="$(ArtifactRoot)\NuGet.Tools\15.0\$(Configuration)\Microsoft.VisualStudio.NuGet.Core.json -&gt; $(PublishDestination)" Importance="high" />
Define a property for the full path

2017-02-01 22:17 UTC, alpaix commented on src/NuGet.Clients/NuGet.Tools/source.extension.vs15.vsixmanifest
> +    <DisplayName>NuGet Package Manager for Visual Studio 17</DisplayName>
Visual Studio 2017 or Visual Studio "15"

2017-02-01 22:23 UTC, alpaix commented on src/NuGet.Clients/NuGet.Tools/source.extension.vs15.insertable.vsixmanifest
> +    <DisplayName>NuGet Package Manager for Visual Studio 17</DisplayName>
Fix the name

2017-02-01 22:37 UTC, alpaix commented on src/NuGet.Clients/NuGet.Tools/NuGet.Tools.csproj
> +    <Message Text="$(ArtifactRoot)\NuGet.Tools\15.0\$(Configuration)\Microsoft.VisualStudio.NuGet.Core.json -&gt; $(PublishDestination)" Importance="high" />
Also, use `$(OutDir)` for the output file location

2017-02-01 22:40 UTC, alpaix commented on src/NuGet.Clients/NuGet.Tools/NuGet.Tools.csproj
> +  <Target Name="AfterBuild" DependsOnTargets="AfterBuild14;AfterBuild15;AfterBuildIns15"/>
I'd suggest naming targets respectively: `PublishVS14`, `PublishVS15`, and `PublishVS15Insertable`

2017-02-01 22:43 UTC, alpaix commented on build.ps1
> +    -skip:$SkipVS15 `
I presume this build step should be running on CI only. If so then
`-skip:($SkipVS15 -or -not $CI)`

2017-02-01 22:47 UTC, alpaix commented on src/NuGet.Clients/NuGet.Tools/NuGet.Tools.csproj
> +    <Message Text="$(ArtifactRoot)\NuGet.Tools\15.0\$(Configuration)\Microsoft.VisualStudio.NuGet.Core.json -&gt; $(PublishDestination)" Importance="high" />
Actually this file should be an item, similar to `$(NuGetSymbolFiles)`

2017-02-01 22:48 UTC, alpaix requested changes
Address the comments.

2017-02-01 22:51 UTC, nkolev92 commented on src/NuGet.Clients/NuGet.Tools/NuGet.Tools.csproj
> +    <Message Text="$(ArtifactRoot)\NuGet.Tools\15.0\$(Configuration)\Microsoft.VisualStudio.NuGet.Core.json -&gt; $(PublishDestination)" Importance="high" />
Change PublishDestination to OutDir or?

2017-02-01 22:55 UTC, alpaix commented on src/NuGet.Clients/NuGet.Tools/NuGet.Tools.csproj
> +    <Message Text="$(ArtifactRoot)\NuGet.Tools\15.0\$(Configuration)\Microsoft.VisualStudio.NuGet.Core.json -&gt; $(PublishDestination)" Importance="high" />
Path to the generated file should be `$(OutputPath)Microsoft.VisualStudio.NuGet.Core.json`

2017-02-01 22:55 UTC, nkolev92 commented on build.ps1
> +    -skip:$SkipVS15 `
It should run on local builds as well. That way it's easy to install your own local bits.

2017-02-01 23:41 UTC, nkolev92 commented
🔔

2017-02-02 00:27 UTC, alpaix commented on src/NuGet.Clients/NuGet.Tools/NuGet.Tools.csproj
> +      <ManifestPath Include="$(OutputPath)Microsoft.VisualStudio.NuGet.Core.json"/>
if it's an item (not property) it should be named like `ManifestV3File`

2017-02-02 00:29 UTC, alpaix approved these changes
Overall looks :sparkles:

Address the suggestion for better item naming.
Squash before merging!

2017-02-03 02:23 UTC, merged