Skip on-build restore for pure .NET Core solutions
NuGet/NuGet.Client pull request #1177
Opened 2017-02-07 20:15 UTC by alpaix

Addresses NuGet/Home#4225.

Determine if a solution contains .NET Core projects only (Roslyn project
system) and no LSL enabled. In this case skip on-buld restore as
redundant. Auto-restore should be sufficient for this scenario.

//cc @rrelyea @lifengl

2017-02-07 20:31 UTC, emgarten commented
What about rebuild? It looks like the force restore flag is ignored here. Are we confident that this override will no longer be needed?

2017-02-07 20:32 UTC, emgarten commented on src/NuGet.Clients/NuGet.SolutionRestoreManager/SolutionRestoreWorker.cs
> +                                && SolutionManager.GetNuGetProjects().All(p => p is CpsPackageReferenceProject))
If there are zero projects it looks like this new code path would be used. Which could bring some minor behavior changes. Maybe an explicit project count check should be done here, or return separately for that reason.

2017-02-07 20:32 UTC, emgarten requested changes
Waiting on questions

2017-02-07 20:36 UTC, jainaashish commented on src/NuGet.Clients/NuGet.SolutionRestoreManager/SolutionRestoreWorker.cs
> +#if VS15
Would be better to use !VS14

2017-02-07 20:38 UTC, jainaashish commented on src/NuGet.Clients/NuGet.SolutionRestoreManager/SolutionRestoreWorker.cs
> +                            {
Why don't we move this check to `RestoreManagerPackage` itself and skip getting into SolutionRestoreWorker if it isn't requried at all, which will also save on unnecessary `JTF.Run` and `JoinableCollection.Join()`

2017-02-07 21:10 UTC, alpaix commented on src/NuGet.Clients/NuGet.SolutionRestoreManager/SolutionRestoreWorker.cs
> +                            {
The `RestoreManagerPackage` has nothing to do with restore logic. Its role is to re-route UI events to the worker. The `SolutionRestoreWorker` in its turn owns this decision. It helps keeping all conditionals in one place accessible via the same entry point.

Also I'd argue on `JTF` usage here as every query to `SolutionManager` runs under `JTF` anyway.

2017-02-07 21:51 UTC, alpaix commented
@emgarten Agree on force flag/rebuild behavior - we shouldn't skip on-build restore in this case. This scenario will be covered with another long-term proper fix.

2017-02-07 23:14 UTC, alpaix commented
🔔

2017-02-07 23:19 UTC, emgarten approved these changes
Looks perfect to me ✨

2017-02-07 23:21 UTC, jainaashish approved these changes
Looks good!

2017-02-21 23:11 UTC, alpaix commented
Abandoning the PR in favor of the full fix #1174.

2017-02-21 23:11 UTC, closed without merging