Check for MSBuild property for RestoreProjectStyle on legacy project systems
NuGet/NuGet.Client pull request #1187
Opened 2017-02-13 23:43 UTC by sbanni

@emgarten @jainaashish

2017-02-13 23:43 UTC, dnfclas commented
Hi __@sbanni__, I'm your friendly neighborhood .NET Foundation Pull Request Bot (You can call me DNFBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no Contribution License Agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, DNFBOT;

2017-02-14 06:22 UTC, emgarten requested changes
A couple minor changes, overall it looks like this would solve it

2017-02-14 06:22 UTC, emgarten commented on src/NuGet.Clients/PackageManagement.VisualStudio/EnvDTEProjectAdapter.cs
> +        private const string ProjectStylePackageReference = "PackageReference";
Use ProjectStyle.PackageReference instead

2017-02-14 06:22 UTC, emgarten commented on src/NuGet.Clients/PackageManagement.VisualStudio/EnvDTEProjectAdapter.cs
> +                    if (!string.IsNullOrWhiteSpace(restoreProjectStyle) && restoreProjectStyle.Equals(ProjectStylePackageReference, StringComparison.OrdinalIgnoreCase))
The property check looks good, but the property alone isn't enough. The project must be a VSProject4. It looks like you could combine this with the other check below to also verify that RestoreProjectStyle is not set to PackageReference.

2017-02-14 17:42 UTC, jainaashish requested changes
I don't understand the reason for this PR. We reverted this change to fix RPS perf regression but this PR will again introduce that regression. Ideally we need to come up with a solution which doesn't impact perf for normal scenarios.

2017-02-14 22:28 UTC, jainaashish commented on src/NuGet.Clients/PackageManagement.VisualStudio/EnvDTEProjectAdapter.cs
> +                            && (AsVSProject4.PackageReferences?.InstalledPackages?.Length ?? 0) == 0)
These two conditions can't be clubbed together. Justin just meant AsVSProject4 == null check even if RestoreProjectStyle is set to PackageReference.

Scenarios are like:
1. If AsVSProject4 == null then simply set _isLegacyCSProjPackageReferenceProject = false
2. Else if, RestoreProjectStyle is defined to PackageReferencen OR  AsVSProject4.PackageReferences?.InstalledPackages?.Length ?? 0) > 0 then set  _isLegacyCSProjPackageReferenceProject = true
3. Else, set _isLegacyCSProjPackageReferenceProject = false

2017-02-14 22:30 UTC, jainaashish commented on src/NuGet.Clients/PackageManagement.VisualStudio/EnvDTEProjectAdapter.cs
> +                        var restoreProjectStyle = GetMSBuildProperty(AsIVsBuildPropertyStorage, RestoreProjectStyle, null);
👍

2017-02-14 22:34 UTC, sbanni commented on src/NuGet.Clients/PackageManagement.VisualStudio/EnvDTEProjectAdapter.cs
> +                            && (AsVSProject4.PackageReferences?.InstalledPackages?.Length ?? 0) == 0)
1 is covered above: if (AsIVsHierarchy?.IsCapabilityMatch("CPS") ?? true || AsVSProject4 == null)
Do you have specific tests you would like me to run to verify that everything works correctly?

2017-02-24 19:56 UTC, jainaashish commented on src/NuGet.Clients/PackageManagement.VisualStudio/EnvDTEProjectAdapter.cs
> +        private const string ProjectStylePackageReference = "PackageReference";
remove this const `ProjectStylePackageReference `

2017-02-24 19:57 UTC, jainaashish approved these changes
Looks good 👍

2017-02-24 22:57 UTC, emgarten approved these changes

2017-03-02 01:31 UTC, emgarten commented
Replaced by @jainaashish's PR

2017-03-02 01:31 UTC, closed without merging