Avoid running duplicate/ unnecessary auto restore
NuGet/NuGet.Client pull request #1198
Opened 2017-02-22 00:22 UTC by jainaashish

This PR will delay auto restore when we're still expecting some nominations to come from project system and make sure to run a single auto restore for all the projects which will save performance as well as avoid unnecessary error/ warning messages from multiple auto restores.

Also, this will maximum delay auto restore for 10 secs, even after 10 secs we're missing some nominations then we'll continue with it and let it fail assuming there is something wrong with project system which is why they were not able to nominate. This is the fallback mechanism so that we never delay auto restore indefinitely.

Fixes https://github.com/NuGet/Home/issues/4307

@rrelyea @DoRonMotter  @alpaix @emgarten

2017-02-22 17:30 UTC, alpaix commented on src/NuGet.Clients/PackageManagement.VisualStudio/IDE/IVsSolutionManager.cs
> +        int GetExpectedProjectsNomination();
How about boolean `IsAllProjectsNominated()` instead? Actual count is not necessary and may be confusing.

2017-02-22 17:32 UTC, alpaix commented on src/NuGet.Clients/PackageManagement.VisualStudio/IDE/VSSolutionManager.cs
> +                if (_projectSystemCache.TryGetProjectRestoreInfo(cpsProject.MSBuildProjectPath, out projectRestoreInfo) &&
Noted in other places we tend to use `GetNuGetProjectSafeName` for polling the cache. What if project created and not saved?

2017-02-22 17:33 UTC, alpaix commented on src/NuGet.Clients/NuGet.SolutionRestoreManager/SolutionRestoreWorker.cs
> +                                currentExpectedNominations = _solutionManager.Value.GetExpectedProjectsNomination();
Consider caching the result once all of the projects are nominated.

2017-02-22 17:33 UTC, alpaix requested changes
Address the feedback.

2017-02-22 17:46 UTC, jainaashish commented on src/NuGet.Clients/PackageManagement.VisualStudio/IDE/IVsSolutionManager.cs
> +        int GetExpectedProjectsNomination();
hmm makes sense! earlier i was validating changes with previous run so used int.. but now it makes more sense to just use boolean.

2017-02-22 17:50 UTC, jainaashish commented on src/NuGet.Clients/NuGet.SolutionRestoreManager/SolutionRestoreWorker.cs
> +                                currentExpectedNominations = _solutionManager.Value.GetExpectedProjectsNomination();
thought so, but then there still could be cases where new projects are being created which are still missing nominations when it tries to run an auto restore which is why I didn't cache it. And also figuring out if projects are nominated or not, is a quick check so doesn't impact perf as well.

2017-02-22 18:28 UTC, jainaashish commented on src/NuGet.Clients/PackageManagement.VisualStudio/IDE/VSSolutionManager.cs
> +                if (_projectSystemCache.TryGetProjectRestoreInfo(cpsProject.MSBuildProjectPath, out projectRestoreInfo) &&
`TryGetProjectRestoreInfo` is only being used in CPSProjectReferenceProject and it always passes projectFullPath which is why I passed the same thing here to have the consistency.

2017-02-22 19:49 UTC, emgarten approved these changes

2017-04-06 23:19 UTC, mishra14 commented
@alpaix @emgarten : is this needed?

2017-06-22 23:27 UTC, alpaix commented on src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/IDE/VSSolutionManager.cs
> +            var nominatedProjects = 0;
you don't have to count all of them, just find at least one without restore info.

2017-06-22 23:39 UTC, alpaix commented on src/NuGet.Clients/NuGet.SolutionRestoreManager/SolutionRestoreWorker.cs
> +                                await Task.Delay(DelayAutoRestoreTime);
Not needed. `TryTake` above will do wait just fine.

2017-06-22 23:43 UTC, alpaix reviewed
⌚️

2017-06-28 01:18 UTC, jainaashish commented
@alpaix As per our discussion, I've updated the PR

2017-06-28 16:06 UTC, alpaix approved these changes
👏 Well done!

2017-06-28 17:37 UTC, merged