Handle nullref when the project is not saved on disk - Closes https://github.com/NuGet/Home/issues/4567
NuGet/NuGet.Client pull request #1226
Opened 2017-03-07 06:10 UTC by nkolev92

Closes NuGet/Home#4567

The root cause of our null ref is the fact that the DTE returns an empty solution path when this variable is unchecked.
We make that call right here:
https://github.com/NuGet/NuGet.Client/blob/b89bb5750c475212213e14f750604d2ecaf704ff/src/NuGet.Clients/PackageManagement.VisualStudio/IDE/VSSolutionManager.cs#L531
This however hasn't changed so we need to work around this issue on our side.

The ProjectFactory might return a null NuGetProject, we null check and throw an exception to stop the restore.

Similar to #1205

//cc
@emgarten @zhili1208 @alpaix @rohit21agrawal @mishra14 @jainaashish

2017-03-07 16:43 UTC, alpaix commented on src/NuGet.Clients/PackageManagement.VisualStudio/IDE/VSSolutionManager.cs
> +            if(nuGetProject == null)
nit: space after `if`. Format changed code block.

2017-03-07 16:45 UTC, alpaix commented on src/NuGet.Clients/PackageManagement.VisualStudio/Strings.resx
> +    <value>Cannot create NuGet project. The VS project might be invalid or the solution is not saved on disk.</value>
not sure about the abbreviation in user message. Replace with full name?

2017-03-07 16:47 UTC, alpaix commented on src/NuGet.Clients/PackageManagement.VisualStudio/IDE/VSSolutionManager.cs
> +                throw new InvalidOperationException(Strings.Error_FailureToCreateNuGetProject);
Write error to the activity log?

2017-03-07 16:51 UTC, alpaix requested changes
Not sure this change would help user understand how to fix the problem. Let's sync offline.

2017-03-09 22:55 UTC, nkolev92 commented
:bell: @alpaix

2017-03-10 18:47 UTC, alpaix commented on src/NuGet.Clients/NuGet.SolutionRestoreManager/SolutionRestoreJob.cs
> +                if (solutionDirectory == null) {
nit: new line

2017-03-10 18:49 UTC, alpaix commented on src/NuGet.Clients/PackageManagement.VisualStudio/IDE/VSSolutionManager.cs
> +            // Create the NuGet project first. If this throws or returns null we bail out and do not change the cache.
not relevant after you unrolled your changes here.

2017-03-10 18:50 UTC, alpaix approved these changes
Couple of minor notes. After that 🚢.

2017-03-10 23:47 UTC, nkolev92 commented
Can one person take a look?

@emgarten @rohit21agrawal @jainaashish @zhili1208 @mishra14

2017-03-11 03:08 UTC, emgarten approved these changes

2017-03-13 16:53 UTC, merged