Get package metadata from all enabled sources for checking license
NuGet/NuGet.Client pull request #1240
Opened 2017-03-15 22:33 UTC by zhili1208

https://github.com/NuGet/Home/issues/4768

the issue is nuget UI is fetching package metadata only from current active source during checking license.

the fix is fetching metadata from all enabled sources.

2017-03-15 22:46 UTC, jainaashish commented on src/NuGet.Clients/PackageManagement.UI/Actions/UIActionEngine.cs
> +            var localSources = new List<SourceRepository>();
you updated the variable name but didn't change the name at the usage.  Update `sources` at line 652

2017-03-15 22:46 UTC, jainaashish requested changes
Address comment

2017-03-15 23:38 UTC, jainaashish approved these changes
👍

2017-03-16 17:29 UTC, zhili1208 commented
merged to dev, waiting for 4.1 approval.https://github.com/NuGet/NuGet.Client/commit/ba680fcca0ac5178ec33273671687e35f0df9420

2017-03-17 21:56 UTC, zhili1208 commented
merged to 4.1

2017-03-17 21:56 UTC, closed without merging