Changing E2E setup to test with Insertable vsix and some test fix
NuGet/NuGet.Client pull request #1247
Opened 2017-03-18 02:40 UTC by mishra14

This fixes: https://github.com/NuGet/Home/issues/4759

1. Fixes the way we run E2E tests. This change (and some artifact dependency changes on CI), will make sure we use Insertable vsix for E2E tests.

2. This also fixes couple of test failures on dev.

//cc: @emgarten @nkolev92 @rohit21agrawal @jainaashish @alpaix

2017-03-18 02:45 UTC, nkolev92 requested changes
Take care of the dev14 cases.

2017-03-18 02:45 UTC, nkolev92 commented on scripts/e2etests/InstallNuGetVSIX.ps1
> +$success = InstallVSIX $VSIXPath $VSVersion $VSIXInstallerWaitTimeInSecs
The same script is used for both DEV15 and DEV14 E2E tests

2017-03-18 02:45 UTC, nkolev92 commented on scripts/e2etests/InstallNuGetVSIX.ps1
> +ClearDev15MEFCache
Same here

2017-03-20 02:16 UTC, emgarten approved these changes

2017-03-20 15:37 UTC, nkolev92 approved these changes

2017-03-20 18:49 UTC, merged