Holder PR for migration merge
NuGet/NuGet.Client pull request #1268
Opened 2017-03-27 22:46 UTC by mishra14

Merging migration into dev today. 

This PR is to allow people to take a look before we merge. If needed please raise a concern.

Changes - 
1. Migrated most of the projects to .Net Core. The only projects left out are WPF related.
2. Merged NuGet.Core.Sln and NuGet.Client.Sln into NuGet.Sln.
3. Created build.proj to perform all of our build and test related tasks.
4. Changed our ps1 scripts to invoke build.proj.
5. Restructured props and targets to reflect the new project structures.

//cc: @alpaix @rohit21agrawal @emgarten @nkolev92 @jainaashish @zhili1208 @joelverhagen @rrelyea

2017-03-27 22:52 UTC, nkolev92 commented on .nuget/packages.config
> +  <package id="Microsoft.VSSDK.BuildTools" version="15.0.26201" targetFramework="net46" />
This fixes:
https://github.com/NuGet/Home/issues/4727

2017-03-27 22:54 UTC, nkolev92 commented on .nuget/packages.config
> +</packages>
nit: 
new line

2017-03-27 22:54 UTC, mishra14 commented on .nuget/packages.config
> +</packages>
up for grabs!

2017-03-27 23:08 UTC, mishra14 commented
Fixes: https://github.com/NuGet/Home/issues/3616

2017-03-28 16:31 UTC, nkolev92 commented
The VSIX that the migrate branch currently produces is corrupt.

2017-03-28 16:31 UTC, nkolev92 requested changes
Make sure the VSIX is packed correctly.

2017-03-28 18:39 UTC, nkolev92 approved these changes

2017-03-29 04:28 UTC, emgarten approved these changes

2017-03-30 01:15 UTC, merged