Fixing assembly and file versions for net core projects
NuGet/NuGet.Client pull request #1280
Opened 2017-04-01 00:48 UTC by mishra14

Currently net core projects are using auto generated build numbers. this PR fixes that.

2017-04-01 00:53 UTC, emgarten commented on build/common.props
> +    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
Move this to common.project.props with a condition.

2017-04-01 00:56 UTC, emgarten requested changes
Move GenerateAssemblyInfo

2017-04-01 01:02 UTC, emgarten approved these changes
Good fix 🚀

2017-04-03 16:04 UTC, alpaix requested changes
Address the feedback.

2017-04-03 16:04 UTC, alpaix commented on build/common.project.props
> +    <AssemblyVersion>$(SemanticVersion).$(PreReleaseVersion)</AssemblyVersion>
Why do you need to set this explicitly? Having `$(Version)` should be enough to make msbuild set correct assembly version.

2017-04-03 16:06 UTC, nkolev92 commented on build/common.project.props
> +  <PropertyGroup Condition=" '$(IsNetCoreProject)' == 'true' ">
Merge this propertygroup with the one below it?

2017-04-03 18:01 UTC, mishra14 commented on build/common.project.props
> +    <AssemblyVersion>$(SemanticVersion).$(PreReleaseVersion)</AssemblyVersion>
`$(version)` alone does not work. We already had that.

2017-04-03 18:34 UTC, mishra14 commented
🔔

2017-04-03 18:41 UTC, nkolev92 approved these changes

2017-04-03 18:41 UTC, nkolev92 commented on build/common.project.props
> +
nit: no need for the empty line.

2017-04-03 19:18 UTC, mishra14 commented on build/common.project.props
> +
That keeps the separate logical properties separate. I think this is fine.

2017-04-03 20:12 UTC, alpaix commented on build/common.project.props
> +    <AssemblyVersion>$(SemanticVersion).$(PreReleaseVersion)</AssemblyVersion>
I created a simple netstandard library
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard1.3;net45</TargetFrameworks>
    <Version>2.3.4-beta1-1256</Version>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
  </PropertyGroup>

</Project>
```
And it did set version correctly. What's wrong with our projects?

2017-04-03 23:09 UTC, alpaix approved these changes

2017-04-04 00:40 UTC, merged