Improve auto restore performance and also NuGet sln load time
NuGet/NuGet.Client pull request #1285
Opened 2017-04-05 00:10 UTC by jainaashish

This PR improves auto restore performance by almost ~50%. Previously it was taking ~80 secs to complete auto restore on NuGet sln (without cleaning cache) now it takes ~45 secs for the same sln.

It primarily does 2 things:
1. Avoid blocking threadpool thread when it tries to move to UI thread so `IsSolutionFullyLoaded` API is being converted to `async` so it will improve overall auto restore performance and will be applicable across solutions.
2. Avoid downgrade warnings which was specific to NuGet solution.

There are still couple of areas to further improve it such as `ExecuteAndCommitAsync` API in `RestoreRunner` ideally this method should be executed as async instead of running under `Task.Run`. Will continue to improve it further.

@rrelyea @DoRonMotter

2017-04-05 01:12 UTC, emgarten approved these changes
Use the async suffix on the method name to match other methods. 

Then :shipit:

50%! 👏

2017-04-05 01:12 UTC, emgarten commented on src/NuGet.Clients/PackageManagement.VisualStudio/IDE/IVsSolutionManager.cs
> +        Task<bool> IsSolutionFullyLoaded();
``IsSolutionFullyLoadedAsync``

2017-04-05 17:19 UTC, alpaix commented on src/NuGet.Clients/PackageManagement.VisualStudio/IDE/VSSolutionManager.cs
> +            await NuGetUIThreadHelper.JoinableTaskFactory.SwitchToMainThreadAsync();
This may have unexpected side effect when caller switches to main thread from a background thread.

2017-04-05 17:22 UTC, alpaix commented on src/NuGet.Clients/VsConsole/PowerShellHost/PowerShellHost.cs
> +                if (!await _solutionManager.IsSolutionFullyLoaded())
Here, `PowerShellHost` will switch to the main thread. This may cause a deadlock.

2017-04-05 17:23 UTC, alpaix requested changes
Requesting changes.

2017-04-05 18:45 UTC, alpaix approved these changes
We had offline discussion and clarified my concerns.

2017-04-05 19:49 UTC, merged

2017-05-25 01:40 UTC, davkean commented
👍