Implemented build restore without blocking UI thread
NuGet/NuGet.Client pull request #1294
Opened 2017-04-06 00:23 UTC by jainaashish

This PR avoid blocking UI thread to block build while running onbuild restore. So instead of using restore on `onBuildEvent` from dte, it now runs it with `UpdateSolution_QueryDelayFirstUpdateAction` and delay build until restore is in progress.

So, now VS won't be freezed or unresponsive during build restore and improve user experience as well as performance.

Fixes https://github.com/NuGet/Home/issues/4986

@rrelyea @DoRonMotter

2017-04-06 00:31 UTC, emgarten approved these changes
Minor spelling issue. Looks great overall. I went through this with Ashish offline.

2017-04-06 00:31 UTC, emgarten commented on src/NuGet.Clients/NuGet.SolutionRestoreManager/RestoreManagerPackage.cs
> +                else if (!_issRestoreRunning)
``_is``

2017-04-20 21:20 UTC, alpaix requested changes
This change implements non-trivial state machine. My major concern is validate all edge cases are covered. For instance, one issue I found when build is cancelled during restore running. In this case the state machine would be broken.

2017-04-20 21:20 UTC, alpaix commented on src/NuGet.Clients/NuGet.SolutionRestoreManager/RestoreManagerPackage.cs
> +                    pfDelay = 1;
This introduces unnecessary delay when `OnBuildRestore` no-ops. For instance, when performing Clean only, or `ShouldRestoreOnBuild` returns `false`.

2017-04-20 21:20 UTC, alpaix commented on src/NuGet.Clients/NuGet.SolutionRestoreManager/RestoreManagerPackage.cs
> +                _solutionBuildManager3.AdviseUpdateSolutionEvents3(updateSolutionEvent, out _updateSolutionEventsCookie3);
Validate the return code.

2017-04-20 21:20 UTC, alpaix commented on src/NuGet.Clients/NuGet.SolutionRestoreManager/RestoreManagerPackage.cs
> +            public int OnBeforeActiveSolutionCfgChange(IVsCfg pOldActiveSlnCfg, IVsCfg pNewActiveSlnCfg)
Why is this implementation needed?

2017-04-24 16:42 UTC, alpaix commented
🔔 @alpaix @emgarten Addressed the feedback, added tests.

2017-04-24 18:02 UTC, alpaix approved these changes
LGTM

2017-04-24 18:54 UTC, emgarten commented on test/TestUtilities/Test.Utility/Test.Utility.csproj
> +    <Compile Remove="Threading\*.cs" />
👍

2017-04-24 19:01 UTC, emgarten approved these changes
LGTM

2017-04-24 20:57 UTC, merged