Change version number for .NET Core projects
NuGet/NuGet.Client pull request #1306
Opened 2017-04-09 09:36 UTC by nkolev92

We hit a known when we tried to insert into dotnet SDK here: https://github.com/dotnet/sdk/pull/1101
The underlying bug is this one https://github.com/dotnet/cli/issues/4214, and until that is fixed we will have to do some gymnastics when inserting in the CLI/SDK. 

This fix aims to avoid us running into the problems specified in the above PR every time. We'd only hit it when changing the NuGet version.
The problem stems from the fact that the AssemblyVersion now contains the build number as well, while before all NuGet.Core projects had the build number as 0 every time.  

This has some side-effects as some client projects are now .NET as well and the versions for those will be changed too.

2017-04-09 09:38 UTC, emgarten approved these changes

2017-04-09 16:15 UTC, rohit21agrawal approved these changes

2017-04-10 16:06 UTC, alpaix commented on build/common.project.props
> +    <AssemblyVersion>$(SemanticVersion).0</AssemblyVersion>
Please please please add a comment above!

2017-04-10 16:07 UTC, alpaix requested changes
Apologize for blocking. Comments are important!

2017-04-10 19:32 UTC, rohit21agrawal commented
@alpaix fixed on behalf of @nkolev92

2017-04-10 19:35 UTC, alpaix approved these changes

2017-04-10 19:36 UTC, merged