ilmerge nuget.build.tasks.pack
NuGet/NuGet.Client pull request #1309
Opened 2017-04-11 20:02 UTC by rohit21agrawal

Fixes: https://github.com/NuGet/Home/issues/5011

CC: @emgarten @alpaix

2017-04-11 20:05 UTC, alpaix commented on src/NuGet.Core/NuGet.Build.Tasks.Pack.Library/NuGet.Build.Tasks.Pack.Library.csproj
> +    <PackageId>NuGet.Build.Tasks.Pack</PackageId>
Consider renaming the project to follow the package ID.

2017-04-11 20:13 UTC, alpaix commented
What is the license for the new library?

2017-04-11 20:15 UTC, alpaix commented
Does it merge symbols? What is the final size of the result assembly? Does it merge NuGet* assemblies only or all of the dependencies?

2017-04-11 20:21 UTC, alpaix commented on build/common.project.props
> +    <ILRepackExePath>$(SolutionPackagesFolder)ILRepack.2.0.13\tools\ILRepack.exe</ILRepackExePath>
Package contains the props file defining the tool location. Also would it work if installed directly in target project?

2017-04-11 20:22 UTC, alpaix requested changes
Waiting for response.

2017-04-11 20:55 UTC, emgarten commented on src/NuGet.Core/NuGet.Build.Tasks.Pack.Library/NuGet.Build.Tasks.Pack.Library.csproj
> +    <PackageId>NuGet.Build.Tasks.Pack</PackageId>
@rohit21agrawal is the circular dependency problem fixed now that the SDK no longer depends on pack?

2017-04-11 20:57 UTC, emgarten commented on src/NuGet.Core/NuGet.Build.Tasks.Pack.Library/NuGet.Build.Tasks.Pack.Library.csproj
> +      <IlmergeCommand>$(ILRepackExePath) $(PathToBuiltNuGetPack) /lib:$(OutputPath)$(RuntimeIdentifier)\publish @(BuildArtifacts, ' ') /out:$(OutputPath)NuGet.Build.Tasks.Pack.dll /internalize</Ilmer
``/parallel`` would help here

2017-04-11 20:59 UTC, emgarten commented on src/NuGet.Core/NuGet.Build.Tasks.Pack.Library/NuGet.Build.Tasks.Pack.Library.csproj
> +      <IlmergeCommand>$(ILRepackExePath) $(PathToBuiltNuGetPack) /lib:$(OutputPath)$(RuntimeIdentifier)\publish @(BuildArtifacts, ' ') /out:$(OutputPath)NuGet.Build.Tasks.Pack.dll /internalize</Ilmer
Is there a new .pdb created from this? If so it should get copied to the symbols folder with the nuget.exe merged one

2017-04-11 21:06 UTC, rohit21agrawal commented on src/NuGet.Core/NuGet.Build.Tasks.Pack.Library/NuGet.Build.Tasks.Pack.Library.csproj
> +    <PackageId>NuGet.Build.Tasks.Pack</PackageId>
yes.

2017-04-11 21:07 UTC, rohit21agrawal commented on build/common.project.props
> +    <ILRepackExePath>$(SolutionPackagesFolder)ILRepack.2.0.13\tools\ILRepack.exe</ILRepackExePath>
@alpaix for some reason couldn't get it to work as a package reference.

2017-04-11 21:07 UTC, rohit21agrawal commented on src/NuGet.Core/NuGet.Build.Tasks.Pack.Library/NuGet.Build.Tasks.Pack.Library.csproj
> +      <IlmergeCommand>$(ILRepackExePath) $(PathToBuiltNuGetPack) /lib:$(OutputPath)$(RuntimeIdentifier)\publish @(BuildArtifacts, ' ') /out:$(OutputPath)NuGet.Build.Tasks.Pack.dll /internalize</Ilmer
we haven't been shipping symbols for this, as we don't create a symbols package.

2017-04-11 21:08 UTC, rohit21agrawal commented
@alpaix the software is a part of Free Software Foundation and there is no license i could find on the project site.

the resulting dll for netstandard is 1.5 mb and for net45 is 2mb.

2017-04-11 21:14 UTC, emgarten commented on src/NuGet.Core/NuGet.Build.Tasks.Pack.Library/NuGet.Build.Tasks.Pack.Library.csproj
> +    <RuntimeIdentifier>win10-x64</RuntimeIdentifier>
Make sure this builds on Linux

2017-04-11 21:14 UTC, emgarten approved these changes

2017-04-11 21:21 UTC, alpaix commented
@rohit21agrawal The license is here https://github.com/gluck/il-repack/blob/master/LICENSE.
It's licensed under the Apache License 2.0.

2017-04-11 21:23 UTC, alpaix commented
@rohit21agrawal Are you going to pack both assemblies, netstandard and net45, into the final shipping package?

2017-04-11 21:30 UTC, rohit21agrawal commented
@alpaix yes, both assemblies are going to be packed. also i have submitted request for approval of the ilrepack nuget package.

2017-04-12 02:08 UTC, alpaix approved these changes

2017-04-12 17:32 UTC, rohit21agrawal commented
Closing in favour of https://github.com/NuGet/NuGet.Client/pull/1310

2017-04-12 17:32 UTC, closed without merging