Keep Project.json in sync with TPMinV for UWP Projects
NuGet/NuGet.Client pull request #1341
Opened 2017-04-27 23:01 UTC by shishirx34

Fixes https://github.com/NuGet/Home/issues/4932. 

Replaces the UAP framework in project.json with the TPMinV from csproj for UWP projects. 

Added relevant unit tests. Investigating into adding end to end tests if possible.

2017-04-28 16:17 UTC, alpaix requested changes

2017-04-28 16:17 UTC, alpaix commented on src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/ProjectSystems/ProjectJsonBuildIntegratedProjectSystem.cs
> +            if (InternalMetadata.TryGetValue(NuGetProjectMetadataKeys.TargetFramework, out object targetFramework))
This won't compile for VS14.

2017-04-28 16:17 UTC, alpaix commented on src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/ProjectSystems/ProjectJsonBuildIntegratedProjectSystem.cs
> +                    if (platfromMinVersion != null)
`!string.IsNullOrEmpty()`?
- addressed.

2017-04-28 16:17 UTC, alpaix commented on src/NuGet.Core/NuGet.PackageManagement/Projects/ProjectJsonBuildIntegratedNuGetProject.cs
> +                && IsUAPFramework(frameworks.First())
I'd rather implement this method to fit generic scenario by simply comparing json framework against the metadata one.

2017-04-28 16:17 UTC, alpaix commented on src/NuGet.Core/NuGet.PackageManagement/Utility/JsonConfigUtility.cs
> +                    string.Equals(item.Framework, framework.Framework, StringComparison.OrdinalIgnoreCase)
`NuGetFramework` employs its own comparer, so `list.Any(framework)` should just work.

2017-04-28 16:17 UTC, alpaix commented on test/NuGet.Core.Tests/NuGet.PackageManagement.Test/ProjectManagement/JsonConfigUtilityTests.cs
> +            // Act
nit: `Act` normally corresponds to a single line calling a method the test is written for. In this case it's line 121.

2017-04-28 16:17 UTC, alpaix commented on src/NuGet.Core/NuGet.PackageManagement/Utility/JsonConfigUtility.cs
> +            if (json.TryGetValue("frameworks", out node))
Add a constant for "frameworks"

2017-04-28 16:17 UTC, alpaix commented on src/NuGet.Clients/NuGet.VisualStudio.Common/EnvDTEProjectInfoUtility.cs
> +        public const string FullPath = "FullPath";
Don't have to be public, right?

2017-04-28 21:41 UTC, shishirx34 commented on src/NuGet.Clients/NuGet.VisualStudio.Common/EnvDTEProjectInfoUtility.cs
> +        public const string FullPath = "FullPath";
This doesn't need to be but TargetPlatformMinVersion does need to be to reuse above to get TPMin version from envDTEProject. Ideally I would have liked these values to be consts defined in a separate class or something, but I am avoiding to make any unneeded refactors for now.

2017-04-28 21:50 UTC, shishirx34 commented on src/NuGet.Core/NuGet.PackageManagement/Utility/JsonConfigUtility.cs
> +                    string.Equals(item.Framework, framework.Framework, StringComparison.OrdinalIgnoreCase)
Oh cool, I wasn't aware it had a comparer

2017-04-28 22:18 UTC, shishirx34 commented on src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/ProjectSystems/ProjectJsonBuildIntegratedProjectSystem.cs
> +            if (InternalMetadata.TryGetValue(NuGetProjectMetadataKeys.TargetFramework, out object targetFramework))
I ran the build script and saw no errors. How else can I compile for VS14?

2017-04-28 22:40 UTC, shishirx34 commented on src/NuGet.Core/NuGet.PackageManagement/Projects/ProjectJsonBuildIntegratedNuGetProject.cs
> +                && IsUAPFramework(frameworks.First())
Had an offline chat with Alex, decided to add a check on the `newTargetFramework` for UAP and get input from PM on the need for check for json framework.

2017-05-01 21:06 UTC, alpaix approved these changes

2017-05-01 22:51 UTC, merged