Changing default behavior in collector logger to not log to the inner logger
NuGet/NuGet.Client pull request #1381
Opened 2017-05-15 20:09 UTC by mishra14

This should only affect restore logs since no other code path uses collector logger.

I have added a bool `LogToInnerLogger` into `IRestoreLogMessage` to ensure that the collector logger selectively passes logs to the inner logger.

2017-05-15 23:23 UTC, emgarten commented on src/NuGet.Core/NuGet.Common/Errors/IRestoreLogMessage.cs
> +        bool LogToInnerLogger { get; set; }
How about AlwaysDisplayToUser?  LogToInnerLogger makes sense for the implementation, but it would be more clear if this was tied to the behavior.

2017-05-15 23:29 UTC, mishra14 commented on src/NuGet.Core/NuGet.Common/Errors/IRestoreLogMessage.cs
> +        bool LogToInnerLogger { get; set; }
how about `DisplayLog` or 'DisplayToUser'?
Always seems redundant.

2017-05-15 23:30 UTC, emgarten commented on src/NuGet.Core/NuGet.Common/Errors/IRestoreLogMessage.cs
> +        bool LogToInnerLogger { get; set; }
I like DisplayToUser

2017-05-16 00:47 UTC, emgarten requested changes

2017-05-16 00:47 UTC, emgarten commented on test/TestUtilities/Test.Utility/DebuggerUtils.cs
> +    public class DebuggerUtils
static

I don't see this used anywhere though? should it go away?

2017-05-16 02:06 UTC, mishra14 commented on test/TestUtilities/Test.Utility/DebuggerUtils.cs
> +    public class DebuggerUtils
its a helper for when you need to attach a debugger in a test. Its quite handy.

2017-05-16 02:27 UTC, emgarten commented on test/TestUtilities/Test.Utility/DebuggerUtils.cs
> +    public class DebuggerUtils
It looks like it is for core only. How about adding ifdefs for the framework and doing a debugger.launch for desktop?

the class should still be static also.

2017-05-16 17:42 UTC, mishra14 commented on test/TestUtilities/Test.Utility/DebuggerUtils.cs
> +    public class DebuggerUtils
Agree with static. But this can be used for core or desktop.

2017-05-16 22:08 UTC, emgarten approved these changes
🚀

2017-05-16 22:08 UTC, emgarten commented on test/TestUtilities/Test.Utility/DebuggerUtils.cs
> +#if IS_CORECLR
💯

2017-05-18 01:19 UTC, emgarten commented on test/NuGet.Clients.Tests/NuGet.CommandLine.Test/NuGetRestoreCommandTest.cs
> +            DebuggerUtils.WaitForDebugger();
this will hang tests

2017-05-18 01:20 UTC, emgarten approved these changes

2017-05-19 18:35 UTC, merged