Nominate API and TFM & TPMinV sync for Project.Json
NuGet/NuGet.Client pull request #1395
Opened 2017-05-22 18:05 UTC by shishirx34

This PR contains two major changes:

- A new Nominate API for doing a solution restore without the `ProjectRestoreInfo`. This will be called by UWP as appropriate on change of the `TPMinV`
- Update's ProjectJson project system to read the TPMinV from csproj on
  - Any Package install which then updates `project.json`
  - Any Package uninstall/update which then updates `project.json`
  - On Solution restore, the internal value of TFM is updated with the correct value of the version from csproj, so that the solution is correctly restored on modified `Targeted Minimum Platform Version`.

2017-05-22 20:01 UTC, emgarten commented
This would need to be done in the MSBuild restore task also otherwise the TFM will be different from the command line.

2017-05-22 20:34 UTC, alpaix requested changes

2017-05-22 20:34 UTC, alpaix commented on src/NuGet.Core/NuGet.PackageManagement/Projects/ProjectJsonBuildIntegratedNuGetProject.cs
> +            if (InternalMetadata.TryGetValue(NuGetProjectMetadataKeys.TargetFramework, out object newTargetFrameworkObject))
To avoid duplicated code, consider adding a helper method like `TryGetInternalTargetFramework`.

2017-05-22 20:34 UTC, alpaix commented on src/NuGet.Core/NuGet.PackageManagement/Projects/ProjectJsonBuildIntegratedNuGetProject.cs
> +                    var replaceTargetFramework = new TargetFrameworkInformation();
These two line should better be moved under the next if-clause.

2017-05-22 20:34 UTC, alpaix commented on src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/ProjectSystems/ProjectJsonBuildIntegratedProjectSystem.cs
> +        protected override void UpdateInternalTargetFramework()
Make it async.

2017-05-22 23:53 UTC, jainaashish commented on src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/ProjectSystems/ProjectJsonBuildIntegratedProjectSystem.cs
> +            NuGetUIThreadHelper.JoinableTaskFactory.Run(async () =>
And when you make it async, you dont need `JTF.Run` since you're executing whole method on UI thread.

2017-05-22 23:57 UTC, jainaashish commented on src/NuGet.Clients/NuGet.SolutionRestoreManager/VsSolutionRestoreService.cs
> +            if (string.IsNullOrEmpty(projectUniqueName))
instead you can use `Assumes.NotNullOrEmpty`

2017-05-23 00:04 UTC, jainaashish commented on src/NuGet.Clients/NuGet.SolutionRestoreManager/VsSolutionRestoreService.cs
> +        public Task<bool> NominateProjectAsync(string projectUniqueName, CancellationToken token)
why do you even need this `projectUniqueName`?

2017-05-23 00:06 UTC, shishirx34 commented on src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/ProjectSystems/ProjectJsonBuildIntegratedProjectSystem.cs
> +            NuGetUIThreadHelper.JoinableTaskFactory.Run(async () =>
Yes. Done.

2017-05-23 00:08 UTC, shishirx34 commented on src/NuGet.Clients/NuGet.SolutionRestoreManager/VsSolutionRestoreService.cs
> +        public Task<bool> NominateProjectAsync(string projectUniqueName, CancellationToken token)
Its not really needed. We decided to keep it so that in when/if we add project restore only option it can be extended for it.

2017-05-23 00:43 UTC, shishirx34 commented on src/NuGet.Clients/NuGet.SolutionRestoreManager/VsSolutionRestoreService.cs
> +            if (string.IsNullOrEmpty(projectUniqueName))
I looked it up. It seems that we are not really using it anywhere else, any reason particularly? Are we going to transition to using it going forward? Just to keep consistency I would keep it the way it is, but if you feel that `Assumes` is the way to go, I can change it. Thoughts?

2017-05-23 00:53 UTC, jainaashish commented on src/NuGet.Clients/NuGet.SolutionRestoreManager/VsSolutionRestoreService.cs
> +            if (string.IsNullOrEmpty(projectUniqueName))
We recently started using it. Already use it for Argument null check, it's more convenient and simple without worrying about right error message as well.

2017-05-23 01:00 UTC, shishirx34 commented on src/NuGet.Clients/NuGet.SolutionRestoreManager/VsSolutionRestoreService.cs
> +            if (string.IsNullOrEmpty(projectUniqueName))
Sounds good. Will do.

2017-05-23 01:11 UTC, alpaix approved these changes
LGTM. Couple of minor notes.

2017-05-23 01:11 UTC, alpaix commented on src/NuGet.Core/NuGet.PackageManagement/Projects/ProjectJsonBuildIntegratedNuGetProject.cs
> +        protected virtual Task UpdateInternalTargetFramework()
rename to `UpdateInternalTargetFrameworkAsync`

2017-05-23 01:11 UTC, alpaix commented on src/NuGet.Core/NuGet.PackageManagement/Projects/ProjectJsonBuildIntegratedNuGetProject.cs
> +        private async Task UpdateFramework(JObject json)
`UpdateFrameworkAsync`

2017-05-23 16:20 UTC, jainaashish approved these changes
Looks good, please add some tests as well for this scenario.

2017-05-23 20:50 UTC, shishirx34 commented
I will merge these changes in order to unblock the build for testing, and follow up with the MSBuild Restore task in a separate PR.

2017-05-23 20:50 UTC, merged