Updating MSBuildLogger to take in ILogMessages
NuGet/NuGet.Client pull request #1398
Opened 2017-05-23 21:58 UTC by mishra14

2017-05-23 23:24 UTC, emgarten requested changes
Can LogErrorSummary be removed also as part of this?

2017-05-23 23:24 UTC, emgarten commented on src/NuGet.Core/NuGet.Build.Tasks/Common/MSBuildLogger.cs
> +// Copyright (c) .NET Foundation. All rights reserved.
Move copyright to the top (I think VS causes this problem)

2017-05-23 23:24 UTC, emgarten commented on src/NuGet.Core/NuGet.Build.Tasks/Common/MSBuildLogger.cs
> +            var logMessage = message as IRestoreLogMessage;
Call ``DisplayMessage`` to verify that the message should be shown, this looks like it would log everything.

2017-05-23 23:24 UTC, emgarten commented on src/NuGet.Core/NuGet.Build.Tasks/Common/MSBuildLogger.cs
> +                logWithDetails(string.Empty,
Add a comment saying that the subcategory is not used in nuget

2017-05-23 23:24 UTC, emgarten commented on src/NuGet.Core/NuGet.Build.Tasks/Common/MSBuildLogger.cs
> +                    LogError(logMessage, _taskLogging.LogError, _taskLogging.LogError);
Does this make warnings show as errors? Is there a LogWarning method?

2017-05-23 23:24 UTC, emgarten commented on src/NuGet.Clients/NuGet.CommandLine/Commands/RestoreCommand.cs
> -                    restoreContext.DisplayAllLogs = false;
👍

2017-05-24 00:58 UTC, mishra14 commented
🔔

2017-05-24 04:00 UTC, emgarten approved these changes
🚀

2017-05-24 18:06 UTC, merged