NET Core 2.0: Update description for autoreferenced Packages
NuGet/NuGet.Client pull request #1399
Opened 2017-05-23 23:54 UTC by shishirx34

Fixes https://github.com/NuGet/Home/issues/4964

The new description looks like:

![image](https://cloud.githubusercontent.com/assets/1646506/26381140/684e1480-3fd7-11e7-9be5-279281a12394.png)

2017-05-23 23:55 UTC, emgarten requested changes

2017-05-23 23:55 UTC, emgarten commented on src/NuGet.Clients/NuGet.PackageManagement.UI/Models/DetailControlModel.cs
> +                var autoReferencedMessage = "This package is automatically referenced by the SDK and should not be updated independently. To update the package, update the SDK to which it belongs. Mo
This should be a resource string so that it can be localized.

2017-05-24 00:21 UTC, anangaur commented
Looks so texty :( I need to refine the language to make it short.

2017-05-24 00:51 UTC, anangaur approved these changes
Looks good to me.

2017-05-24 00:53 UTC, shishirx34 commented on src/NuGet.Clients/NuGet.PackageManagement.UI/Models/DetailControlModel.cs
> +                OnPropertyChanged(nameof(OptionsBlockedMessage));
Wonder if these other property changed events need to be raised here. Mimicked the behavior from above to get feedback.

2017-05-24 03:58 UTC, emgarten approved these changes

2017-05-24 16:28 UTC, jainaashish approved these changes

2017-05-24 18:13 UTC, alpaix commented on src/NuGet.Clients/NuGet.PackageManagement.UI/Models/DetailControlModel.cs
> +                OptionsBlockedUrlText = "Learn more";
the text should be localized

2017-05-24 18:19 UTC, shishirx34 commented on src/NuGet.Clients/NuGet.PackageManagement.UI/Models/DetailControlModel.cs
> +                OptionsBlockedUrlText = "Learn more";
I assumed "Learn more" need not be localized. Updated.

2017-05-24 18:27 UTC, alpaix approved these changes

2017-05-30 17:07 UTC, merged

2017-12-17 16:37 UTC, laultman commented
From a everyday user: Lots of discussion that doesn't help me actually fix my issue. I can very quickly see that I need to upgrade something. I look in my Program Files and see that I have the latest SDK for .NET Core. installed. In fact SDK 2.0.0 is NOT installed. I have 2.1.2. It still will not upgrade in my solution. Why don't you address that?