Fix vsix installation scripts
NuGet/NuGet.Client pull request #1401
Opened 2017-05-24 18:33 UTC by nkolev92

The latest prerel VS builds now allow us to downgrade to the VS baked-in VSIXs. 
The new option is /d:VsixID

We don't know the error codes when we try to downgrade the vsix. 

@rohit21agrawal Can you check what happens if we try to downgrade when we only have the baked-in VSIX?

2017-05-24 18:43 UTC, emgarten approved these changes

2017-05-25 07:20 UTC, mishra14 requested changes

2017-05-25 07:20 UTC, mishra14 commented on scripts/e2etests/VSUtils.ps1
> +        if($p.ExitCode -eq 1002)
Have you encountered this exception while downgrading?
I had added this check in the `UnInstallVSIX `function before we started building v3 vsix and then it was possible to be not have the vsix installed. I am not sure if you can get this exception while downgrading.

2017-05-25 15:46 UTC, nkolev92 commented on scripts/e2etests/VSUtils.ps1
> +        if($p.ExitCode -eq 1002)
Yup, I wasn't sure about that, so that's why I already tagged @rohit21agrawal in the original  PR message to validate it.

2017-06-02 22:08 UTC, mishra14 approved these changes
small change and then :shipit:

2017-06-02 22:08 UTC, mishra14 commented on scripts/e2etests/InstallNuGetVSIX.ps1
> +    $success = DowngradeVSIX $NuGetVSIXID $VSVersion $VSIXInstallerWaitTimeInSecs
indent and check for success

2017-06-02 22:20 UTC, merged