Fail overall restoration when a project is invalid
NuGet/NuGet.Client pull request #1405
Opened 2017-05-24 20:18 UTC by rainersigwald

Fixes NuGet/Home#5284 by changing the default setting for
`$(RestoreContinueOnError)` from `WarnAndContinue` (treat errors as
warnings that do not fail this task nor the overall build) to
`ErrorAndContinue` (continue the build, but mark it as failed if there
are any errors here).

2017-05-24 20:18 UTC, dnfclas commented
@rainersigwald,
Thanks for having already signed the Contribution License Agreement. Your agreement was validated by .NET Foundation. We will now review your pull request.
_Thanks,
.NET Foundation Pull Request Bot_

2017-05-25 23:53 UTC, emgarten commented
This will cause other problems, the warn and continue behavior is currently by design.

Restore needs to walk every project in the solution, however not all projects support ``CustomAfterMicrosoftCommonTargets`` such as C++ projects. To avoid failing and not restoring any projects NuGet skips unreadable projects and restores what can.

Discovering that a project is completely invalid is expected to be found at build time, restore is not intended to be project validator here, that leads to many duplicate errors between restore and build.

Is there a way that Restore can if a child project contains the expected target or if it supports ``CustomAfterMicrosoftCommonTargets`` before trying to call it? That is the real problem here.

2017-05-25 23:57 UTC, emgarten requested changes
This will break C# projects that depend on C++ projects.

2017-05-30 17:42 UTC, rainersigwald commented
Closing in favor of discussion on NuGet/Home#5284.

2017-05-30 17:42 UTC, closed without merging