Add profiles 44 & 151 to the list of Xamarin supported profiles
NuGet/NuGet.Client pull request #1457
Opened 2017-06-05 20:40 UTC by DanRigby

Fixes https://github.com/NuGet/Home/issues/5341

This PR adds PCL Profiles 44 & 151 to the list of Xamarin supported profiles and adds unit tests to cover them.

These profiles have been supported by Xamarin projects since early 2016 but were missing from NuGet's compatibility list.

2017-06-05 20:40 UTC, dnfclas commented
@DanRigby,
Thanks for having already signed the Contribution License Agreement. Your agreement was validated by .NET Foundation. We will now review your pull request.
_Thanks,
.NET Foundation Pull Request Bot_

2017-06-12 17:55 UTC, emgarten requested changes
Minor comments on tests. Overall this seems fine if 44 and 151 are supported by Xamarin now.

2017-06-12 17:55 UTC, emgarten commented on test/NuGet.Core.Tests/NuGet.Frameworks.Test/CompatibilityPCLTests.cs
> +        [InlineData("xamarinmac20", "portable-net451+netcore451")]
Would you add tests for net451+win81  also? It should be the same as net451+netcore451.

2017-06-12 18:39 UTC, emgarten approved these changes
LGTM

2017-06-12 18:40 UTC, DanRigby commented
Updated:
- Used the preferred win* TFM naming
- Added profile 151 tests
- Labeled the profile versions of the tests with comments as done elsewhere in the file

2017-06-12 18:44 UTC, emgarten commented
@mhutch @mrward  would you take a look also and confirm that these are the right compatibility mappings?

2017-06-12 19:08 UTC, mhutch commented
Looks good to me!

2017-06-12 19:19 UTC, mrward commented
Looks good to me.

2017-06-12 19:45 UTC, merged

2017-06-12 19:45 UTC, emgarten commented
Merged, thanks for the PR!