Dev bhavyau accessibilityissues
NuGet/NuGet.Client pull request #1474
Opened 2017-06-07 23:12 UTC by bhavyaus

Fix for Bug 395738: Inspect: Control type is inappropriate for tab item

The "Browse", "Installed", "Update" and "Consolidate" tabs (Which are actually buttons) in the Nuget Package Manager currently have default "button" as LocalizedControlType and the narrator reads them as "button" and not "tabitem". 
Created automation peer to explicitly set the control type to tabitem. Also added ISelectionItemProvider to the automation peer to enable the property IsSelectionItemPatternAvailable.

2017-06-07 23:12 UTC, dnfclas commented
@__bhavyaus__,
Thanks for your contribution.
To ensure that the project team has proper rights to use your work, please complete the Contribution License Agreement at https://cla2.dotnetfoundation.org.

It will cover your contributions to all .NET Foundation-managed open source projects.
_Thanks,
.NET Foundation Pull Request Bot_

2017-06-07 23:15 UTC, dnfclas commented
__@bhavyaus__, thanks for signing the contribution license agreement. We will now validate the agreement and then the pull request.
<br />_Thanks, .NET Foundation Pull Request Bot_

2017-06-08 16:22 UTC, alpaix requested changes
Document new classes, explain their purpose.
Also place them in new `Controls` folder.

2017-06-08 16:22 UTC, alpaix commented on src/NuGet.Clients/NuGet.PackageManagement.UI/Automation/TabItemButtonAutomationPeer.cs
> +namespace NuGet.PackageManagement.UI.Automation
remove `.Automation` it pollutes using

2017-06-08 16:22 UTC, alpaix commented on src/NuGet.Clients/NuGet.PackageManagement.UI/Automation/TabItemButtonAutomationPeer.cs
> +    public class TabItemButtonAutomationPeer : FrameworkElementAutomationPeer, ISelectionItemProvider
`internal`

2017-06-08 16:22 UTC, alpaix commented on src/NuGet.Clients/NuGet.PackageManagement.UI/Automation/TabItemButtonAutomationPeer.cs
> +        private TabItemButton tabItemButton;
`readonly` rename to `_tabItemButton`

2017-06-08 16:22 UTC, alpaix commented on src/NuGet.Clients/NuGet.PackageManagement.UI/Automation/TabItemButtonAutomationPeer.cs
> +            this.tabItemButton = owner;
null-check

2017-06-08 16:22 UTC, alpaix commented on src/NuGet.Clients/NuGet.PackageManagement.UI/TabItemButton.cs
> +    public class TabItemButton: Button
Format document <kbd>Ctrl+K</kbd>, <kbd>Ctrl+D</kbd>

2017-06-08 16:22 UTC, alpaix commented on src/NuGet.Clients/NuGet.PackageManagement.UI/Automation/TabItemButtonAutomationPeer.cs
> +            this.tabItemButton = owner;
remove `this` here and everywhere else. This generates `IDE0003` warning, so make sure all of them are addressed.

2017-06-08 17:26 UTC, bhavyaus commented on src/NuGet.Clients/NuGet.PackageManagement.UI/Automation/TabItemButtonAutomationPeer.cs
> +namespace NuGet.PackageManagement.UI.Automation
fixed.

2017-06-08 17:26 UTC, bhavyaus commented on src/NuGet.Clients/NuGet.PackageManagement.UI/Automation/TabItemButtonAutomationPeer.cs
> +    public class TabItemButtonAutomationPeer : FrameworkElementAutomationPeer, ISelectionItemProvider
fixed.

2017-06-08 17:26 UTC, bhavyaus commented on src/NuGet.Clients/NuGet.PackageManagement.UI/Automation/TabItemButtonAutomationPeer.cs
> +        private TabItemButton tabItemButton;
fixed.

2017-06-08 17:27 UTC, bhavyaus commented on src/NuGet.Clients/NuGet.PackageManagement.UI/Automation/TabItemButtonAutomationPeer.cs
> +            this.tabItemButton = owner;
fixed.

2017-06-08 17:27 UTC, bhavyaus commented on src/NuGet.Clients/NuGet.PackageManagement.UI/TabItemButton.cs
> +    public class TabItemButton: Button
fixed.

2017-06-08 17:34 UTC, sbanni approved these changes

2017-06-08 19:05 UTC, alpaix commented on src/NuGet.Clients/NuGet.PackageManagement.UI/Automation/TabItemButtonAutomationPeer.cs
> +        private TabItemButton _tabItemButton;
`readonly`

2017-06-08 19:06 UTC, alpaix commented on src/NuGet.Clients/NuGet.PackageManagement.UI/Automation/TabItemButtonAutomationPeer.cs
> +            Debug.Assert(owner != null);
This should throw `ArgumentNullException`. As an alternative you can use `Assumes.NotNull`

2017-06-08 19:07 UTC, alpaix approved these changes
Minor notes. Otherwise :shipit:

2017-06-08 21:09 UTC, merged