[ISSUE #1774, Nuget/Home] Update nuget.exe help for high level commands
NuGet/NuGet.Client pull request #1478
Opened 2017-06-08 03:30 UTC by mido3ds

PR for issue https://github.com/NuGet/Home/issues/1774

2017-06-08 03:30 UTC, dnfclas commented
@__mido3ds__,
Thanks for your contribution.
To ensure that the project team has proper rights to use your work, please complete the Contribution License Agreement at https://cla2.dotnetfoundation.org.

It will cover your contributions to all .NET Foundation-managed open source projects.
_Thanks,
.NET Foundation Pull Request Bot_

2017-06-08 03:37 UTC, dnfclas commented
__@mido3ds__, thanks for signing the contribution license agreement. We will now validate the agreement and then the pull request.
<br />_Thanks, .NET Foundation Pull Request Bot_

2017-06-08 05:23 UTC, nkolev92 requested changes
Hi @mido3ds,

Thank you for your contribution!

I have added some comments to the PR.
Please address them before we proceed.

2017-06-08 05:23 UTC, nkolev92 commented on src/NuGet.Clients/NuGet.CommandLine/NuGetCommand.resx
> -    <value>Deletes a package from the server.</value>
When you edit a resource file, please make sure the generated Designer file is added to the PR too.

2017-06-08 05:23 UTC, nkolev92 commented on src/NuGet.Core/NuGet.CommandLine.XPlat/Strings.resx
> -    <value>Deletes a package from the server.</value>
Same here. 
Please make sure that the relevant Designer is updated as well.

2017-06-25 06:46 UTC, mido3ds commented
@nkolev92
I have update the Designer and added it to PR.  

thanks for your time

2017-11-10 23:46 UTC, emgarten commented
Thanks for the PR @mido3ds, I am closing due to lack of activity at this time.

2017-11-10 23:46 UTC, closed without merging