Updated file share permissions while reading project.json
NuGet/NuGet.Client pull request #1487
Opened 2017-06-13 18:29 UTC by jainaashish

There are watson crash indicating it failed to access project.json file since it was being used by another program. Although we couldn't repro it locally, but I feel this is to do with the fact that we try to read project.json at multiple level with different file share access. So I'm making all the steam reader to use same file share permissions (even more granular access) to read project.json. Also, we're already using this same file share access for packages.config scenarios and never faced such issue so I'm hopeful that it will resolve this issue.

Fixes https://github.com/NuGet/Home/issues/5404

@rrelyea

2017-06-13 18:37 UTC, rohit21agrawal commented on src/NuGet.Core/NuGet.ProjectModel/JsonPackageSpecReader.cs
> +        public static readonly FileShare share = FileShare.ReadWrite | FileShare.Delete;
Change to FileSharePermissions to be more descriptive

2017-06-13 18:38 UTC, rohit21agrawal commented on src/NuGet.Core/NuGet.ProjectModel/JsonPackageSpecReader.cs
> +            using (var stream = new FileStream(packageSpecPath, FileMode.Open, FileAccess.Read, share))
why give read-write permission when only reading is required?

2017-06-13 18:41 UTC, nkolev92 commented on src/NuGet.Core/NuGet.ProjectModel/JsonPackageSpecReader.cs
> +        public static readonly FileShare share = FileShare.ReadWrite | FileShare.Delete;
Well FileSharePermissions...file access is a different thing.

2017-06-13 18:42 UTC, rohit21agrawal commented on src/NuGet.Core/NuGet.ProjectModel/JsonPackageSpecReader.cs
> +        public static readonly FileShare share = FileShare.ReadWrite | FileShare.Delete;
yeah i just read the constructor description

---
In reply to: [121762845](https://github.com/NuGet/NuGet.Client/pull/1487#discussion_r121762845) [](ancestors = 121762845)

2017-06-13 18:42 UTC, rohit21agrawal commented on src/NuGet.Core/NuGet.ProjectModel/JsonPackageSpecReader.cs
> +            using (var stream = new FileStream(packageSpecPath, FileMode.Open, FileAccess.Read, share))
never mind, makes sense now.

---
In reply to: [121762020](https://github.com/NuGet/NuGet.Client/pull/1487#discussion_r121762020) [](ancestors = 121762020)

2017-06-13 18:44 UTC, rohit21agrawal commented on src/NuGet.Core/NuGet.PackageManagement/Projects/ProjectJsonNuGetProject.cs
> +                using (var streamReader = new StreamReader(_jsonConfig.Open(FileMode.Open, FileAccess.Read, JsonPackageSpecReader.share)))
maybe make this a static public utility method on the JsonPackageSpecReader class?

2017-06-13 18:49 UTC, jainaashish commented on src/NuGet.Core/NuGet.ProjectModel/JsonPackageSpecReader.cs
> +        public static readonly FileShare share = FileShare.ReadWrite | FileShare.Delete;
I thought `share` was also self explanatory but I'm open to any good suggestion which you guys feel  would be more appropriate...

2017-06-13 18:50 UTC, jainaashish commented on src/NuGet.Core/NuGet.PackageManagement/Projects/ProjectJsonNuGetProject.cs
> +                using (var streamReader = new StreamReader(_jsonConfig.Open(FileMode.Open, FileAccess.Read, JsonPackageSpecReader.share)))
why?

2017-06-13 18:51 UTC, rohit21agrawal commented on src/NuGet.Core/NuGet.PackageManagement/Projects/ProjectJsonNuGetProject.cs
> +                using (var streamReader = new StreamReader(_jsonConfig.Open(FileMode.Open, FileAccess.Read, JsonPackageSpecReader.share)))
so people don't make this mistake in the future and just use the one method that's supposed to do the reading work for project.json.

2017-06-13 18:58 UTC, emgarten commented
Writing should be updated also to use https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Common/PathUtil/FileUtility.cs#L82 

Writing the lock file and target files use this already, so there is no reason project.json can't be written the same way.

2017-06-13 19:01 UTC, rohit21agrawal commented on src/NuGet.Core/NuGet.ProjectModel/JsonPackageSpecReader.cs
> +        public static readonly FileShare share = FileShare.ReadWrite | FileShare.Delete;
FileSharePermissions sounds better

2017-06-13 19:28 UTC, alpaix commented
Can you think of a test emulating original scenario in order to validate the fix?
Also would adding a retry mechanism around the write operation help resolving it?

2017-06-13 20:23 UTC, emgarten commented
Retry would be helpful also. @nkolev92 has a PR out that includes a file reader with retry in FileUtilities, you could use that.

2017-06-13 21:08 UTC, jainaashish commented
@alpaix I wasn't able to repro it locally and neither I'm 100% sure about the scenario like where exactly it threw that error so I can't think of a test emulating it to validate. This code change is a safeguard to avoid such exceptions.

I can add retry logic.

2017-06-14 03:12 UTC, emgarten requested changes
Looking much better, update this so SafeRead handles the complete file read and then I think this will be perfect

2017-06-14 03:12 UTC, emgarten commented on src/NuGet.Core/NuGet.ProjectModel/JsonPackageSpecReader.cs
> +        public static readonly FileShare share = FileShare.ReadWrite | FileShare.Delete;
This isn't used anymore with SafeRead

2017-06-14 03:12 UTC, emgarten commented on src/NuGet.Core/NuGet.PackageManagement/Projects/ProjectJsonNuGetProject.cs
> +                using (var streamReader = FileUtility.SafeRead(filePath: JsonConfigPath, read: (stream, filePath) => new StreamReader(stream)))
This and the one above should create the JObject inside FileUtility.SafeRead.

 Just returning the unread stream could still hit issues and throw outside the retry loop.

The pattern should look the same as FileUtility.Replace where all the work is done inside

2017-06-14 18:37 UTC, jainaashish commented on src/NuGet.Core/NuGet.PackageManagement/Projects/ProjectJsonNuGetProject.cs
> +                using (var streamReader = FileUtility.SafeRead(filePath: JsonConfigPath, read: (stream, filePath) => new StreamReader(stream)))
yes, I thought about it after pushing this change :) will update it.

2017-06-15 00:03 UTC, nkolev92 commented on test/NuGet.Core.Tests/NuGet.Common.Test/FileUtilityTests.cs
> +        public void FileUtility_SafeRead_Success()
:clap:

2017-06-15 00:03 UTC, nkolev92 approved these changes

2017-06-15 00:44 UTC, emgarten approved these changes
LGTM 🥇

2017-06-15 21:29 UTC, merged