[WIP] stuffses
NuGet/NuGet.Client pull request #1488
Opened 2017-06-13 18:53 UTC by mishra14

2017-06-13 19:13 UTC, emgarten approved these changes
LGTM

2017-06-14 20:03 UTC, emgarten approved these changes
🚀

2017-06-14 20:44 UTC, rohit21agrawal requested changes

2017-06-14 20:44 UTC, rohit21agrawal commented on src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/ProjectServices/VsManagedLanguagesProjectSystemServices.cs
> +            _referenceMetadata = Array.CreateInstance(typeof(string), 4);
i know this isn't related, but can we please simplify this to :
_referenceMetadata = new string[] {..... }  ?

2017-06-14 20:44 UTC, rohit21agrawal commented on src/NuGet.Core/NuGet.Commands/RestoreCommand/RestoreCommand.cs
> +                ProjectPath = _request.Project.RestoreMetadata?.ProjectPath,
why remove the null check on Project?

2017-06-14 20:44 UTC, rohit21agrawal commented on src/NuGet.Core/NuGet.Commands/RestoreCommand/RestoreCommand.cs
> +                    ProjectFrameworks = request.Project.TargetFrameworks.Select(f => f.FrameworkName).ToList()
no need to do a ToList() as it causes it  to iterate unnecessarily.

2017-06-14 20:44 UTC, rohit21agrawal commented on src/NuGet.Core/NuGet.Commands/RestoreCommand/Logging/WarningPropertiesCollection.cs
> +        public IReadOnlyList<NuGetFramework> ProjectFrameworks { get; set; } = new List<NuGetFramework>();
maybe instantiate with ReadOnlyCollection otherwise someone could cast it to a list and modify it.

2017-06-14 20:45 UTC, rohit21agrawal commented on src/NuGet.Core/NuGet.Commands/RestoreCommand/Logging/WarningPropertiesCollection.cs
> +        public IReadOnlyList<NuGetFramework> ProjectFrameworks { get; set; } = new List<NuGetFramework>();
i am not sure about this actually so might be worth verifying.

2017-06-14 20:57 UTC, rohit21agrawal commented on src/NuGet.Core/NuGet.Commands/RestoreCommand/Logging/WarningPropertiesCollection.cs
> +        public IReadOnlyList<NuGetFramework> ProjectFrameworks { get; set; } = new List<NuGetFramework>();
more info here: https://stackoverflow.com/a/17398449/2430119

2017-06-14 21:28 UTC, mishra14 commented on src/NuGet.Core/NuGet.Commands/RestoreCommand/RestoreCommand.cs
> +                ProjectPath = _request.Project.RestoreMetadata?.ProjectPath,
This cannot be null. clarified with @emgarten while debugging.

2017-06-14 21:29 UTC, mishra14 commented on src/NuGet.Core/NuGet.Commands/RestoreCommand/RestoreCommand.cs
> +                    ProjectFrameworks = request.Project.TargetFrameworks.Select(f => f.FrameworkName).ToList()
ToList prevents an enumerator being created on every foreach

2017-06-14 21:55 UTC, mishra14 commented on src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/ProjectServices/VsManagedLanguagesProjectSystemServices.cs
> +            _referenceMetadata = Array.CreateInstance(typeof(string), 4);
I dont feel confident changing `_referenceMetadata = Array.CreateInstance(typeof(string), 4);`

2017-06-14 21:59 UTC, mishra14 commented on src/NuGet.Core/NuGet.Commands/RestoreCommand/Logging/WarningPropertiesCollection.cs
> +        public IReadOnlyList<NuGetFramework> ProjectFrameworks { get; set; } = new List<NuGetFramework>();
We dont have any convention for that. We use this style in other places across our code.

2017-06-14 22:08 UTC, mishra14 commented on src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/ProjectServices/VsManagedLanguagesProjectSystemServices.cs
> +            _referenceMetadata = Array.CreateInstance(typeof(string), 4);
Possibly. But we should figure out the reason why was this used in a separate check in.

2017-06-14 22:55 UTC, rohit21agrawal commented on src/NuGet.Core/NuGet.Commands/RestoreCommand/Logging/WarningPropertiesCollection.cs
> +        public IReadOnlyList<NuGetFramework> ProjectFrameworks { get; set; } = new List<NuGetFramework>();
if we use it in other places, it doesn't make it right.

2017-06-14 23:51 UTC, mishra14 commented
🔔

2017-06-14 23:52 UTC, rohit21agrawal approved these changes

2017-06-15 21:33 UTC, merged