Show SemVer2 build metadata on package details page in VS
NuGet/NuGet.Client pull request #1519
Opened 2017-06-28 12:17 UTC by xavierdecoster

NuGet/Home#5494

2017-06-28 16:03 UTC, alpaix requested changes
Please add tests.

2017-06-28 16:30 UTC, xavierdecoster commented
@alpaix can you please point me to the current tests where I should add these?

2017-06-28 16:53 UTC, alpaix commented
As long as the core logic of your change is encapsulated in a converter class you need to unittest the converter only [test/NuGet.Clients.Tests/NuGet.PackageManagement.UI.Test/Converters](https://github.com/NuGet/NuGet.Client/tree/dev/test/NuGet.Clients.Tests/NuGet.PackageManagement.UI.Test/Converters). 

P.S. We're working on establishing UI test automation infrastructure. Currently it is manually tested by overseas vendors. Consider also instructing them how to validate it.

2017-06-28 17:04 UTC, rohit21agrawal commented on src/NuGet.Clients/NuGet.PackageManagement.UI/DisplayVersion.cs
> +            if (versionFormat == null)
given that you have already defaulted to "N" in the function definition, do you really need this case?

2017-06-29 09:15 UTC, xavierdecoster commented on src/NuGet.Clients/NuGet.PackageManagement.UI/DisplayVersion.cs
> +            if (versionFormat == null)
The default will not be applied if an explicit `null` value is provided?

2017-06-29 17:54 UTC, rohit21agrawal commented on src/NuGet.Clients/NuGet.PackageManagement.UI/DisplayVersion.cs
> +            if (versionFormat == null)
oh, I see. no one should provide an explicit null here , but i guess its fine to check here.

2017-06-29 18:03 UTC, xavierdecoster commented on src/NuGet.Clients/NuGet.PackageManagement.UI/DisplayVersion.cs
> +            if (versionFormat == null)
This could be null :) https://github.com/NuGet/NuGet.Client/pull/1519/files#diff-c20d2bf504a1dc14b412134958fb54e9R22

2017-06-29 18:16 UTC, rohit21agrawal approved these changes

2017-06-29 19:12 UTC, xavierdecoster commented
@alpaix care to have another look?

2017-06-29 19:54 UTC, alpaix approved these changes
LGTM

2017-06-30 08:11 UTC, merged