Setting HideWarningsAndErrors to false on Install to display detailed errors in the output console
NuGet/NuGet.Client pull request #1535
Opened 2017-07-06 19:38 UTC by mishra14

Fixes: https://github.com/NuGet/Home/issues/5510

During the work for Warnings and Errors we introduced a bool `HideWarningsAndErrors` in the dg spec to prevent displaying restore warnings and errors. This was only used for net core sdk projects and is set on nomination.

Since during Package Install through PM.UI we do not generate an assets file on failure, we should display warnings and errors.

Output window - 

```
Restoring packages for C:\Users\anmishr\source\repos\ClassLibrary8\ClassLibrary8\ClassLibrary8.csproj...
Package Microsoft.AspNetCore.Mvc.ViewFeatures 1.1.3 is not compatible with netstandard1.4 (.NETStandard,Version=v1.4). Package Microsoft.AspNetCore.Mvc.ViewFeatures 1.1.3 supports:
  - net451 (.NETFramework,Version=v4.5.1)
  - netstandard1.6 (.NETStandard,Version=v1.6)
Package restore failed. Rolling back package changes for 'ClassLibrary8'.
Time Elapsed: 00:00:11.9556179
========== Finished ==========
```

2017-07-06 19:40 UTC, emgarten commented
This looks correct, but it may need to hide warnings for scenarios where the install passes but warnings occur. Otherwise there could be duplicates.

2017-07-06 19:41 UTC, mishra14 commented
@emgarten  I am investigating that right now.

2017-07-06 23:47 UTC, emgarten commented on src/NuGet.Core/NuGet.PackageManagement/NuGetPackageManager.cs
> +            if (logMessages.Any( m => m.Level == LogLevel.Error))
Use restoreResult.Result.Success instead, only call this method if it is false

2017-07-06 23:48 UTC, emgarten requested changes

2017-07-06 23:48 UTC, emgarten commented on src/NuGet.Core/NuGet.PackageManagement/NuGetPackageManager.cs
> +                    logger.LogAsync(restoreLogMessage);
this needs await

2017-07-06 23:52 UTC, rohit21agrawal commented on src/NuGet.Core/NuGet.PackageManagement/NuGetPackageManager.cs
> +                    logger.LogAsync(restoreLogMessage);
in that case, make the method name ReplayWarningsAndErrorsAsync

2017-07-06 23:53 UTC, rohit21agrawal commented on src/NuGet.Core/NuGet.PackageManagement/NuGetPackageManager.cs
> +                    var restoreLogMessage = new RestoreLogMessage(logMessage.Level, logMessage.Code, logMessage.Message)
just curious, these look like the same data structures (in respect to properties) - what's the difference between them?

2017-07-06 23:54 UTC, nkolev92 reviewed
Tests?

2017-07-06 23:54 UTC, nkolev92 commented on src/NuGet.Core/NuGet.PackageManagement/NuGetPackageManager.cs
> +        private void ReplayWarningsAndErrors(LockFile lockFile, ILogger logger)
Is this method the same as the one in RestoreCommand?

2017-07-07 00:20 UTC, mishra14 commented on src/NuGet.Core/NuGet.PackageManagement/NuGetPackageManager.cs
> +                    var restoreLogMessage = new RestoreLogMessage(logMessage.Level, logMessage.Code, logMessage.Message)
Loggers do not log `IAssetsMessage` as `ILogger` exist in `NuGet.Common` and `IAssetsLogMessage` exists in `NuGet.ProjectModel`.

2017-07-07 01:23 UTC, emgarten approved these changes
address feedback then :shipit:

2017-07-07 01:23 UTC, emgarten commented on src/NuGet.Core/NuGet.Commands/Utility/Extensions.cs
> +        public static RestoreLogMessage AsRestoreLogMessage(this IAssetsLogMessage logMessage)
Add summary

2017-07-07 01:23 UTC, emgarten commented on src/NuGet.Core/NuGet.Commands/RestoreCommand/Utility/MSBuildRestoreUtility.cs
> +            var logMessages = (lockFile?.LogMessages ?? Enumerable.Empty<IAssetsLogMessage>())
the ``??`` should be at the end

2017-07-07 01:30 UTC, mishra14 commented
@nkolev92 @rohit21agrawal updated and added couple of tests. Take a look. I will do some manual validation as well, before merging.

2017-07-07 04:35 UTC, nkolev92 approved these changes
LGTM other than the naming suggestion.

2017-07-07 04:35 UTC, nkolev92 commented on src/NuGet.Core/NuGet.Commands/RestoreCommand/Utility/MSBuildRestoreUtility.cs
> +        public static Task ReplayWarningsAndErrors(LockFile lockFile, ILogger logger)
ReplayWarningsAndErrorsAsync

2017-07-07 04:35 UTC, nkolev92 commented on src/NuGet.Core/NuGet.PackageManagement/NuGetPackageManager.cs
> +                !restoreResult.Result.Success)
I saw @emgarten suggested this, but I don't get how this could lead to duplicates. Can you please explain?

2017-07-10 22:10 UTC, merged