fetching ProjectTypeGuid in LSL mode
NuGet/NuGet.Client pull request #1546
Opened 2017-07-13 17:01 UTC by zhili1208

the bug is in LSL mode, IsSupport() check for project always return true, then nuget initialize lots of unsupport projects. That cause perf issue and also show unsupport project in project list of UI or powershell.

Fix here is fetching ProjectTypeGuid and ProjectTypeGuids from AnyCode database and filtering out unsupport projects

2017-07-13 18:21 UTC, emgarten requested changes

2017-07-13 18:21 UTC, emgarten commented on src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/Projects/VsProjectAdapter.cs
> +                        return projectTypeGuids.Split(';');
Use this helper method https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Commands/Utility/MsBuildStringUtility.cs#L15

It handles whitespace and other common scenarios that have been problems for msbuild

2017-07-13 18:21 UTC, emgarten commented on src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/Projects/VsProjectAdapter.cs
> +                    if (!string.IsNullOrEmpty(_projectTypeGuid))
Add comments on the order of fallback here

2017-07-13 18:21 UTC, emgarten commented on src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/Services/DeferredProjectWorkspaceService.cs
> +            if(!string.IsNullOrEmpty(relativeProjectPath)
nit: spacing, format the document

2017-07-13 18:21 UTC, emgarten commented on src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/Services/DeferredProjectWorkspaceService.cs
> +            var relativeProjectPath = Common.PathUtility.GetRelativePath(solutionPath, projectFilePath);
Add using for `Common` unless this is conflicting with something else

2017-07-13 18:21 UTC, emgarten commented on src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/Services/DeferredProjectWorkspaceService.cs
> +            var indexedSolutionProjectTypes = (await indexService.GetFileDataValuesAsync<ProjectBaseTypesInSolution>(solutionPath,
nit: I would assign the awaited value and then use it, but it would be the same result

2017-07-13 18:21 UTC, emgarten commented on src/NuGet.Clients/NuGet.VisualStudio.Common/VsHierarchyUtility.cs
> +        private static readonly HashSet<string> UnsupportedProjectCapabilities = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
I don't see this being used as a hash set or to compare, I only see it used for iterating, i would make this an array instead

2017-07-13 18:21 UTC, emgarten commented on src/NuGet.Clients/NuGet.VisualStudio.Common/NuGet.VisualStudio.Common.csproj
> +    <Compile Update="SupportedProjectTypes.cs" />
Why is this needed and why Update? Isn't this in the folder?

2017-07-13 19:24 UTC, alpaix requested changes
Couple of notes, plus Justin's comments. Also format documents <kbd>Ctrl + K</kbd>, <kbd>Ctrl + D</kbd>

2017-07-13 19:24 UTC, alpaix commented on src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/Services/DeferredProjectWorkspaceService.cs
> +                return "{"+projectTypeGuid.ToString()+"}";
`projectTypeGuid.ToString("B")`

2017-07-13 19:24 UTC, alpaix commented on src/NuGet.Clients/NuGet.VisualStudio.Common/VsHierarchyUtility.cs
> +            foreach (var unsupportedProjectCapability in UnsupportedProjectCapabilities)
```cs
return UnsupportedProjectCapabilities.Any(c => hierarchy.IsCapabilityMatch(c));
```

2017-07-13 19:24 UTC, alpaix commented on src/NuGet.Clients/NuGet.VisualStudio.Common/VsHierarchyUtility.cs
> +            if (hierarchy.IsCapabilityMatch("AssemblyReferences + DeclaredSourceItems + UserSourceItems"))
Similar to `EnvDTEProjectUtility.IsProjectCapabilityCompliant`. Consider unifying them.

2017-07-17 21:12 UTC, zhili1208 commented on src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/Services/DeferredProjectWorkspaceService.cs
> +            var relativeProjectPath = Common.PathUtility.GetRelativePath(solutionPath, projectFilePath);
Yes, it's conflicting

2017-07-17 21:42 UTC, emgarten approved these changes
LGTM

2017-07-18 17:29 UTC, alpaix approved these changes
LGTM

2017-07-18 18:37 UTC, jainaashish requested changes
Looks good, but can we add some tests as well for this scenario?

2017-07-28 18:37 UTC, closed without merging

2017-07-28 22:35 UTC, nkolev92 commented
@zhili1208 this PR is not the way to go for 15.4?

2017-08-03 18:59 UTC, zhili1208 commented
@nkolev92 it's in 15.4, it didn't show up here because of rebase