Creating NuGet.Localization.nupkg for delivering localized components to dotnet cli
NuGet/NuGet.Client pull request #1566
Opened 2017-07-21 01:47 UTC by mishra14

Adding a script `scripts/cibuild/CreateLocalizedPackage.ps1` that is invoked by VSTS cli to create a localization package containing all the satellite assemblies for our `nupkgs`.

The script invokes a target in loc.proj which then invokes targets per project to get all localized dlls. These dlls are then placed in a common location. 

I have also added a new `nuspec` file to pack the package.

I am going to work with someone from the cli team to verify this. But please take a look in the mean time.

Once this is merged I will add the VSTS step to the official build definition.

2017-07-21 22:16 UTC, emgarten requested changes
move to MSBuild

2017-07-21 23:00 UTC, rohit21agrawal commented
If you can wait until Monday, i will show you a couple more tricks to clean this up

2017-07-21 23:00 UTC, rohit21agrawal requested changes

2017-07-21 23:00 UTC, rohit21agrawal commented on build/common.targets
> +      <_AllResourceDlls Include="$(OutputPath)**\$(AssemblyName).resources.dll"/>
Isn't this item group already being used in a different target?

2017-07-21 23:00 UTC, rohit21agrawal commented on build/common.targets
> +      <LocalizedFilesFromProject Include="@(_AllResourceDlls)" Condition="'@(_AllResourceDlls)'!=''">
Don't think this condition makes sense for item groups

2017-07-21 23:06 UTC, mishra14 commented on build/common.targets
> +      <LocalizedFilesFromProject Include="@(_AllResourceDlls)" Condition="'@(_AllResourceDlls)'!=''">
In case the resource files are not present, the this condition prevents failures.

2017-07-21 23:13 UTC, emgarten approved these changes

2017-07-21 23:13 UTC, rohit21agrawal requested changes

2017-07-21 23:13 UTC, rohit21agrawal commented on build/common.targets
> +      Properties="TargetFramework=%(ProjectTargetFrameworkEntries.Identity);
Why do you need to do an inner build?

2017-07-21 23:13 UTC, rohit21agrawal commented on build/common.targets
> +      Properties="TargetFramework=%(ProjectTargetFrameworkEntries.Identity);
All the localised files are already present in $(LocalizationRootDirectory) , this move is redundant

2017-07-22 00:52 UTC, mishra14 commented on build/common.targets
> +      Properties="TargetFramework=%(ProjectTargetFrameworkEntries.Identity);
Where are those files moved?

2017-07-24 18:32 UTC, rohit21agrawal requested changes

2017-07-24 18:32 UTC, rohit21agrawal commented on build/common.targets
> +      <LocalizedFiles Include="$(OutputPath)**\$(AssemblyName).resources.dll"/>
start with _ since these are internal itemgroups

2017-07-24 18:32 UTC, rohit21agrawal commented on build/build.proj
> +          ItemName="LocalizedFiles" />
LocalizedFilesForNupkg

2017-07-24 18:32 UTC, rohit21agrawal commented on build/build.proj
> +        <TargetPath>$(ArtifactsDirectory)LocalizedFiles\%(LocalizedFiles.RelativeTargetPath)</TargetPath>
change this to msbuild variable

2017-07-24 18:32 UTC, rohit21agrawal commented on build/build.proj
> +  <Target Name="GenerateLocalizedPackage" DependsOnTargets="MoveLocalizedFilesToLocalizedArtifacts" Condition=" '$(IsXPlat)' != 'true' ">
change to $(PackProject) == true

2017-07-24 21:18 UTC, rohit21agrawal commented on build/Nuspec/NuGet.Localization.nuspec
> +<?xml version="1.0" encoding="utf-8"?>
put this file under src as well. Create a folder for the project name and put it under there.

2017-07-24 22:26 UTC, rohit21agrawal commented on build/common.targets
> +  <Target Name="GetLocalizedFilesForLocalizationPackage" Returns="@(_LocalizedFilesForLocalizationPackage)" Condition=" '$(Shipping)' == 'true' ">
this should also be PackProject == true

2017-07-25 20:13 UTC, emgarten commented
:shipit:

2017-07-25 20:15 UTC, mishra14 commented
Had an offline discussion with @emgarten. merging this in to get this into CLI ASAP.

2017-07-25 20:15 UTC, merged