Net standard 2.0 support for VS2015
NuGet/NuGet.Client pull request #1607
Opened 2017-08-02 23:54 UTC by jainaashish

This PR is to support net standard 2.0 for VS2015. There is a new .net standard support extension for the .net frameworks so if this MSI is not installed and user tries to install a net standard 2.0 package into net461 project, then we will throw a error asking user to install this MSI in order to install this package.

Fixes https://github.com/NuGet/Home/issues/5325

@rrelyea

2017-08-03 19:55 UTC, mishra14 requested changes
Some comments/clarifications.

2017-08-03 19:55 UTC, mishra14 commented on src/NuGet.Clients/PackageManagement.VisualStudio/ProjectSystems/VSMSBuildNuGetProjectSystem.cs
> +        public bool IsNetStandardMSINeeded()
please add some comments for public methods.

2017-08-03 19:55 UTC, mishra14 commented on src/NuGet.Clients/NuGet.CommandLine/Common/MSBuildProjectSystem.cs
> +        public bool IsNetStandardMSINeeded()
please add some comments for public methods.

2017-08-03 19:55 UTC, mishra14 commented on src/NuGet.Core/NuGet.PackageManagement/NuGetPackageManager.cs
> +                if (nuGetProject.TryGetMetadata<NuGetFramework>(NuGetProjectMetadataKeys.TargetFramework, out targetFramework))
nit: targetFramework can be declared as part of the function call.

2017-08-03 19:55 UTC, mishra14 commented on src/NuGet.Core/NuGet.PackageManagement/NuGetPackageManager.cs
> +                                // Check to see if the hack to install make net461/net462/net47 compatibile with netstandard20 or greater
nit: Check to see if the hack to make net461/net462/net47 compatibile with netstandard20 or greater

2017-08-03 19:55 UTC, mishra14 commented on src/NuGet.Core/NuGet.PackageManagement/Utility/NetStandardCompatibilityUtil.cs
> +        internal static bool DoesProjectTargetsNEt461ORGreater(NuGetFramework currentProjectFramework)
typo: DoesProjectTargetsNet461ORGreater or DoesProjectTargetsNET461ORGreater

2017-08-03 19:55 UTC, mishra14 commented on src/NuGet.Core/NuGet.PackageManagement/Utility/NetStandardCompatibilityUtil.cs
> +            if (currentProjectFramework.IsDesktop()
[IsDesktop ](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Frameworks/FrameworkExtensions.cs#L21)also returns true for `AspNet ` and `DNX`. Maybe we should check for `NetFramework `explicitly?

2017-08-03 19:55 UTC, mishra14 commented on src/NuGet.Core/NuGet.PackageManagement/Utility/NetStandardCompatibilityUtil.cs
> +            // hence the !needsNetstandard20Assets condition.
Where is this condition checked?

2017-08-03 21:56 UTC, jainaashish commented on src/NuGet.Clients/PackageManagement.VisualStudio/ProjectSystems/VSMSBuildNuGetProjectSystem.cs
> +        public bool IsNetStandardMSINeeded()
As discussed offline, this is not a public public method, and for our understanding, name is self explanatory. I can add a comment down line to specify when we think MSI is installed.

2017-08-03 21:57 UTC, jainaashish commented on src/NuGet.Clients/NuGet.CommandLine/Common/MSBuildProjectSystem.cs
> +        public bool IsNetStandardMSINeeded()
Explained on another comment

2017-08-03 21:57 UTC, jainaashish commented on src/NuGet.Core/NuGet.PackageManagement/NuGetPackageManager.cs
> +                if (nuGetProject.TryGetMetadata<NuGetFramework>(NuGetProjectMetadataKeys.TargetFramework, out targetFramework))
yeah, but this is more readable.

2017-08-03 21:58 UTC, jainaashish commented on src/NuGet.Core/NuGet.PackageManagement/NuGetPackageManager.cs
> +                                // Check to see if the hack to install make net461/net462/net47 compatibile with netstandard20 or greater
corrected

2017-08-03 22:04 UTC, jainaashish commented on src/NuGet.Core/NuGet.PackageManagement/Utility/NetStandardCompatibilityUtil.cs
> +            if (currentProjectFramework.IsDesktop()
As discussed offline, this has been the same behavior for VS 2017 as well so we just back ported it. I think we shouldn't change anything here until we decides to explicitly not supporting ASPNet or DNX. And if we ever decides it then it should be changed for VS 2017 and not for VS 2015.

2017-08-03 22:05 UTC, jainaashish commented on src/NuGet.Core/NuGet.PackageManagement/Utility/NetStandardCompatibilityUtil.cs
> +            // hence the !needsNetstandard20Assets condition.
copy-paste mistake, corrected the comment.

2017-08-03 22:32 UTC, mishra14 approved these changes
LGTM!

2017-08-04 00:03 UTC, merged

2017-08-14 18:02 UTC, BradBarnich commented
The link doesn't work. https://aka.ms/netstandard-build-support-netfx goes to microsoft.com