remaking methods virtual in PackagePathResolver
NuGet/NuGet.Client pull request #1608
Opened 2017-08-03 03:44 UTC by rohit21agrawal

Fixes: https://github.com/NuGet/Home/issues/5700

CC: @joelverhagen - the methods ceased to be virtual as part of your changeset for https://github.com/NuGet/NuGet.Client/commit/b8372bbc3720b08b08337122d3e5569df3cf7c6c .. any particular reason why?

2017-08-03 04:28 UTC, nkolev92 approved these changes
🚢

2017-08-03 04:48 UTC, emgarten requested changes
Can you update https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Packaging/VersionFolderPathResolver.cs also to make these consistent?

2017-08-03 05:00 UTC, emgarten commented
Also check out https://github.com/NuGet/NuGet.Client/pull/1610

2017-08-03 17:31 UTC, rohit21agrawal commented
@emgarten changes made.

2017-08-03 17:43 UTC, dtivel requested changes
If this broke once, it can break again.

We need some assurance that we won't break this again.  How about adding tests?

2017-08-03 18:24 UTC, joelverhagen commented
>  the methods ceased to be virtual as part of your changeset for b8372bb .. any particular reason why?

It's been a while, but I think it's because they were not being overridden anywhere.

Given that this is part of our contract with customers (a fact I did not realize at the time), I totally agreed with @dtivel that we need tests around this.

2017-08-03 18:38 UTC, rohit21agrawal commented
ok makes sense.. I will add tests

2017-08-03 23:24 UTC, rohit21agrawal commented
@emgarten @dtivel added tests to test overriding behavior

2017-08-04 00:26 UTC, emgarten approved these changes
:rocket:

2017-08-04 00:33 UTC, merged

2017-08-04 01:53 UTC, albahari commented
That's terrific, thanks.