Add msbuild task UserAgent strings for netcore vs desktop
NuGet/NuGet.Client pull request #1614
Opened 2017-08-04 01:18 UTC by emgarten

Desktop framework will use: `NuGet Desktop MSBuild Task`
NETStandard will use: `NuGet .NET Core MSBuild Task`

Fixes https://github.com/NuGet/Home/issues/5709

2017-08-04 01:44 UTC, nkolev92 approved these changes

2017-08-04 01:44 UTC, rohit21agrawal approved these changes

2017-08-04 17:25 UTC, jainaashish approved these changes

2017-08-04 22:34 UTC, mishra14 requested changes

2017-08-04 22:34 UTC, mishra14 commented on src/NuGet.Core/NuGet.Build.Tasks/RestoreTask.cs
> +#if IS_DESKTOP
Did you find where is `IS_DESKTOP` declared?

2017-08-04 22:41 UTC, mishra14 commented on src/NuGet.Core/NuGet.Build.Tasks/RestoreTask.cs
> +#if IS_DESKTOP
nvm, i found it [here](https://github.com/NuGet/NuGet.Client/blob/e6e7d4ddb2499f2cce370f9f1c477d204aec90ba/build/common.targets#L5).

2017-08-04 22:42 UTC, mishra14 approved these changes

2017-08-07 07:55 UTC, xavierdecoster commented
@emgarten any updates needed server-side to track these apparently new user agent strings? If so, could you create an issue on the gallery repo and assign it to me pls? :)

2017-08-07 18:16 UTC, emgarten commented
@xavierdecoster I'll open a gallery issue once this goes in, I just want to make sure the strings do not change as part of the feedback here :smile:

2017-08-08 05:59 UTC, merged