Add package prefix reservation logic and use vs image service
NuGet/NuGet.Client pull request #1623
Opened 2017-08-07 23:36 UTC by PatoBeltran

Work for https://github.com/NuGet/Home/issues/5694

2017-08-07 23:37 UTC, dnfclas commented
@__PatoBeltran__,
Thanks for your contribution.
To ensure that the project team has proper rights to use your work, please complete the Contribution License Agreement at https://cla2.dotnetfoundation.org.

It will cover your contributions to all .NET Foundation-managed open source projects.
_Thanks,
.NET Foundation Pull Request Bot_

2017-08-07 23:37 UTC, PatoBeltran commented
Missing fixing tests

2017-08-07 23:54 UTC, dnfclas commented
__@PatoBeltran__, thanks for signing the contribution license agreement. We will now validate the agreement and then the pull request.
<br />_Thanks, .NET Foundation Pull Request Bot_

2017-08-08 00:24 UTC, nkolev92 commented
@PatoBeltran Please rebase from dev as there are infrastructure changes that cause the VSTS build to fail.

2017-08-09 00:25 UTC, jainaashish commented on src/NuGet.Clients/NuGet.PackageManagement.UI/Models/PackageItemListViewModel.cs
> +using Microsoft.VisualStudio.Imaging.Interop;
sort these usings.

2017-08-09 00:26 UTC, jainaashish commented on src/NuGet.Clients/NuGet.PackageManagement.UI/Models/PackageItemListViewModel.cs
> +        public ImageMoniker PrefixReservedIndicatorMoniker
do you really need private as well as public fields here?

2017-08-09 00:27 UTC, jainaashish commented on src/NuGet.Clients/NuGet.PackageManagement.UI/NuGet.PackageManagement.UI.csproj
> +    <Reference Include="Microsoft.VisualStudio.Imaging.Interop.14.0.DesignTime, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL">
is it the same assembly be used for dev14 vs dev15?

2017-08-09 00:27 UTC, jainaashish commented on src/NuGet.Clients/NuGet.PackageManagement.UI/NuGet.PackageManagement.UI.csproj
> +    <Compile Include="Models\PackageIconMonikers.cs" />
is it also supported with dev14 (VS 2015)?

2017-08-09 03:29 UTC, jainaashish commented on src/NuGet.Clients/NuGet.PackageManagement.UI/Xamls/DownloadIndicator.xaml
> +﻿<!-- This file was generated by the AiToXaml tool.-->
I think you can remove these auto generated text

2017-08-09 03:29 UTC, jainaashish commented on src/NuGet.Clients/NuGet.PackageManagement.UI/Xamls/PackageItemControl.xaml
> +  xmlns:imaging="clr-namespace:Microsoft.VisualStudio.Imaging;assembly=Microsoft.VisualStudio.Imaging"
do you really need to define the assembly here?

2017-08-09 03:33 UTC, jainaashish commented on src/NuGet.Clients/NuGet.PackageManagement.UI/Xamls/PackageManagerControl.xaml.cs
> +            foreach (PackageItemListViewModel package in e.AddedItems)
You can use '_packageList.SelectedItem' to update prefix reserve moniker

2017-08-09 03:36 UTC, jainaashish commented on src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/PackageFeeds/MultiSourcePackageFeed.cs
> +        private const string NUGET_ORG_SOURCE_NAME = "nuget.org";
We already have this constant defined ( i think as part of protocol project or common). You can use that only.

2017-08-09 03:39 UTC, jainaashish commented on src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/PackageFeeds/MultiSourcePackageFeed.cs
> +        public bool IsOnlyLoadingFromNuGetOrg => !IsMultiSource && _sourceRepositories.First<SourceRepository>().ToString() == NUGET_ORG_SOURCE_NAME;
Ignore cases for string comparison. `StringComparer.OrdinalIgnoreCase.Equals(x, y)`

2017-08-09 03:40 UTC, jainaashish commented on src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/PackageFeeds/PlainPackageFeedBase.cs
> +        public bool IsOnlyLoadingFromNuGetOrg => false;
should it always be false?

2017-08-09 03:41 UTC, jainaashish commented on src/NuGet.Clients/NuGet.Tools/NuGetTools.vsct
> +    <GuidSymbol name="PackageIconMonikers" value="{8F5EAE8F-9892-4CE2-826C-764BEDE6D2EC}">
What's the purpose of adding these here? And I see other values are hexa decimal, so will that make any difference?

2017-08-09 03:48 UTC, jainaashish requested changes
Some improvements and questions, overall looks nice. Good job done!

2017-08-09 18:42 UTC, rohit21agrawal commented on src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/PackageFeeds/MultiSourcePackageFeed.cs
> +        public bool IsOnlyLoadingFromNuGetOrg => !IsMultiSource && StringComparer.OrdinalIgnoreCase.Equals(_sourceRepositories.First<SourceRepository>().ToString(), NuGetConstants.FeedName);
why do we only compare the first string in _sourceRepositories?

2017-08-09 18:42 UTC, rohit21agrawal commented on src/NuGet.Clients/NuGet.PackageManagement.UI/Xamls/PrefixReservedIndicator.xaml
> +              <GeometryDrawing Brush="#FFF6F6F6" Geometry="F1M16,8C16,12.411 12.411,16 8,16 3.589,16 0,12.411 0,8 0,3.589 3.589,0 8,0 12.411,0 16,3.589 16,8" />
no idea if these are correct or not, but curious to know how these were generated.

2017-08-09 18:43 UTC, rohit21agrawal commented on src/NuGet.Clients/NuGet.PackageManagement.UI/Xamls/PackageItemControl.xaml
> +  xmlns:imaging="clr-namespace:Microsoft.VisualStudio.Imaging;assembly=Microsoft.VisualStudio.Imaging"
yeah this is standard xaml convention - if we refer to a namespace in a different assembly, this is how you do it.

---
In reply to: [132083672](https://github.com/NuGet/NuGet.Client/pull/1623#discussion_r132083672) [](ancestors = 132083672)

2017-08-09 18:45 UTC, rohit21agrawal commented on src/NuGet.Clients/NuGet.VisualStudio.Client/NuGet.VisualStudio.Client.csproj
> +    </Content>
does it really need to ship as part of VSIX or can it included as an EmbeddedResource in the PackageManagement.UI dll?

2017-08-09 18:47 UTC, rohit21agrawal commented on src/NuGet.Core/NuGet.Protocol/LegacyFeed/V2FeedParser.cs
> +            bool prefixReserved = StringComparer.OrdinalIgnoreCase.Equals(bool.TrueString, GetString(properties, _xnamePrefixReserved));
instead of doing string comparison, parse the _xnamePrefixReserved as a boolean, and then do simple equality check.

2017-08-09 18:53 UTC, rohit21agrawal commented on src/NuGet.Clients/NuGet.PackageManagement.UI/Models/PackageItemListViewModel.cs
> +        public ImageMoniker PrefixReservedIndicatorMoniker
i am not sure if i understand this - the ImageMoniker will always be the same image right? Why does it need to trigger PropertyChanged event? We only need to toggle visibility of the image based on PrefixReserved .

2017-08-09 18:58 UTC, rohit21agrawal requested changes
overall looks good, but some comments that i would like an answer to.
it would also be cool if you can paste images (old vs new) highlighting changes.

2017-08-11 17:54 UTC, PatoBeltran commented on src/NuGet.Clients/NuGet.PackageManagement.UI/Xamls/PackageManagerControl.xaml.cs
> +            // AddedItems will have the item that gets selected
`e` should have two arrays `AddedItems` and `RemovedItems`. Each is supposed to have one element (the one is being selected and the one loosing selection). I'm not sure if this is the best way to do this or if it would be better to just assume the arrays always have an element and use the first element on each array.

2017-08-11 17:54 UTC, PatoBeltran commented on src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/PackageFeeds/MultiSourcePackageFeed.cs
> +        public bool IsOnlyLoadingFromNuGetOrg => !IsMultiSource && _sourceRepositories.First<SourceRepository>().ToString() == NUGET_ORG_SOURCE_NAME;
I don't know if this is the best way to decide if the feed is the one coming from nuget.org

2017-08-11 17:54 UTC, PatoBeltran commented on src/NuGet.Core/NuGet.Protocol/LegacyFeed/V2FeedPackageInfo.cs
> +            _prefixReserved = prefixReserved;
@rohit21agrawal This feature is not supposed to work with V2 but I needed to add this logic because of `IPackageSearchMetadata.cs`. Should I instead just hard-code `PrefixReserved` to always be `false` on V2?

2017-08-11 17:54 UTC, PatoBeltran commented on src/NuGet.Clients/NuGet.PackageManagement.UI/Models/PackageItemListViewModel.cs
> +        public ImageMoniker PrefixReservedIndicatorMoniker
I need to call `OnPropertyChanged()` on `set`, is there a way of achieving this without both fields?

2017-08-11 17:54 UTC, PatoBeltran commented on src/NuGet.Clients/NuGet.PackageManagement.UI/NuGet.PackageManagement.UI.csproj
> +    <Reference Include="Microsoft.VisualStudio.Imaging.Interop.14.0.DesignTime, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL">
Yes, according to the docs https://msdn.microsoft.com/en-us/library/mt628927.aspx

2017-08-11 17:54 UTC, PatoBeltran commented on src/NuGet.Clients/NuGet.PackageManagement.UI/Xamls/PackageItemControl.xaml
> +  xmlns:imaging="clr-namespace:Microsoft.VisualStudio.Imaging;assembly=Microsoft.VisualStudio.Imaging"
Yes, the docs define it and if I remove it `CripsImage` is not found and therefore the build fails.

2017-08-11 17:54 UTC, PatoBeltran commented on src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/PackageFeeds/PlainPackageFeedBase.cs
> +        public bool IsOnlyLoadingFromNuGetOrg => false;
The prefix reserved checkmark should only be shown when the feed is nuget.org, therefore I set this to false so it would default to not showing the checkmark in most feeds.

2017-08-11 17:54 UTC, PatoBeltran commented on src/NuGet.Clients/NuGet.Tools/NuGetTools.vsct
> +    <GuidSymbol name="PackageIconMonikers" value="{8F5EAE8F-9892-4CE2-826C-764BEDE6D2EC}">
The image service requires a guid be set for each manifest and an id for each image, to let visual studio map the images with the actual files. It doesn't matter if the values are hexadecimal or decimal, they just need to be congruent with whatever is set in the image manifest.

2017-08-11 17:54 UTC, PatoBeltran commented on src/NuGet.Clients/NuGet.PackageManagement.UI/Models/PackageItemListViewModel.cs
> +        public ImageMoniker PrefixReservedIndicatorMoniker
This used to be a dynamic property (based on item selection), the design has changed to static and I forgot to modify this. Thank you!

2017-08-11 17:54 UTC, PatoBeltran commented on src/NuGet.Clients/NuGet.PackageManagement.UI/Xamls/PrefixReservedIndicator.xaml
> +              <GeometryDrawing Brush="#FFF6F6F6" Geometry="F1M16,8C16,12.411 12.411,16 8,16 3.589,16 0,12.411 0,8 0,3.589 3.589,0 8,0 12.411,0 16,3.589 16,8" />
@diverdan92 provided the new XAML files for the icons.

2017-08-11 17:54 UTC, PatoBeltran commented on src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/PackageFeeds/MultiSourcePackageFeed.cs
> +        public bool IsOnlyLoadingFromNuGetOrg => !IsMultiSource && StringComparer.OrdinalIgnoreCase.Equals(_sourceRepositories.First<SourceRepository>().ToString(), NuGetConstants.FeedName);
The idea is that if the feed has only one source and that source is nuget.org then the variable should be true. That is why I first check `!IsMultiSource`, because that should mean that `_sourceRepositories` only has one element, therefore take that element and check if it's `nuget.org`

2017-08-11 17:54 UTC, PatoBeltran commented on src/NuGet.Clients/NuGet.VisualStudio.Client/NuGet.VisualStudio.Client.csproj
> +    </Content>
I was following [this](https://github.com/Microsoft/VSProjectSystem/blob/master/doc/scenario/provide_custom_icons_for_the_project_or_item_type.md) docs that mention adding it to the VSIX and also in the docs [here](https://msdn.microsoft.com/en-us/library/mt628927.aspx#Anchor_11) there's a reference to adding it to the VSIX in the faq.

2017-08-11 17:55 UTC, rohit21agrawal commented on src/NuGet.Core/NuGet.Protocol/LegacyFeed/V2FeedPackageInfo.cs
> +            _prefixReserved = prefixReserved;
yeah, hardcoding to false would be better. add a comment along with it.

2017-08-11 17:57 UTC, PatoBeltran commented on src/NuGet.Clients/NuGet.PackageManagement.UI/NuGet.PackageManagement.UI.csproj
> +    <Compile Include="Models\PackageIconMonikers.cs" />
Yes, according to the docs it's the same for VS 2015 and VS 2017

2017-08-11 18:47 UTC, PatoBeltran commented
@rohit21agrawal @jainaashish Addressed all comments. Are there any more changes needed?

2017-08-11 19:57 UTC, rohit21agrawal approved these changes

2017-08-11 22:41 UTC, jainaashish approved these changes
Looks good, nice job! 👏

2017-08-14 17:54 UTC, merged