[WIP] Add BuildTools willow package
NuGet/NuGet.Client pull request #1626
Opened 2017-08-08 18:50 UTC by alpaix

2017-08-09 19:42 UTC, rohit21agrawal requested changes

2017-08-09 19:42 UTC, rohit21agrawal commented on build/sign.proj
> +  <Import Project="$(MicroBuildDirectory)MicroBuild.Core.props"/>
nit: can you make the same change in loc.proj while you are at it?

2017-08-09 19:42 UTC, rohit21agrawal commented on setup/Microsoft.VisualStudio.NuGet.Core.vsmanproj
> +  <Import Project="$(MicroBuildDirectory)MicroBuild.Core.props" />
why are you including these here? this will cause localization/signing to run when building this project which we do separately.

2017-08-09 19:42 UTC, rohit21agrawal commented on src/NuGet.Clients/NuGet.VisualStudio.Client/NuGet.VisualStudio.Client.csproj
> +    <MSBuild Projects="@(SolutionProjectsWithoutVSIX)" Targets="GetLocalizedFilesForVsix" Properties="IsVsixBuild=true;&#xD;&#xA;                BuildProjectReferences=false;">
this looks really weird as a result of formatting, can you undo this?

2017-08-09 21:14 UTC, alpaix commented on setup/Microsoft.VisualStudio.NuGet.Core.vsmanproj
> +  <Import Project="$(MicroBuildDirectory)MicroBuild.Core.props" />
Needed for MicroBuild tasks and targets to produce manifest and related artifacts from swix project

2017-08-09 21:15 UTC, rohit21agrawal commented on setup/Microsoft.VisualStudio.NuGet.Core.vsmanproj
> +  <Import Project="$(MicroBuildDirectory)MicroBuild.Core.props" />
I don't get it, it was working until now, right?

2017-08-09 21:22 UTC, alpaix commented on setup/Microsoft.VisualStudio.NuGet.Core.vsmanproj
> +  <Import Project="$(MicroBuildDirectory)MicroBuild.Core.props" />
You're right. This is core project. Will remove.

2017-08-09 21:45 UTC, rohit21agrawal commented on setup/Microsoft.VisualStudio.NuGet.Core.vsmanproj
> +  <Import Project="$(MicroBuildDirectory)MicroBuild.Core.targets"/>
need to remove these targets too

2017-08-09 21:50 UTC, alpaix commented on setup/Microsoft.VisualStudio.NuGet.Core.vsmanproj
> +  <Import Project="$(MicroBuildDirectory)MicroBuild.Core.targets"/>
targets have been there before. Are you sure?

2017-08-09 21:55 UTC, rohit21agrawal commented on setup/Microsoft.VisualStudio.NuGet.Core.vsmanproj
> +  <Import Project="$(MicroBuildDirectory)MicroBuild.Core.targets"/>
sorry, my bad.

2017-08-09 21:55 UTC, rohit21agrawal approved these changes

2017-08-10 17:01 UTC, merged

2017-08-10 17:02 UTC, rohit21agrawal commented
have you made the corresponding changes to the official build definition?

2017-08-10 17:03 UTC, alpaix commented
Not yet. Will let it build for the first time without changes.

2017-10-24 13:12 UTC, UncleFirefox commented
Will this be included into the VS Build tools anytime soon? Thanks!

2017-10-24 16:46 UTC, nkolev92 commented
@UncleFirefox 15.4 and later Build Tools SKU contains the NuGet  artifacts. 

What problems are you facing? Can you please open another issue with more details? Thanks.

2017-10-25 07:07 UTC, UncleFirefox commented
Hi, that's strange. Having this version of the build tools:

![image](https://user-images.githubusercontent.com/3224718/31984790-06763458-b963-11e7-9bfd-d807fcdbd825.png)

When I issue msbuild

```
 `&'C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MS
Build.exe' /t:restore
Microsoft (R) Build Engine version 15.4.8.50001 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.
````

I get the following error: 
`error MSB4057: The target "restore" does not exist in the project.`

Which can be fixed copying targets coming from the whole Visual Studio 2017 installation but that was supposed to be fixed. Am I misssing something?

2017-10-25 07:26 UTC, nkolev92 commented
@UncleFirefox 

Please open another issue for that, and provide some more details, based on the template [here](https://github.com/nuget/home/issues/new)

Can you try repairing the Build Tools SKU and trying to restore again? 

If possible maybe upload the project file or steps to a repro?

Thanks.

2017-10-25 07:41 UTC, alpaix commented
@UncleFirefox Could you please verify what workloads are installed? NuGet component requires either .NET Core or ASP.NET workloads.

2017-10-25 07:50 UTC, UncleFirefox commented
Oh, so build tools does not include it by default you need to select it in the workloads!
![image](https://user-images.githubusercontent.com/3224718/31986727-d557ca1a-b969-11e7-9cbe-51ec6f2857b2.png)