[WIP] the great nuget.exe install clean up
NuGet/NuGet.Client pull request #1634
Opened 2017-08-10 08:45 UTC by emgarten

* Allow upgrading packages with -ExcludeVersion
* Fix for NoCache, the meaning of this has changed and 4.x is using it incorrectly compared to 2.x

2017-08-10 17:20 UTC, mishra14 commented
@emgarten not so great if the build fails!! :P

2017-08-10 17:52 UTC, nkolev92 commented
@mishra14 I assume that's why it's a WIP :P

2017-08-11 08:37 UTC, emgarten commented
Tests are passing on teamcity

2017-08-11 21:54 UTC, zhili1208 commented on src/NuGet.Clients/NuGet.CommandLine/Commands/InstallCommand.cs
> +                return PerformV2RestoreAsync(configFilePath, installPath);
why not await here?

2017-08-11 21:54 UTC, zhili1208 commented on src/NuGet.Clients/NuGet.CommandLine/Commands/InstallCommand.cs
> +                return InstallPackageAsync(packageId, version, installPath);
same

2017-08-11 22:02 UTC, zhili1208 commented on src/NuGet.Clients/NuGet.CommandLine/Commands/DownloadCommandBase.cs
> +        /// If true the global packages folder will be added as a source.
If true the global packages folder will not be added as a source

2017-08-11 22:05 UTC, zhili1208 commented on src/NuGet.Clients/NuGet.CommandLine/Commands/DownloadCommandBase.cs
> +            if (!NoCache && !ExcludeCacheAsSource)
Is "NoCache" also used in other place? why can't just use "NoCache" to exclude cache

2017-08-11 22:08 UTC, zhili1208 commented on src/NuGet.Clients/NuGet.CommandLine/Common/InstallCommandProject.cs
> +                // Package does not exit
exist

2017-08-11 22:19 UTC, emgarten commented on src/NuGet.Clients/NuGet.CommandLine/Commands/DownloadCommandBase.cs
> +            if (!NoCache && !ExcludeCacheAsSource)
ExcludeCacheAsSource is a subset of NoCache

2017-08-11 22:19 UTC, emgarten commented on src/NuGet.Clients/NuGet.CommandLine/Commands/InstallCommand.cs
> +                return PerformV2RestoreAsync(configFilePath, installPath);
it returns the task and is awaited higher up

2017-08-11 22:20 UTC, emgarten commented on src/NuGet.Clients/NuGet.CommandLine/Commands/InstallCommand.cs
> +                return InstallPackageAsync(packageId, version, installPath);
also returning the task

2017-08-11 23:03 UTC, mishra14 requested changes
how will people realize how ExcludeCacheAsSource work?

2017-08-11 23:03 UTC, mishra14 commented on src/NuGet.Clients/NuGet.CommandLine/Commands/InstallCommand.cs
> +                if (!result.Restored || failedEvents.Count > 0)
👍

2017-08-11 23:03 UTC, mishra14 commented on src/NuGet.Clients/NuGet.CommandLine/Commands/InstallCommand.cs
> +                ExcludeCacheAsSource = true;
this seems a bit arbitrary. how will people realize what is the resolution logic?

2017-08-11 23:03 UTC, mishra14 commented on src/NuGet.Clients/NuGet.CommandLine/Commands/RestoreCommand.cs
> +                    collectorLogger.Errors.Concat(failedEvents.Select(e => new RestoreLogMessage(LogLevel.Error, NuGetLogCode.Undefined, e.Exception.Message))));
👍

2017-08-11 23:03 UTC, mishra14 commented on src/NuGet.Core/NuGet.PackageManagement/Projects/FolderNuGetProject.cs
> +            if (targetFramework == null)
nit: simplify these just as `root` and `packagePathResolver `

2017-08-11 23:11 UTC, mishra14 commented on src/NuGet.Clients/NuGet.CommandLine/Commands/InstallCommand.cs
> +                ExcludeCacheAsSource = true;
Discussed offline. This is fine as we set ExcludeCacheAsSource only if we see floating versions in the dependency list.

2017-08-11 23:11 UTC, mishra14 approved these changes
Discussed offline. Looks good

2017-08-12 02:50 UTC, merged