In Legacy Package Ref case, use only per tfm dependencies
NuGet/NuGet.Client pull request #1652
Opened 2017-08-15 23:08 UTC by nkolev92

This PR partially addresses https://github.com/NuGet/Home/issues/5444
To fully fix the above issue, I will create another PR which specifically targets the way we calculate the hash for no-op comparison.

In the case of Legacy Package Reference our code has been used inconsistently where in most cases we used top level dependencies, while we built the package spec with both top level/ per tfm in VS. 
In the exe only top level dependencies were used. 

Now I have changed all of those to use Per TFM dependencies only. This will make the dg specs created among VS and exe "almost" the same.

2017-08-16 18:17 UTC, rohit21agrawal commented on src/NuGet.Core/NuGet.Build.Tasks.Pack/PackTaskLogic.cs
> -                // First, add each of the generic package dependencies to the framework-specific list.
investigate if this is really necessary.

2017-08-16 18:20 UTC, rohit21agrawal commented on src/NuGet.Core/NuGet.ProjectModel/PackageSpecOperations.cs
> +// Copyright (c) .NET Foundation. All rights reserved.
revert this one.

2017-08-16 18:20 UTC, rohit21agrawal commented on src/NuGet.Core/NuGet.ProjectModel/PackageSpecOperations.cs
> -        public static void AddOrUpdateDependency(PackageSpec spec, PackageDependency dependency)
we are removing a public api that has potential to break sdk/cli when they update.
i would prefer if you added an overload and make this method call the overloaded method.

2017-08-16 18:22 UTC, rohit21agrawal commented on src/NuGet.Core/NuGet.Build.Tasks/NuGet.targets
> +    <ItemGroup Condition=" '$(RestoreProjectStyle)' == 'PackageReference' AND '$(RestoreProjectStyle)' == 'PackageReference' ">
why do you need the same condition twice?

2017-08-16 18:36 UTC, nkolev92 commented on src/NuGet.Core/NuGet.Build.Tasks/NuGet.targets
> +    <ItemGroup Condition=" '$(RestoreProjectStyle)' == 'PackageReference' AND '$(RestoreProjectStyle)' == 'PackageReference' ">
We don't lol.
Nice catch. 
I misread it completely.

2017-08-16 22:33 UTC, nkolev92 commented on src/NuGet.Core/NuGet.ProjectModel/PackageSpecOperations.cs
> -        public static void AddOrUpdateDependency(PackageSpec spec, PackageDependency dependency)
I checked that, and it's not used. 
I'd normally prefer to cleanup APIs that aren't super important for other users, but I'll revert this.

2017-08-16 22:36 UTC, nkolev92 commented
🔔 @rohit21agrawal @jainaashish @mishra14 @zhili1208 @PatoBeltran

2017-08-16 22:41 UTC, rohit21agrawal commented on src/NuGet.Core/NuGet.Build.Tasks/NuGet.targets
> -      <_RestoreTargetFrameworkItemsHasValues Condition=" '$(TargetFramework)' != '' OR '$(TargetFrameworks)' != '' ">true</_RestoreTargetFrameworkItemsHasValues>
this isn't used anywhere?

2017-08-16 22:41 UTC, rohit21agrawal approved these changes
just one minor question, otherwise looks good!

2017-08-16 22:58 UTC, nkolev92 commented on src/NuGet.Core/NuGet.Build.Tasks/NuGet.targets
> -      <_RestoreTargetFrameworkItemsHasValues Condition=" '$(TargetFramework)' != '' OR '$(TargetFrameworks)' != '' ">true</_RestoreTargetFrameworkItemsHasValues>
It's just a local one used in the below item group as a condition. It was used to restrict setting the target frameworks to net core only. 
By changing it now the target frameworks are set in the legacy case as well.

2017-08-17 00:43 UTC, jainaashish commented on src/NuGet.Core/NuGet.PackageManagement/NuGetPackageManager.cs
> +                    if (updatedPackageSpec.RestoreMetadata.ProjectStyle == ProjectStyle.ProjectJson)
Would it make more sense if you check for `PackageReference` and pass tfms. And else case use the old call. That will keep the existing behavior and only change PR

2017-08-17 00:44 UTC, jainaashish requested changes
Small correction to be consistent with existing behavior. Otherwise looks good.

2017-08-17 02:17 UTC, nkolev92 commented
@jainaashish :bell:

2017-08-17 17:17 UTC, jainaashish approved these changes
LGTM

2017-08-18 20:18 UTC, nkolev92 commented
This PR currently has some failing EndToEnd tests due to the following issues: 
https://github.com/NuGet/Home/issues/5778 and https://github.com/NuGet/Home/issues/5777 
Once the templates have been fixed 5778, this should be safe to merge in. 

Depending on the decision in https://github.com/NuGet/Home/issues/5777 there might need to improvements in this, but that's a separate issue.

2017-09-07 18:50 UTC, emgarten requested changes
Make this change in MSBuildRestoreUtility.AddPackageReferences

2017-09-07 22:06 UTC, nkolev92 commented
@emgarten 🔔

2017-09-07 23:09 UTC, emgarten commented on src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/Projects/LegacyPackageReferenceProject.cs
>                  FilePath = _projectFullPath,
Where do the package dependencies get populated now?

2017-09-07 23:11 UTC, emgarten commented on src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/Projects/LegacyPackageReferenceProject.cs
>                  FilePath = _projectFullPath,
I see :smile:

2017-09-07 23:11 UTC, emgarten approved these changes
🚀

2017-09-08 00:14 UTC, merged