Dev zhi fixpack uwp
NuGet/NuGet.Client pull request #1657
Opened 2017-08-16 21:01 UTC by zhili1208

https://github.com/NuGet/Home/issues/5379

pack layout files for UWP

2017-08-16 21:03 UTC, rohit21agrawal commented
This will fail on every project that does not define that target. You need to ask the UWP project team to add these files to BuiltProjectOutptGroup target, this is the wrong way to go.

2017-08-16 21:08 UTC, rohit21agrawal requested changes
get an email thread going with UWP team on adding these layout files to a output group that pack supports.

2017-08-16 21:09 UTC, rohit21agrawal commented on src/NuGet.Core/NuGet.Build.Tasks.Pack/Pack.targets
> +                            @(_LayoutFile)"/>
we shouldn't take dependencies on items that start with _ as they are meant to be internal.

2017-08-21 22:30 UTC, commonsensesoftware commented
@rohit21agrawal UWP is not open source to my knowledge. What is the _right_ way to engage with the team. It's not clear who to track down, even internally.

2017-08-22 16:47 UTC, rohit21agrawal commented
@commonsensesoftware PM me and i'll send you some contacts.

2017-11-10 23:55 UTC, emgarten commented
Please re-open if this is still active.

2017-11-10 23:55 UTC, closed without merging