Fixed IVsPackageInstallerService APIs to return correct install path
NuGet/NuGet.Client pull request #1666
Opened 2017-08-22 01:50 UTC by jainaashish

Fixes internal bug# 482522

Issue is, we started supporting `RestorePackagesPath` in VS to have custom packages path for `PackageReference` based projects but we never updated `IVsPackageInstallerService` APIs to start consuming this property to return correct install path for the packages.

@rrelyea

2017-08-22 23:57 UTC, emgarten approved these changes

2017-08-22 23:57 UTC, emgarten commented on src/NuGet.Clients/NuGet.VisualStudio.Implementation/Extensibility/VsPackageInstallerServices.cs
> +            var packageSpec = (await project.GetPackageSpecsAsync(context)).First();
this should be fine, but you should take the first spec that is of type PackageReference and not a tool spec. 
https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.ProjectModel/ProjectStyle.cs#L21

2017-08-22 23:57 UTC, emgarten commented on src/NuGet.Clients/NuGet.VisualStudio.Implementation/Extensibility/VsPackageInstallerServices.cs
> +            return new FallbackPackagePathResolver(packagesPath, SettingsUtility.GetFallbackPackageFolders(_settings));
This needs to be VSRestoreSettingsUtilities.GetFallbackFolders

SettingsUtility will have the same issue for fallback folders as it did for the global packages folder.

2017-08-23 02:35 UTC, emgarten requested changes
this needs to read fallback folders in the same way

2017-08-23 17:54 UTC, jainaashish commented on src/NuGet.Clients/NuGet.VisualStudio.Implementation/Extensibility/VsPackageInstallerServices.cs
> +            return new FallbackPackagePathResolver(packagesPath, SettingsUtility.GetFallbackPackageFolders(_settings));
yeah, makes sense!

2017-08-23 18:04 UTC, emgarten approved these changes
LGTM 🚀

2017-08-23 18:09 UTC, merged