throw error for PC and PJ when projectRef is not resolved
NuGet/NuGet.Client pull request #1667
Opened 2017-08-22 23:56 UTC by zhili1208

https://github.com/NuGet/Home/issues/5777

For netcore project and package reference, NuGet always pass project reference path to restore, let restore throw error.

But Project.json and packages.config will skip unresolved project reference, let restore succeed, but fail during build.

the fix is let PJ and PC also throw during restore if project reference is not resolved.

we should have test infrastructure for error/warning code, filed a bug: https://github.com/NuGet/Home/issues/5792

2017-08-23 00:13 UTC, emgarten commented
Check where the Resolved property was originally added. I know this was added for a DTE related reason. There could be different behavior for every project system around this.

2017-08-23 17:39 UTC, zhili1208 commented
the Resolved is added before NuGet.Client repo created, so can't find the original commit, searched all bugs, didn't find anything

2017-08-23 18:26 UTC, jainaashish requested changes
Please add test for this scenario. Adding whole infra for warnings n errors will happen when it happens, but that should not stop us adding tests for scenarios which can be easily added.

2017-08-23 21:25 UTC, emgarten commented
I'm leery of taking this without finding the original issue. Other things may have changed around this that fix the issue, but I recall a lot of pitfalls around this check.

2017-08-23 21:26 UTC, emgarten commented
> Resolved is added before NuGet.Client repo create

That doesn't seem right, but if so the original git history was copied from the other repos.

2017-08-23 22:30 UTC, zhili1208 commented
this change is introduced by https://github.com/NuGet/NuGet.Client/commit/9880fd22f0c0c1c29405daf280810bb8cab24769 which fixed https://github.com/NuGet/Home/issues/1110,

Here is the PR: https://github.com/NuGetArchive/NuGet.VisualStudioExtension/pull/54

the fix is about native projects where the reference does not exist on disk DTE throws a generic exception.

the "try catch" is the real fix,  Removing Resovled Check doesn't break this

2017-09-06 21:11 UTC, nkolev92 reviewed
Let's discuss this together with @emgarten and @jainaashish at the least. 
I'd personally prefer the other fix, where we let msbuild deal with it.

2017-09-06 21:11 UTC, nkolev92 commented on test/EndToEnd/tests/BuildIntegratedTest.ps1
> +    $projectT = $projectT | Select-Object UniqueName, ProjectName, FullName
This line is not needed.

2017-09-06 21:11 UTC, nkolev92 commented on test/EndToEnd/nuget.assert.ps1
> +        if ($log.Code.ToUpperInvariant().Equals($errorCode.ToUpperInvariant()))
This would fail, code is an enum, so replace this with ToString()

2017-09-06 21:14 UTC, nkolev92 commented on test/EndToEnd/tests/BuildIntegratedTest.ps1
>      #Assert
I would also suggest adding an LSL test for the same scenario. 
I did some testing myself, so I used the following test. I would add it to LightweightSolutionLoadTest.ps1

```
function Test-DeferredBuildIntegratedGetIncompatibleError {
    [SkipTestForVS14()]
      
    $projectR = New-Project Net45BuildIntegratedClassLibrary #project.json
    $projectT = New-Project PackageReferenceClassLibrary #this is a net46 library, incompatible

    $projectR | Add-ProjectReference -ProjectTo $projectT

    Clean-Solution

    $projectR = $projectR | Select-Object UniqueName, ProjectName, FullName

    Enable-LightweightSolutionLoad -Reload

    # Act (Restore)
    Build-Solution

    Assert-True ($projectR | Test-Project -IsDeferred) -Message 'Test project should stay in deferred mode'
    
    Assert-ProjectJsonLockFileErrorCode $projectR NU1201
}
```

2017-09-07 18:16 UTC, zhili1208 commented
after discussion, we decide to close it as won't fix

2017-09-07 18:16 UTC, closed without merging