Switching NuGet.Build.Tasks.Pack packing to nuspec
NuGet/NuGet.Client pull request #1888
Opened 2017-12-20 21:06 UTC by mishra14

As part of https://github.com/NuGet/NuGet.Client/pull/1772 and https://github.com/NuGet/NuGet.Client/pull/1778 @nkolev92  switched the packing of `NuGet.Build.Tasks.Pack` to using the csproj file instead of a nuspec file.

This creates an issue that surfaced while working on https://github.com/dotnet/sdk/pull/1829. Because of using csproj file the generated package gets package dependencies, which is not accurate as the pack dll is ILmerged.

**nuspec of last inserted package -** 

```
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2011/10/nuspec.xsd">
  <metadata>
    <id>NuGet.Build.Tasks.Pack</id>
    <version>4.5.0-preview2-4529</version>
    <authors>Microsoft</authors>
    <owners>Microsoft</owners>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>NuGet pack for dotnet CLI</description>
    <serviceable>true</serviceable>
  </metadata>
</package>
```

**nuspec of the latest package -** 

```
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
  <metadata>
    <id>NuGet.Build.Tasks.Pack</id>
    <version>4.6.0-preview3-4749</version>
    <authors>Microsoft</authors>
    <owners>Microsoft</owners>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <licenseUrl>https://raw.githubusercontent.com/NuGet/NuGet.Client/dev/LICENSE.txt</licenseUrl>
    <description>NuGet pack for dotnet CLI</description>
    <copyright>Microsoft Corporation. All rights reserved.</copyright>
    <tags>nuget</tags>
    <serviceable>true</serviceable>
    <repository type="git" url="https://github.com/NuGet/NuGet.Client" />
    <dependencies>
      <group targetFramework=".NETFramework4.6">
        <dependency id="NuGet.Commands" version="4.6.0-preview3-4749" exclude="Build,Analyzers" />
      </group>
      <group targetFramework=".NETStandard1.3">
        <dependency id="NuGet.Commands" version="4.6.0-preview3-4749" exclude="Build,Analyzers" />
        <dependency id="NETStandard.Library" version="1.6.0" exclude="Build,Analyzers" />
        <dependency id="Microsoft.Build.Framework" version="15.1.1012" exclude="Build,Analyzers" />
        <dependency id="Microsoft.Build.Tasks.Core" version="15.1.1012" exclude="Build,Analyzers" />
        <dependency id="Microsoft.Build.Utilities.Core" version="15.1.1012" exclude="Build,Analyzers" />
      </group>
    </dependencies>
    <frameworkAssemblies>
      <frameworkAssembly assemblyName="Microsoft.Build.Framework" targetFramework=".NETFramework4.6" />
      <frameworkAssembly assemblyName="Microsoft.Build.Utilities.v4.0" targetFramework=".NETFramework4.6" />
    </frameworkAssemblies>
  </metadata>
</package>
```

This change reverts the packing of the project to using a nuspec file. 
**This will need to be cherry-picked onto the `release-4.6.0-preview2` branch for an updated insertion into cli/sdk**. 
VS insertion is fine as it does not consume this package.

2017-12-20 21:08 UTC, nkolev92 requested changes
This change would break build from source...part of the patches changes.

2017-12-20 21:25 UTC, nkolev92 commented
Discussed offline...we need to rework this to include it 2 csproj...on IsBuildOnlyXPLATProjects==true we need to pack the non-ILMerged dependencies, and only for netstandard 1.3...the full framework build should be the same as it is now. 2

2017-12-20 22:28 UTC, rohit21agrawal commented on src/NuGet.Core/NuGet.Build.Tasks.Pack/NuGet.Build.Tasks.Pack.XPlat.nuspec
> +    <file src="netstandard1.3\*.dll" target="CoreCLR\" />
no localized resources for this?

2017-12-20 22:29 UTC, rohit21agrawal commented on src/NuGet.Core/NuGet.Build.Tasks.Pack/NuGet.Build.Tasks.Pack.XPlat.nuspec
> +    <file src="netstandard1.3\NuGet.Build.Tasks.Pack.targets" target="buildCrossTargeting\NuGet.Build.Tasks.Pack.targets" />
you also need tehe same targets file in build folder

2017-12-20 22:36 UTC, rohit21agrawal commented on src/NuGet.Core/NuGet.Build.Tasks.Pack/NuGet.Build.Tasks.Pack.csproj
> +  <PropertyGroup Condition="'$(IsBuildOnlyXPLATProjects)' != 'true'">
nit: use the same property group for both cases, and have the condition only on the NuspecFile property.

2017-12-20 22:36 UTC, rohit21agrawal approved these changes
verify manually that the nupkg looks good on the CI

2017-12-20 23:42 UTC, nkolev92 commented on src/NuGet.Core/NuGet.Build.Tasks.Pack/NuGet.Build.Tasks.Pack.XPlat.nuspec
> +    <file src="netstandard1.3\*.dll" target="CoreCLR\" />
They don't localize currently.

2017-12-20 23:43 UTC, nkolev92 approved these changes
LGTM

2017-12-20 23:45 UTC, merged

2017-12-22 14:20 UTC, onovotny commented
I hope this is a temporary change until the pack targets are updated to address this scenario? This is a good dogfood example. If you need a nuspec for something, that clearly indicates there's a functional gap somewhere.

2017-12-22 17:43 UTC, mishra14 commented
@onovotny agreed. As discussed with @rohit21agrawal, he is considering adding a solution to `pack`.