try powershell task on linux
NuGet/NuGet.Client pull request #1931
Opened 2018-01-09 19:38 UTC by rohit21agrawal

Fixes: https://github.com/NuGet/Home/issues/5912

Adds help keyword to redirect to the right docs page when F1 is pressed for a control.

Doc side PR : https://github.com/NuGet/docs.microsoft.com-nuget/pull/642

2018-01-09 19:41 UTC, emgarten requested changes

2018-01-09 19:41 UTC, emgarten commented on src/NuGet.Clients/NuGet.Tools/NuGetPackage.cs
> +                if(windowFrame != null)
format the doc

2018-01-09 19:41 UTC, emgarten commented on src/NuGet.Clients/NuGet.Tools/NuGetPackage.cs
> +                    }
Can you make this into a helper method in visualstudio common?

2018-01-09 19:52 UTC, rohit21agrawal commented
@emgarten  done

2018-01-09 20:04 UTC, emgarten approved these changes
Glad to see f1 support fixed! 🚀

2018-01-09 20:04 UTC, emgarten commented on src/NuGet.Clients/NuGet.Console/PowerConsoleToolWindow.cs
> +                if (windowFrame != null)
remove duplicate check 😄

2018-01-09 20:06 UTC, jainaashish commented on src/NuGet.Clients/NuGet.Console/PowerConsoleToolWindow.cs
> +                    WindowFrameHelper.AddF1HelpKeyword(windowFrame, keywordValue: "VS.NuGet.PackageManager.Console");
nit: create constants for these hard core strings.

2018-01-09 20:07 UTC, jainaashish approved these changes
LGTM

2018-01-09 20:22 UTC, mishra14 approved these changes

2018-01-09 20:50 UTC, merged

2018-01-10 20:25 UTC, Newrad0603 commented
LGTM

2018-01-10 21:03 UTC, Huy-Nguyen-MSFT reviewed
Looks good.