changes for verify reposign during package extraction
NuGet/NuGet.Client pull request #2068
Opened 2018-03-05 18:15 UTC by zhili1208

1. protocol change
  talk to server and fetch repo sign information from server
2. PackageReader API change.
 added API for reading repo sign information in PackageReader
3. PackageExtractor change,
Removed API which accepts package stream.

Passing package stream in different layers is bad for package sign, we are losing all information about where the stream comes from, is it already verified...etc. In this changes, we should always pass packageReader in different layers.

2018-03-09 17:07 UTC, jainaashish commented on src/NuGet.Core/NuGet.PackageManagement/NuGetPackageManager.cs
> +                            var packageStream = File.OpenRead(packagePath);
who is closing this stream?

2018-03-09 17:08 UTC, jainaashish commented on src/NuGet.Core/NuGet.PackageManagement/NuGetPackageManager.cs
> +                                File.OpenRead(packagePath), new PackageArchiveReader(packageStream, leaveStreamOpen: true, packageSignatureVerified: true), nuGetProjectAction.SourceRepository?.Packag
why are you opening multiple steams for the same file at the same time?

2018-03-09 17:14 UTC, jainaashish commented on src/NuGet.Core/NuGet.Packaging.Core/FingerPrintInfo.cs
> +        private IDictionary<string, string> _keyValuePairs;
nit: readonly

2018-03-09 17:20 UTC, jainaashish commented on src/NuGet.Core/NuGet.Packaging/PackageArchiveReader.cs
> +                bool packageSignatureVerified = false,
why package reader is taking `packageSignatureVerified` field? isn't this reader job to figure out that by going through package content?

2018-03-09 17:27 UTC, jainaashish commented on src/NuGet.Core/NuGet.Packaging/PackageArchiveReader.cs
> +        /// <param name="requiredRepoSign">Set to true if the package is needed to be repository signed.</param>
nit: update param lists

2018-03-09 17:30 UTC, jainaashish commented on src/NuGet.Core/NuGet.Packaging/PackageArchiveReader.cs
> +            RepositoryCertInfos = repositoryCertInfos;
where and how are you using these fields from package reader? shouldn't these only be with extractor?

2018-03-09 17:36 UTC, jainaashish commented on src/NuGet.Core/NuGet.Packaging/PackageExtractor.cs
> +            if (packageExtractionContext.SignedPackageVerifier != null && !signedPackageReader.PackageSignatureVerified)
in what cases signature will already be verified at the time of extraction?

2018-03-09 17:37 UTC, jainaashish commented on src/NuGet.Core/NuGet.Packaging/PackageFolderReader.cs
> +        public override bool PackageSignatureVerified => true;
why this default to true?

2018-03-09 17:38 UTC, jainaashish commented on src/NuGet.Core/NuGet.Packaging/PackageReaderBase.cs
> +            FrameworkProvider = frameworkProvider ?? throw new ArgumentNullException(nameof(frameworkProvider));
nit: use `Assumes.Present` that will be more simplified

2018-03-09 17:44 UTC, jainaashish commented on src/NuGet.Core/NuGet.Protocol/DownloadResourceResult.cs
> +            _stream.Seek(0, SeekOrigin.Begin);
👍

2018-03-09 18:01 UTC, jainaashish commented on src/NuGet.Core/NuGet.Protocol/RemoteRepositories/HttpFileSystemBasedFindPackageByIdResource.cs
> +            RepositorySignatureResource = repositorySignatureResource;
will repositorySignatureResource always be present for all V3 resources?

2018-03-09 18:03 UTC, jainaashish commented on src/NuGet.Core/NuGet.Protocol/Resources/RepositorySignatureResource.cs
> +        public bool AllRepositorySigned { get; }
what is the field for?

2018-03-09 18:03 UTC, jainaashish commented on src/NuGet.Core/NuGet.Protocol/Strings.resx
> +    <value>Unbale to parse {0} information from {1}. </value>
define comment

2018-03-09 18:28 UTC, dtivel commented on src/NuGet.Core/NuGet.Packaging.Core/FingerPrintInfo.cs
> +    public class FingerPrintInfos
`FingerprintInfos`  `P` should not be capitalized.  "Fingerprint" is a single word.

Update file name too:

    git mv -f FingerPrintInfo.cs FingerprintInfo.cs

2018-03-09 18:28 UTC, dtivel commented on src/NuGet.Core/NuGet.Packaging.Core/FingerPrintInfo.cs
> +            _keyValuePairs = fingerPrints;
`fingerprints`

Also, check that `fingerprints` is not `null`.

2018-03-09 18:28 UTC, dtivel commented on src/NuGet.Core/NuGet.Protocol/Converters/FingerPrintsConverter.cs
> +    public class FingerPrintsConverter : JsonConverter
`FingerprintConverter`

Update file name too.

2018-03-09 18:28 UTC, dtivel commented on src/NuGet.Core/NuGet.Protocol/Converters/FingerPrintsConverter.cs
> +            foreach (var fingerPrint in v)
`fingerprint`

2018-03-09 18:28 UTC, dtivel commented on src/NuGet.Core/NuGet.Protocol/DownloadResourceResult.cs
> +        public DownloadResourceResult(Stream stream, PackageReaderBase packageReader, string source)
Update XML doc comments.

2018-03-09 18:28 UTC, dtivel commented on src/NuGet.Core/NuGet.Protocol/DownloadResourceResult.cs
> +            _stream.Seek(0, SeekOrigin.Begin);
Why did you add this statement?

2018-03-09 18:28 UTC, dtivel commented on src/NuGet.Core/NuGet.Protocol/Strings.resx
> +    <value>Unbale to parse {0} information from {1}. </value>
`Unbale` => `Unable`.

2018-03-09 18:28 UTC, dtivel commented on src/NuGet.Core/NuGet.Protocol/Strings.resx
> +  <data name="Log_FailedToParseRepoSigneInfor" xml:space="preserve">
`Log_FailedToParseRepoSigneInfor` => `Log_FailedToParseRepoSignerInfo`

2018-03-09 18:57 UTC, jainaashish requested changes
As discussed offline, we need to have a separate discussion for package reader changes. So create 2 separate PRs for protocol changes and reader changes.

2018-03-09 19:58 UTC, zhili1208 commented
@dtivel @jainaashish The protocol change PR is https://github.com/NuGet/NuGet.Client/pull/2083, please review it first, I have two other PR depends on it, will send after the PR merged

2018-03-13 17:25 UTC, zhili1208 commented
we decide to pass source to PackageExtractor, all those changes in this PR are not needed any more, close it.

2018-03-13 17:25 UTC, closed without merging