Updating localization validator to v2.0.0
NuGet/NuGet.Client pull request #2193
Opened 2018-04-25 18:55 UTC by mishra14

## Fix
Details: Updating the loc validation tool. The tool has been updated in  2 aspects - 

1. Add additional validation step to assert that NuGet dlls in the vsix have all the necessary localized resource dlls in known paths. This will prevent future cases of issue fixed by https://github.com/NuGet/NuGet.Client/commit/1d3aa71b4a437456feb87fb7282c32edb9d882f5
2. Write output files in json format to make them machine parseable

## Testing/Validation
Validation done:  Running validation tool in a separate private branch's [build](https://devdiv.visualstudio.com/DevDiv/NuGet/_build/index?buildId=1628975)

2018-04-25 18:56 UTC, nkolev92 commented on scripts/cibuild/BuildValidator.ps1
> +    # return the exit code from the validator
when does this run again?
Would it prevent the tests from running? And if yes, which ones?

2018-04-25 18:56 UTC, nkolev92 approved these changes

2018-04-25 18:57 UTC, mishra14 commented on scripts/cibuild/BuildValidator.ps1
> +    # return the exit code from the validator
this runs in the unit build step for non rtm build. This should only block tests that use build artifacts.

2018-04-25 18:59 UTC, nkolev92 commented on scripts/cibuild/BuildValidator.ps1
> +    # return the exit code from the validator
ok. 
So it's basically a change that could introduce more failures, but probably for the right reason. 

We need to watch out that it doesn't get too noisy.

2018-04-25 19:03 UTC, rohit21agrawal requested changes
@mishra14 given that you are just updating the change in the version of the validator, the actual validation changes are a black box to us. I would suggest that you add the validator code to the nuget repository, create a PR for your changes, and once those are approved , only then merge this change.

2018-04-30 18:48 UTC, mishra14 commented
@rohit21agrawal 🔔

2018-04-30 19:15 UTC, rohit21agrawal approved these changes

2018-04-30 19:57 UTC, merged