Fix suffix for --no-service-endpoint option description
NuGet/NuGet.Client pull request #2273
Opened 2018-06-01 19:17 UTC by mairaw

Fixing suffix used for --no-service-endpoint option description (see https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Protocol/Resources/PackageUpdateResource.cs#L27 for the correct one)

Also removed the redundant part
![image](https://user-images.githubusercontent.com/12971179/40859173-b2e37604-6595-11e8-8a57-2f08d1286228.png)

2018-06-04 18:18 UTC, mishra14 approved these changes

2018-06-04 18:19 UTC, nkolev92 commented
Thanks for fixing this @mairaw 

However, with resx files, we need to make sure that the designer.cs file has changed as well. 
Look at [this](https://github.com/NuGet/NuGet.Client/commit/96b3bf30b2efcf68b808142169d375474db6e88f#diff-387226381c1a6ecf14f6757fb411df63) for example.

The best way to do this, is to edit the resx file directly from Visual Studio.

2018-06-04 18:22 UTC, mishra14 requested changes
Please generate the Designer.cs file. You can load the solution into VS and then right click on the resx file and click on Run Custom Tool to ensure it.

2018-06-04 21:36 UTC, rohit21agrawal approved these changes

2018-10-03 19:27 UTC, nkolev92 commented
Closing in favor of https://github.com/NuGet/NuGet.Client/pull/2453.

2018-10-03 19:27 UTC, closed without merging