Update the discovery of built in plugins
NuGet/NuGet.Client pull request #2283
Opened 2018-06-07 04:55 UTC by nkolev92

## Bug
Fixes: https://github.com/NuGet/Home/issues/6704
Regression: No  
If Regression then when did it last work:   
If Regression then how are we preventing it in future:   

## Fix
Details: 
Last part of the discovery of plugins for VS and SDK.  
Also adding the plugins as a fallback in Visual Studio. 

## Testing/Validation
Tests Added: Yes  
Reason for not adding tests:  
Validation done: Tests, manual

2018-06-07 23:14 UTC, mishra14 requested changes

2018-06-07 23:14 UTC, mishra14 commented on src/NuGet.Core/NuGet.Protocol/Plugins/PluginDiscoveryUtility.cs
> +        /// <param name="nugetAssemblyPath">The path to a NuGet assembly in CommonExtensions\NuGet</param>
Add: `Needs to be a valid path. file:// not supported.`

2018-06-07 23:14 UTC, mishra14 commented on src/NuGet.Core/NuGet.Protocol/Plugins/PluginDiscoveryUtility.cs
> +        /// Given Visual Studio 2017 MSBuild.exe path, return the NuGet plugins directory which is in CommonExtensions/NuGetPluginsDirectory
`CommonExtensions/NuGetPlugins`

2018-06-07 23:14 UTC, mishra14 commented on src/NuGet.Core/NuGet.Protocol/Plugins/PluginDiscoveryUtility.cs
> +                    Path.Combine(parentDirectory, parentDirectory, parentDirectory, "Common7", "CommonExtensions", "Microsoft", "NuGet", NuGetPluginsDirectory)
are you missing "IDE" here?

`C:\Program Files (x86)\Microsoft Visual Studio\2017DogFood\Enterprise\Common7\IDE\CommonExtensions\Microsoft\NuGet`

2018-06-07 23:47 UTC, nkolev92 commented
🔔 @mishra14

2018-06-08 00:19 UTC, mishra14 approved these changes

2018-06-08 00:19 UTC, mishra14 commented on src/NuGet.Core/NuGet.Protocol/Plugins/PluginDiscoveryUtility.cs
> +        /// Given Visual Studio 2017 MSBuild.exe path, return the NuGet plugins directory which is in CommonExtensions\NuGet\NuGetPluginsDirectory
`NuGetPluginsDirectory` -> `NuGetPlugins`

2018-06-08 17:37 UTC, jainaashish approved these changes

2018-06-08 18:30 UTC, merged