Dev nkolev92 dotnetclihome
NuGet/NuGet.Client pull request #2306
Opened 2018-06-19 00:38 UTC by nkolev92

## Bug
Fixes: https://github.com/NuGet/Home/issues/6989
Regression: No  
If Regression then when did it last work:   
If Regression then how are we preventing it in future:   

## Fix
Details: 
In the dotnet.exe use-cases, NuGet needs to respect the DOTNET_CLI_HOME variable (it takes priority over the HOME variable). 

I have also added a helpful error message if both variables are not set. 

Example on nix platforms
```
Required environment variable 'HOME' is not set. Try setting 'DOTNET_CLI_HOME' or 'HOME' and running the operation
```

The message structure is similar to the already existing error message. 

## Testing/Validation
Tests Added: No
Reason for not adding tests:  No infra for such tests
Validation done: Manually

2018-06-19 00:54 UTC, peterhuene approved these changes

2018-06-26 21:19 UTC, mishra14 requested changes
Please add some functional tests that set the var and not set the var to assert the log.

2018-06-26 21:19 UTC, mishra14 commented on src/NuGet.Core/NuGet.Common/Strings.resx
> +    <value>Required environment variable '{0}' is not set. Try setting '{1}' or '{0}' and running the operation</value>
The error is not very clear. What should this be set to?

2018-06-26 21:19 UTC, mishra14 commented on src/NuGet.Core/NuGet.Common/PathUtil/NuGetEnvironment.cs
> +                return GetValueOrThrowMissingEnvVarsDotnet(() => GetDotNetHome() ?? Environment.GetEnvironmentVariable(Home), Home, DotNetHome);
Why isn't it `Environment.GetEnvironmentVariable(DotNetHome)`?

2018-06-26 21:24 UTC, nkolev92 commented
@mishra14 
There are no functional tests for environment because you can't mock anything.

2018-06-26 21:25 UTC, nkolev92 commented on src/NuGet.Core/NuGet.Common/Strings.resx
> +    <value>Required environment variable '{0}' is not set. Try setting '{1}' or '{0}' and running the operation</value>
That's a common pattern for env variables. (see above MissingRequiredEnvVar)

It's self explnatory what the HOME variable needs to be set to.

2018-06-26 21:27 UTC, nkolev92 commented on src/NuGet.Core/NuGet.Common/PathUtil/NuGetEnvironment.cs
> +                return GetValueOrThrowMissingEnvVarsDotnet(() => GetDotNetHome() ?? Environment.GetEnvironmentVariable(Home), Home, DotNetHome);
GetDotnetHome() does Environment.GetEnvironmentVariable(DotNetHome). 

The behavior is, use DotnetHome if set,otherwise use Home.

2018-06-26 22:43 UTC, mishra14 approved these changes

2018-06-27 03:23 UTC, merged