Update NuGet Packages metadata
NuGet/NuGet.Client pull request #2349
Opened 2018-07-17 22:17 UTC by PatoBeltran

## Bug
Fixes: https://github.com/NuGet/Home/issues/6518

Update NuGet packages metadata to have the correct copyright

2018-07-17 22:33 UTC, rohit21agrawal approved these changes

2018-07-18 17:28 UTC, jainaashish requested changes
One question, why should ProjectUrl be pointing to `NuGet.Home`? IMO it should be `nuget.org`

2018-07-18 17:57 UTC, nkolev92 commented
@jainaashish 
Why NuGet.org?

These are client libraries, not the server. 

Redirecting to NuGet/NuGet.Client instead of NuGet/Home might make a bit more sense.

2018-07-18 17:59 UTC, nkolev92 approved these changes
LGTM. 

I disagree with @jainaashish that the projectUrl should be nuget.org.

2018-07-18 18:44 UTC, jainaashish commented
@nkolev92 this is the project url we're talking about and not repository url... and there is only single NuGet, not client nuget and server nuget for outside world.

2018-07-18 18:46 UTC, nkolev92 commented
NuGet.org still doesn't make sense. 

People are aware there's a client and a server. 

ProjectUrl should ideally be a place where people can file issues/ask for help, which I guess in that context it makes sense for it to stay nuget/home.

2018-07-18 18:58 UTC, jainaashish commented
I disagree ProjectUrl is the place to get more details about the project and not your github link to file issues. Nor i've seen this usage of ProjectUrl any where else. Look at some of the good packages even on nuget.org and what they add as projecturl...

Although we can add our github link on nuget.org to allow customers to move to source code page from there.

2018-07-18 20:05 UTC, mishra14 commented
@PatoBeltran WHat is the reasoning behind changing the copyright? If I remember correctly, NuGet client is still under .NET foundation. cc @karann-msft

2018-07-18 20:59 UTC, PatoBeltran commented
@mishra14 you can look at the issue https://github.com/NuGet/Home/issues/6518

@jainaashish @nkolev92 Given that this is for packages, the project url should be somewhere where you can find more details about the project (eg. documentation, reference to where to file issues, specs, etc.). Since we don't have one page that has everything I think either NuGet/Home or nuget.org are acceptable, but NuGet/Home seems to be more closely couple to us.

2018-07-30 23:01 UTC, nkolev92 commented
@PatoBeltran you can probably merge this.

2018-08-01 18:46 UTC, mishra14 commented
@nkolev92 @PatoBeltran  before merging we should clarify the copyright issue with @karann-msft or @anangaur

2018-08-01 18:54 UTC, nkolev92 commented
@mishra14 doesn't https://github.com/NuGet/Home/issues/6518#issuecomment-403654822 answer that?

2018-08-01 18:55 UTC, nkolev92 commented
Furthermore there's some more changes required per https://github.com/NuGet/Home/issues/6518#issuecomment-408205989
@PatoBeltran

2018-08-02 18:56 UTC, mishra14 commented
@nkolev92 We discussed this offline right? Based on what I remember the Gallery (and the server) team moved to Microsoft, but the client team has not made that transition. We should clarify that before changing our copyright.

2018-08-02 19:15 UTC, nkolev92 commented
//cc @karann-msft

2018-08-09 17:46 UTC, PatoBeltran commented
updated with further required changes. @karann-msft can you please review?

2018-08-16 16:00 UTC, karann-msft approved these changes
LGTM.

2018-08-16 16:00 UTC, karann-msft commented on build/config.props
> +    <Description>NuGet client library. Microsoft holds the copyright for this NuGet package. .NET Foundations holds the copyright to the source.</Description>
As long as `&#169;` translates to © when the package is published, it looks good.

2018-08-16 16:00 UTC, karann-msft commented on src/NuGet.Clients/NuGet.CommandLine/NuGet.CommandLine.nuspec
> +    <copyright>&#169; Microsoft Corporation. All rights reserved.</copyright>
As long as `&#169;` translates to © when the package is published, it looks good.

2018-08-20 21:07 UTC, jainaashish approved these changes

2018-08-20 23:07 UTC, merged

2018-08-21 00:55 UTC, karann-msft commented
:shipit: