fix: AllVersion ignored for list from local folder
NuGet/NuGet.Client pull request #2397
Opened 2018-08-23 03:41 UTC by RussKie

Fixes 

## Bug
Fixes: NuGet/Home#4537
Regression: Yes  
If Regression then when did it last work:  Never?

## Fix
NuGet.exe list from local packages folder does not work with the `AllVersion` flag.
For example, a local folder D:\packages contains four packages:

    D:\packages>dir /b
    foo.1.0.0.31.nupkg
    foo.1.0.0.41.nupkg
    foo.1.0.0.43.nupkg
    foo.2.0.0.10.nupkg

Running the following command with the officially released nuget.exe will return a single package:

    D:\packages>nuget.exe  list -source d:\packages foo -allversions
    foo 2.0.0.10

With the fix the results are as follows:

    D:\packages>nuget.exe  list -source d:\packages foo
    foo 2.0.0.10

    D:\packages>nuget.exe  list -source d:\packages foo -includedelisted
    foo 2.0.0.10

    D:\packages>nuget.exe  list -source d:\packages foo -prerelease
    foo 2.0.0.10

    D:\packages>nuget.exe  list -source d:\packages foo -prerelease -includedelisted
    foo 2.0.0.10

    D:\packages>nuget.exe  list -source d:\packages foo -prerelease -includedelisted -allversions
    foo 1.0.0.31
    foo 1.0.0.41
    foo 1.0.0.43
    foo 2.0.0.10

    D:\packages>nuget.exe  list -source d:\packages foo -allversions
    foo 1.0.0.31
    foo 1.0.0.41
    foo 1.0.0.43
    foo 2.0.0.10

## Testing/Validation
Tests Added: No  
Reason for not adding tests:  I'll add them, if this fix is deemed correct
Validation done:  manual

2018-08-23 23:45 UTC, rohit21agrawal commented
can you please add tests for this as well?

2018-08-24 03:16 UTC, RussKie commented
Could you please let me know if my proposal makes sense? If yes, I'll spend
time writing tests.

On Fri, Aug 24, 2018, 9:45 AM Rohit Agrawal <notifications@github.com>
wrote:

> can you please add tests for this as well?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/NuGet/NuGet.Client/pull/2397#issuecomment-415607348>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AEMyXiJn8vGskzsgDeGMznAuJQ-c47-Jks5uTz6GgaJpZM4WIyXk>
> .
>

2018-09-25 05:01 UTC, dnfclas commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/NuGet/NuGet.Client?pullRequest=2397) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/NuGet/NuGet.Client?pullRequest=2397) before we can accept your contribution.<br/><br/>:x: RussKie [sign now](https://cla.dotnetfoundation.org/NuGet/NuGet.Client?pullRequest=2397)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/NuGet/NuGet.Client?pullRequest=2397) it.</sub>

2018-12-15 21:19 UTC, ThetaSinner commented
Can this fix be merged?

2018-12-21 05:30 UTC, RussKie commented
4 months and still waiting... 😞

2019-01-15 14:58 UTC, wkush commented
Now that the tests are added it would be WONDERFUL to have this fix applied.  :)

2019-05-13 22:49 UTC, nkolev92 commented
Can you rebase from latest dev? 
Can you please add some tests that test aggregated AllVersions. 

Namely, with both a local and http feed. 

Some examples here: https://github.com/NuGet/NuGet.Client/blob/dev/test/NuGet.Clients.Tests/NuGet.CommandLine.Test/NuGetListCommandTest.cs#L417

2019-05-14 07:08 UTC, RussKie commented
> Can you rebase from latest dev?

I can, though it has been 9 months. 

> Can you please add some tests that test aggregated AllVersions.

There are tests in the PR, have you checked what they do?

> Namely, with both a local and http feed.

IIRC the bug only affects local feeds. So - no.

2019-05-17 05:53 UTC, RussKie commented
Rebased

2019-06-01 00:40 UTC, nkolev92 approved these changes

2019-06-01 00:50 UTC, nkolev92 requested changes
My bad, I didn't see the linux tests were failing. 

LocalPackageSearchResource_should_not_filter_results_if_not_requested is failing with 

Assert.Equal() Failure
Expected: String[] ["2.0.0-alpha.1.2+5", "1.0.0", "1.1.0"]
Actual: SelectListIterator<IPackageSearchMetadata, String> ["1.1.0", "1.0.0", "2.0.0-alpha.1.2+5"]

2019-06-01 00:52 UTC, nkolev92 commented
Consider adding a ToArray() at the end on line 755.

2019-06-01 12:53 UTC, RussKie commented
> Consider adding a ToArray() at the end on line 755.

Done, thanks.
I can't see the build, it isn't public, is it?

2019-06-01 18:54 UTC, nkolev92 commented
No unfortunately it's not. 
I kicked off the build again. 
Will update when the tests run.

2019-06-03 18:32 UTC, nkolev92 commented
> LocalPackageSearchResource_should_not_filter_results_if_not_requested is still faling on linux. 

```
Assert.Equal() Failure
Expected: String[] ["2.0.0-alpha.1.2+5", "1.0.0", "1.1.0"]
Actual: String[] ["1.0.0", "2.0.0-alpha.1.2+5", "1.1.0"]
```

From looking at it, I'm not sure if this is a potential issue or just a test problem.

2019-06-05 13:46 UTC, RussKie commented
I find it somewhat concerning that `SearchAsync` isn't producing stable results (for the same inputs).
I suppose I could add an `OrderBy` clause, but I would be questioning whether something else is broken that this fix would be masking...
Your call.

2019-06-05 16:39 UTC, nkolev92 commented
I'm not sure. 
Someone needs to take a look @NuGet/nuget-client and make sure what it happening is expected.

2020-08-17 17:40 UTC, zkat commented
@RussKie hey! Sorry it's taken so long to get back to you on this. We definitely want this PR in. Personally, I think having an `OrderBy` is a great idea! Could you do that and rebase onto the latest `dev` branch when you're able?

2021-01-22 05:38 UTC, zkat commented
Closing as stale

2021-01-22 05:38 UTC, closed without merging