[wip] Read exact package id and version from global packages folder
NuGet/NuGet.Client pull request #2578
Opened 2018-12-26 23:05 UTC by jainaashish

## Bug
Fixes: https://github.com/NuGet/Home/issues/7639
Regression: Yes/No  
If Regression then when did it last work:   
If Regression then how are we preventing it in future:   

## Fix
Details: Details_about the_fix  

## Testing/Validation
Tests Added: Yes/No  
Reason for not adding tests:  
Validation done:

2019-01-04 18:04 UTC, dtivel requested changes

2019-01-04 18:04 UTC, dtivel commented on src/NuGet.Core/NuGet.Commands/RestoreCommand/SourceRepositoryDependencyProvider.cs
> +                if (await _findPackagesByIdResource.DoesPackageExistAsync(
`VersionRange.MinVersion` can be `null`, and `DoesPackageExistAsync(…)` will throw if `version` is `null`.  Although this code assumes `libraryRange.VersionRange.MinVersion` will never be non-null, I see no such guarantee.  Can you check that `libraryRange.VersionRange.MinVersion` is not `null`?

2019-01-08 17:31 UTC, jainaashish commented
@NuGet/nuget-client 🔔

2019-01-09 18:01 UTC, jainaashish commented
@dtivel addressed your comment, will be able to take another look?

2019-01-09 18:34 UTC, dtivel approved these changes

2019-01-09 21:57 UTC, nkolev92 approved these changes

2019-01-14 23:57 UTC, merged