Add interactivity switch for the remove package reference command
NuGet/NuGet.Client pull request #2704
Opened 2019-01-30 20:13 UTC by nkolev92

## Bug

Fixes: https://github.com/NuGet/Home/issues/7727
Regression: Yes/No  
* Last working version:   
* How are we preventing it in future:   

## Fix

Details: 

The details are illustrated in the issue. 

Basically if the evaluation of the project needs to download the sdk, the resolver will never auth because when the credential service is setup, the interactivity context is false (unless you set MSBuildInteractive in the csproj). 

I am not super confident this is the right approach, so I'd like us to discuss before doing this. 

//cc @anangaur @rrelyea @kathleendollard

## Testing/Validation

Tests Added: Yes/No  
Reason for not adding tests:  
Validation:

2019-02-01 00:14 UTC, rrelyea requested changes

2019-02-01 00:14 UTC, rrelyea commented on src/NuGet.Core/NuGet.CommandLine.XPlat/Commands/PackageReferenceCommands/RemovePackageReferenceCommandRunner.cs
> +
most of the other uses of SetupDefaultCredentialService seem to be passing in !interactive

2019-02-01 00:30 UTC, nkolev92 commented on src/NuGet.Core/NuGet.CommandLine.XPlat/Commands/PackageReferenceCommands/RemovePackageReferenceCommandRunner.cs
> +
Nice catch. 
Not sure how I missed that. Fixed.

2019-02-01 21:22 UTC, rrelyea commented
👍

2019-02-01 21:22 UTC, rrelyea approved these changes

2019-02-06 06:31 UTC, wli3 commented
I find adding --interactive is case by case, could you also add interactive to `list`? the underline command called by `dotnet list package` ?

2019-02-06 06:33 UTC, wli3 commented
never mine i find it is merged in https://github.com/NuGet/NuGet.Client/pull/2582

2019-02-06 07:18 UTC, merged