[WIP] Support package signing and verification cross platform
NuGet/NuGet.Client pull request #2706
Opened 2019-01-31 00:50 UTC by PatoBeltran

## Bug

Fixes: https://github.com/NuGet/Home/issues/7606

## Fix

This PR starts the work to remove most of the if/defs and use APIs from netstandard2.0+extensions to add xplat support to the existing signing and signature verification code paths.

**Known issues:**

**Missing:**
- There are still 20+ test failures on Mac OS.
- There are 10+ disabled tests in Linux that use OCSP.
- Manual testing for dotnet restore and nuget.exe on mono

2019-01-31 23:38 UTC, PatoBeltran commented on src/NuGet.Core/NuGet.Packaging/Signing/Timestamp/Rfc3161TimestampVerificationUtility.cs
> +            return timestamp.UpperLimit <= signerCertExpiry &&
This seemed like an error in our code. If this is incorrect we can revert this change and make sure the tests take into account so they don't fail.

2019-01-31 23:38 UTC, PatoBeltran commented on src/NuGet.Core/NuGet.Packaging/Signing/Utility/VerificationUtility.cs
> +                catch (ArgumentException)
We don't want to swallow all the exceptions here, just the ones expected (i.e. one of these methods can throw a `PlatformNotSupportedException`)

2019-01-31 23:38 UTC, PatoBeltran commented on src/NuGet.Core/NuGet.Packaging/Signing/Verification/SignatureTrustAndValidityVerificationProvider.cs
> +            var isUnknownRevocationAllowed = RuntimeEnvironmentHelper.IsLinux && isUntrustedRootAllowed;
This is to account that on Linux UntrustedRoot will always also return unknown revocation. If this is incorrect we should revert this change.

2019-01-31 23:38 UTC, PatoBeltran commented on test/NuGet.Clients.FuncTests/NuGet.CommandLine.FuncTest/Commands/SignCommandTestFixture.cs
> +                                var crlName = urlSplits[1].Replace("%20", " ");
There might be a cleaner way of doing this.

2019-01-31 23:38 UTC, PatoBeltran commented on test/NuGet.Core.FuncTests/NuGet.Commands.FuncTest/RestoreCommandTests.cs
> +#if SUPPORTS_FULL_SIGNING
These tests were disabled because they use packages with timestamps.

2019-01-31 23:38 UTC, PatoBeltran commented on test/NuGet.Core.Tests/NuGet.Packaging.Test/NuGet.Packaging.Test.csproj
> +    <IsTestProject>true</IsTestProject>
This should be reverted.

2019-01-31 23:38 UTC, PatoBeltran commented on test/NuGet.Core.Tests/NuGet.Packaging.Test/SigningTests/SignedPackageArchiveUtilityTests.cs
> +                    offsetOfLocalFileHeaderLastModifiedDateTime = 0x1d5;
In linux and mac the certificates are different than the ones created in windows, therefore the offsets are different.

2019-01-31 23:38 UTC, PatoBeltran commented on test/TestUtilities/Test.Utility/Signing/TrustedTestCert.cs
> +using System.Diagnostics;
This line should be removed

2019-01-31 23:38 UTC, PatoBeltran commented on test/TestUtilities/Test.Utility/Signing/TrustedTestCert.cs
> +            TestDirectory dir,
`dir` is used to store trusted certs in MacOS. To avoid creating a directory for each cert is best for it to be passed by the test.

2019-01-31 23:38 UTC, PatoBeltran commented on test/TestUtilities/Test.Utility/Signing/TrustedTestCert.cs
> +                return StoreLocation.CurrentUser;
MacOS and Linux can only ReadWrite to `CurrentUser`

2019-01-31 23:38 UTC, PatoBeltran commented on test/TestUtilities/Test.Utility/Signing/TrustedTestCert.cs
> +                return StoreName.My;
MacOS can only Read/Write to `My` but this doesn't make the cert trusted. An explicit command has to be run for that.

2019-01-31 23:38 UTC, PatoBeltran commented on test/TestUtilities/Test.Utility/Signing/TrustedTestCert.cs
> +                if (_systemTrustedCertPath != null && RuntimeEnvironmentHelper.IsMacOSX)
It is important to first remove trust and then remove from the store.

2019-02-09 15:25 UTC, onovotny commented on src/NuGet.Core/NuGet.Packaging/Signing/Authoring/X509SignatureProvider.cs
> +#if SUPPORTS_FULL_SIGNING
The line above https://github.com/NuGet/NuGet.Client/pull/2706/files#diff-9f9f0fc95fc31c850ddf340ed90c8d57R134
`cms.ComputeSignature(cmsSigner);` needs to be changed to be `cms.ComputeSignature(cmsSigner, false);`

That parameter is to use a silent context or not, and the default is true. This means that in a silent context, a PIN prompt won't appear if the CNG/CAPI api requires one (like for a smartcard or usb token).

The .NET Framework didn't handle this correctly, and it worked. The behavior was made "correct" on .NET Core, so specifying `false` for the silent context is required.

2019-02-09 15:28 UTC, clairernovotny requested changes
As per my inline comment, `ComputeSignature` needs to change or it won't prompt for PIN prompts in interactive scenarios. This would block a .net core version of nuget.exe and blocks NuGet Package Explorer (which runs on .net core).

2020-01-06 23:11 UTC, zkat commented
This work is now being tracked over at https://github.com/NuGet/Home/issues/7939 and we are going to have a separate PR for this, so I'm closing this PR.

2020-01-06 23:11 UTC, closed without merging