add a framework reference & framework reference group mode
NuGet/NuGet.Client pull request #2789
Opened 2019-04-03 01:45 UTC by nkolev92

## Bug

Fixes: https://github.com/NuGet/Home/issues/7909
Regression: No  
* Last working version:   
* How are we preventing it in future:   

## Fix

Details: TBD

## Testing/Validation

Tests Added: Yes
Reason for not adding tests:  
Validation:  Automation & Manual

2019-04-08 18:54 UTC, zivkan approved these changes

2019-04-08 18:55 UTC, zivkan requested changes
Build errors need to be fixed :)

2019-04-08 19:18 UTC, nkolev92 commented
@zivkan Yep, fixing that now :)

2019-04-09 01:42 UTC, nkolev92 commented
@zivkan The build is fixed.

2019-04-11 19:40 UTC, nkolev92 commented
🔔

2019-04-11 20:08 UTC, zivkan approved these changes

2019-04-15 22:52 UTC, merged