Accessibility fixes
NuGet/NuGet.Client pull request #3201
Opened 2020-01-23 20:38 UTC by dominoFire

## Bug

Fixes: Link_to_issue  
Regression: Yes/No  
* Last working version:   
* How are we preventing it in future:   

## Fix

Details: Details_about_the_fix  

## Testing/Validation

Tests Added: Yes/No  
Reason for not adding tests:  
Validation:

2020-01-23 20:49 UTC, rrelyea commented
Can you please update the PR text to link to the issue that is being fixed.

2020-01-23 22:00 UTC, dominoFire commented
I will the corresponding github issue later. Below is the link for the
current fix.

https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1049209

On Thu, Jan 23, 2020, 12:49 PM Rob Relyea <notifications@github.com> wrote:

> Can you please update the PR text to link to the issue that is being fixed.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/NuGet/NuGet.Client/pull/3201?email_source=notifications&email_token=AAJDDG456WOLDM4YUFEU3ITQ7H7EBA5CNFSM4KK4VVJ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEJYZR4Q#issuecomment-577870066>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAJDDG3R5PMFYOOZ3YJVFXLQ7H7EBANCNFSM4KK4VVJQ>
> .
>

2020-01-23 22:40 UTC, rrelyea commented on src/NuGet.Clients/NuGet.PackageManagement.UI/Xamls/LicenseAcceptanceWindow.xaml
>            AutomationProperties.AutomationId="AcceptButton"
in addition to the fix by removing the labeledby property setting...
seems like the _licenseText element should also remove the AutomationProperties.Name that is set to {Binding Text}.
First of all, it was trying to bind to the text property, i think. But TextBlock.Text already is the default automationproperties.name, so it was unnecessary.  It also probably didn't work the way the author wanted to.

2020-01-23 22:41 UTC, rrelyea requested changes
recommend removing line 165 also.

2020-01-27 18:49 UTC, rrelyea approved these changes

2020-01-27 22:22 UTC, donnie-msft approved these changes

2020-01-27 22:25 UTC, merged