Update ResumeVSInstall to get latest VS_Installer
NuGet/NuGet.Client pull request #3209
Opened 2020-01-28 01:05 UTC by rrelyea

## Bug

Fixes: https://github.com/NuGet/Home/issues/9105
Regression: No

## Fix

Details: download and execute the VS_Bootstrapper exe to update the VS_Installer.exe

## Testing/Validation

Tests Added: No
Reason for not adding tests:  E2E test script
Validation:  Running on CI and then will reenable machine that is current broken to test.

2020-01-28 01:09 UTC, nkolev92 commented on scripts/e2etests/VSUtils.ps1
> +    Start-Process -FilePath "$VSBootstrapperPath" -ArgumentList "--update", "--quiet"
How long does this usually take?

2020-01-28 19:25 UTC, dtivel commented on scripts/e2etests/VSUtils.ps1
> +    $VSBootstrapperUrl = "https://aka.ms/vs/16/intpreview/vs_enterprise.exe"
This is fragile.  Given that `$VSVersion` is passed in, how about:
```PowerShell
$vsMajorVersion = [System.Version]::Parse($VSVersion).Major
$vsBootstrapperUrl = "https://aka.ms/vs/$vsMajorVersion/intpreview/vs_enterprise.exe"
```

2020-01-28 19:25 UTC, dtivel commented on build/vsts_build.yaml
> +    - Agent.Name -equals DDNuGetW001
I assume this is for debugging?

For the benefit of reviewers, you can avoid polluting this PR with debugging commits by creating a branch off this branch and pushing changes to that new branch.  Integrate changes back when appropriate.

2020-04-03 06:58 UTC, heng-liu requested changes

2020-04-03 06:58 UTC, heng-liu commented on scripts/e2etests/VSUtils.ps1
> +    $VSBootstrapperPath =  "$tempdir" + "vs_enterprise.exe"
In the offline discussion, Andy found (https://docs.microsoft.com/en-us/visualstudio/install/use-command-line-parameters-to-install-visual-studio?view=vs-2019#command-line-parameters), 
`Replace vs_enterprise.exe as appropriate for the product edition you're installing. (Alternatively, you can use vs_installer.exe.)`
We'd better change vs_enterprise.exe to vs_installer.exe.

2020-04-20 19:01 UTC, zivkan commented
Closing as abandoned, and superseded by https://github.com/NuGet/NuGet.Client/pull/3345

2020-04-20 19:01 UTC, closed without merging