Add powershell utilities to allow users to choose which version of Vi…
NuGet/NuGet.Client pull request #3384
Opened 2020-05-07 08:00 UTC by sbanni

## Bug

Fixes: [NuGet/Client.Engineering#304](https://github.com/NuGet/Client.Engineering/issues/304)
Regression: No  

## Fix

Details: Add a prompt to let the user choose which version of Visual Studio to run configure/build against if not already running in a developer prompt

## Testing/Validation

Tests Added: No  
Reason for not adding tests: Not a product issue  
Validation:  Ran configure.ps1/build.ps1 and made sure they ran with and without choosing a product version (legacy)

2020-05-07 14:31 UTC, sbanni commented
I just realized that this will probably block CI builds depending on how the environment is setup

2020-05-07 16:55 UTC, srdjanjovcic commented on build/VSUtilities.psm1
> +function Get-VsComnToolsPath {
Spell it out -- `Get-VsCommonToolsPath` instead of using `Comn`.

2020-05-07 16:58 UTC, srdjanjovcic reviewed
While this looks OK overall, I think it may be an overkill to implement all this just to select a Visual Studio. Detecting whether we are running from Dev command prompt or not would be probably enough. Those who have multiple instances just need to choose which VS instance's dev command prompt to launch.

2020-05-07 17:15 UTC, sbanni commented
@srdjanjovcic There is already logic in the scripts to determine if running in a dev cmd prompt, if not it will try to just use the latest vstoolspath but it doesn't start a devshell, just use the path and seems to rely on updating the common.ps1 script to update major version number for VS{VERSION}COMNTOOLS env var.

This is something that I use locally and find very helpful and can be used for other things in the future, for instance if we later wanted to add a script to patch the machine. If it is not needed/wanted, I am ok with closing this PR.

2020-05-07 17:18 UTC, srdjanjovcic commented
@sbanni Yeah, I am OK with this change. As you said, it basically does not do anything if already started from dev command prompt, so _my_ workflow is not affected 🙂.

2020-05-07 17:18 UTC, srdjanjovcic approved these changes

2020-05-07 17:40 UTC, sbanni commented
@rrelyea FYI

2020-05-07 17:56 UTC, sbanni commented
As I thought, the CI build does not like the read-host script, I will look to see if there is a way to distinguish between CI and local

2020-05-14 19:02 UTC, rrelyea commented
Looking into this now.

In VS command prompt, this happens:
![image](https://user-images.githubusercontent.com/8865080/81974383-6057d700-95da-11ea-9c00-8e4b5c163c5b.png)

In CMD prompt (non-dev cmd prompt), this happens:
![image](https://user-images.githubusercontent.com/8865080/81974477-80879600-95da-11ea-9100-4ea622b04bce.png)

My workflow doesn't need it...but seems like it will help new folks to our work be successful, so i like in general.
@zivkan - thoughts?

one problem, if i choose x, it prompts me a second time.
![image](https://user-images.githubusercontent.com/8865080/81974660-b9c00600-95da-11ea-8fe5-5bfac2c63d09.png)

2020-05-14 21:06 UTC, rrelyea requested changes
is that a bug we should address...(the one i described in conversation, pressing x, prompts again)

will take a look at code after you reply to that.

2020-05-14 23:18 UTC, sbanni commented
@rrelyea I see that spacing issue without my changes:
![image](https://user-images.githubusercontent.com/1885888/81995199-81caba00-95fe-11ea-9ebb-7358a7905a14.png)

The other issue I can look into, I don't recall seeing that.

2020-05-20 18:28 UTC, zivkan commented on build/VSUtilities.psm1
> +        Invoke-WebRequest "http://github.com/Microsoft/vswhere/releases/download/$vsWhereVersion/vswhere.exe" -OutFile $vswhereExe
Firstly, this looks like it's trying to create a directory and write a file in program files, which I strongly believe we should not be doing.

Secondly, I believe vswhere first shipped with VS2017, 15.3. Given the current NuGet dev branch needs VS2019, it's safe to assume that the machine has vswhere installed, so no need to download. THe VS installer doesn't allow customers to modify where the installer, and therefore where vswhere, is saved, so I think it's safe enough to hardcode the program files location and if it's not found, assume no compatible VS is installed.  `build\common.ps1` also uses vswhere.

2020-05-20 18:28 UTC, zivkan commented on build/VSUtilities.psm1
> +    $temp = & "$vsWhereExe" -nologo -all -prerelease -format text | select-string "instanceId|installationPath|installationName|catalog_productSemanticVersion"
You're probably already aware, but vswhere now supports `-format` to get json or xml, in case that's easier

2020-05-20 18:28 UTC, zivkan commented on build/common.ps1
> +if(![bool]([Environment]::GetCommandLineArgs() -like '-noni*')) {
`build.ps1` doesn't allow any `noni*` arguments, and I can't find a similar argument in any of our ps1 or `build/vsts_build.yaml` file. Does powershell automatically add it when it detects a non-interactive session?

2020-06-08 16:21 UTC, sbanni commented
Closing this, does not seem to be any interest in this.

2020-06-08 16:21 UTC, closed without merging