Updating NuGet.Build.Tasks.Console.exe.config with binding redirects
NuGet/NuGet.Client pull request #3441
Opened 2020-06-11 19:44 UTC by jeffkl

MSBuild added binding redirects for some of its dependencies because of a mismatch which means this app.config needs to have them as well.

## Bug

Fixes: https://github.com/NuGet/Home/issues/9665
Regression: Yes  
* Last working version:   5.6
* How are we preventing it in future:   Looking into VS setup automation to generate these binding redirects at install time.

## Fix

Details: Match the binding redirects from MSBuild.exe.config for 16.7

## Testing/Validation

Tests Added: No
Reason for not adding tests:  Not possible
Validation:  Set these binding redirects for my local config and verified that the restore works.

2020-06-11 19:44 UTC, jeffkl commented
Please review @rainersigwald and @forgind

2020-06-11 19:47 UTC, nkolev92 commented
@jeffkl Are you looking into the automatic binding redirects generation?

2020-06-11 19:47 UTC, Forgind reviewed
I'm a little surprised this was sufficient. Is there a reason you didn't include the other binding redirects we added?

2020-06-11 19:48 UTC, rainersigwald requested changes
I think this should match all of the new binding redirects in MSBuild.exe.config

```xml
<assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
  <dependentAssembly>
    <assemblyIdentity name="System.Buffers" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
    <bindingRedirect oldVersion="0.0.0.0-4.0.3.0" newVersion="4.0.3.0" />
  </dependentAssembly>
</assemblyBinding>
<assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
  <dependentAssembly>
    <assemblyIdentity name="System.Numerics.Vectors" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
    <bindingRedirect oldVersion="0.0.0.0-4.1.4.0" newVersion="4.1.4.0" />
  </dependentAssembly>
</assemblyBinding>
<assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
  <dependentAssembly>
    <assemblyIdentity name="System.Runtime.CompilerServices.Unsafe" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
    <bindingRedirect oldVersion="0.0.0.0-4.0.6.0" newVersion="4.0.6.0" />
  </dependentAssembly>
</assemblyBinding>
<assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
  <dependentAssembly>
    <assemblyIdentity name="System.ValueTuple" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
    <bindingRedirect oldVersion="0.0.0.0-4.0.3.0" newVersion="4.0.3.0" />
  </dependentAssembly>
</assemblyBinding>
```

2020-06-11 19:49 UTC, rainersigwald commented
Can we pretty please get this in for VS 16.7 preview 3?

2020-06-11 19:53 UTC, nkolev92 commented
> Can we pretty please get this in for VS 16.7 preview 3?

We can try :) 

cc @aortiz-msft @zkat

2020-06-11 19:58 UTC, jeffkl commented
At the moment, the code path does not need the other assemblies so the EXE runs fine without the other binding redirects.  But I'll add them just to be safe

2020-06-11 20:02 UTC, jeffkl commented
> Are you looking into the automatic binding redirects generation?

Yes @nkolev92 I will start some conversations with folks about how to make this automatic at install time.

2020-06-11 20:17 UTC, Forgind approved these changes
LGTM!

2020-06-11 20:17 UTC, Forgind commented on src/NuGet.Core/NuGet.Build.Tasks.Console/App.config
>          <codeBase version="4.0.2.0" href="..\..\..\..\..\MSBuild\Current\Bin\System.Buffers.dll" />
Should this be 4.0.3.0?

2020-06-11 20:19 UTC, Forgind approved these changes

2020-06-11 20:30 UTC, rainersigwald approved these changes

2020-06-11 22:35 UTC, nkolev92 commented
@jeffkl There's some test failures because of the binding redirect changes.

The current set-up is a bit fragile because of that.

2020-06-11 22:38 UTC, jeffkl commented
I wouldn't recommend we ship the assemblies next to NuGet as they're only really needed by MSBuild.  How hard would it be to get 16.7 Preview on the agents?  We might need to disable the tests for now until we're running on newer MSBuild. 😢

2020-06-11 22:43 UTC, nkolev92 commented
> How hard would it be to get 16.7 Preview on the agents?

It's impossible in the sense that we don't control that. 

I agree with disabling them in the mean time. 

> I wouldn't recommend we ship the assemblies next to NuGet as they're only really needed by MSBuild

We are calling MSBuild in our process technically. 
We should avoid duplication, but having to do insertion hops might prove to be too difficult. 
We can't even test this reliably given the CI machine state.

2020-06-13 04:30 UTC, nkolev92 approved these changes

2020-06-13 04:31 UTC, merged