Fix performance bottleneck
NuGet/NuGet.Client pull request #4446
Opened 2022-02-08 14:15 UTC by danslocombe

## Bug

Fixes:

Regression? Last working version:

## Description

Saw my nuget restores are quite slow on a mid-sized-project with the CPU pegged close to 100% on Windows.
Looking at a trace it seems like it is spending a lot of time intersecting properties from dependencies
![image](https://user-images.githubusercontent.com/5894853/153004265-4914eb70-f1e3-4ff1-9b6d-438b1d6500b2.png)
In particular a Linq execution seems to be taking a long time.

This small pr improves the intersection hopefully bringing speedups :)
All the tests seem to be passing.

## PR Checklist

- [ ] PR has a meaningful title
- [ ] PR has a linked issue.
- [ ] Described changes

- **Tests**
  - [ ] Automated tests added
  - **OR**
  
  - [ ] Test exception
  - **OR**
  - [ ] N/A 

- **Documentation**
  
  - [ ] Documentation PR or issue filled
  - **OR**
  - [ ] N/A

2022-02-08 14:15 UTC, dnfgituser commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/NuGet/NuGet.Client?pullRequest=4446) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/NuGet/NuGet.Client?pullRequest=4446) before we can accept your contribution.<br/><br/>:x: danslocombe [sign now](https://cla.dotnetfoundation.org/NuGet/NuGet.Client?pullRequest=4446)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/NuGet/NuGet.Client?pullRequest=4446) it.</sub>

2022-02-08 14:19 UTC, danslocombe commented on src/NuGet.Core/NuGet.Commands/RestoreCommand/Logging/TransitiveNoWarnUtils.cs
> -                    var allKeys = thisPackages.Keys.Concat(otherPackages.Keys)
The only reason I can see for the old implementation is if `thisPackages` or `otherPackages` can have a different StringComparer to OrdinalIgnoreCase.

Can this ever happen? I can't see tests for it

2022-02-08 19:09 UTC, erdembayar commented on src/NuGet.Core/NuGet.Commands/RestoreCommand/Logging/TransitiveNoWarnUtils.cs
> +                    foreach (var kv in thisPackages)
Thank you for your contribution. 
Could you be able to include after change flame graph? We need to measure if it's improving or not.
Also, I believe there is correctness concern too.
`thisPackage` -> `a, b,c` 
`thisPackage` -> ` b,c,d`
Before your change result it `a, b, c ,d`
After your change `a, b, c` only.
You need to add another for loop iteration for `otherPackages` too.

2022-02-08 22:30 UTC, zivkan commented
@jeffkl investigated the same code a few months ago: https://github.com/NuGet/NuGet.Client/pull/4256

Jeff, do you have any comments/feedback/learnings to share with this PR?

> All the tests seem to be passing.

@danslocombe Unfortunately I don't have great trust in NuGet.Client's tests.  I concur with @erdembayar's concern that there may be a correctness issue. As I commented in Jeff's PR, I was unable to find a test where a package is a transitive package of two different PackageReferences, each of which have different NoWarn values. I honestly have no idea if the transitive package is supposed to have both or neither of the NoWarn values 😕

2022-02-08 22:31 UTC, zivkan commented
Also, can you please improve the title of this PR?  NuGet has an enormous surface, Visual Studio, various command line tools, many features that are not restore. This PR's title much too ambiguous as to what part of NuGet it's related to.

2022-02-09 13:47 UTC, danslocombe commented
> @jeffkl investigated the same code a few months ago: #4256
> 
> Jeff, do you have any comments/feedback/learnings to share with this PR?
> 
> > All the tests seem to be passing.
> 
> @danslocombe Unfortunately I don't have great trust in NuGet.Client's tests. I concur with @erdembayar's concern that there may be a correctness issue. As I commented in Jeff's PR, I was unable to find a test where a package is a transitive package of two different PackageReferences, each of which have different NoWarn values. I honestly have no idea if the transitive package is supposed to have both or neither of the NoWarn values 😕

Yeah the issue seems to be the Intersect *doesn't perform an intersection* if one of the input collections is null
I don't know if this is the intended behaviour :/

2022-02-09 15:35 UTC, erdembayar commented
> > @jeffkl investigated the same code a few months ago: #4256
> > Jeff, do you have any comments/feedback/learnings to share with this PR?
> > > All the tests seem to be passing.
> > 
> > 
> > @danslocombe Unfortunately I don't have great trust in NuGet.Client's tests. I concur with @erdembayar's concern that there may be a correctness issue. As I commented in Jeff's PR, I was unable to find a test where a package is a transitive package of two different PackageReferences, each of which have different NoWarn values. I honestly have no idea if the transitive package is supposed to have both or neither of the NoWarn values 😕
> 
> Yeah the issue seems to be the Intersect _doesn't perform an intersection_ if one of the input collections is null I don't know if this is the intended behaviour :/

I don't follow, if one of them is null, then it returns the other one, I believe it's expected. 
https://github.com/NuGet/NuGet.Client/blob/beba8c2e08f8ae480359c3bea77cd57921fb8d04/src/NuGet.Core/NuGet.Commands/RestoreCommand/Logging/TransitiveNoWarnUtils.cs#L899-L907

2022-02-09 16:24 UTC, jeffkl commented
When I investigated the issue, I only discovered that the determination of transitive NoWarn with a complex graph could create millions of items and take forever.  My attempt at a fix was here: https://github.com/NuGet/NuGet.Client/pull/4256/files which limited the transitive search to ignore already visited keys.  

There are a fair _amount_ of [unit tests for this class](https://github.com/NuGet/NuGet.Client/blob/dev/test/NuGet.Core.Tests/NuGet.Commands.Test/TransitiveNoWarnUtilsTests.cs) but I didn't have time to really dive into how much coverage they provide.

2022-02-22 17:50 UTC, erdembayar commented
@danslocombe
Gentle ping. Is this PR still under your radar? I can see few comments needs to be addressed.

2022-03-03 04:56 UTC, martinrrm commented
@erdembayar Assigning this issue to you because it looks like you are engaging with the contributor.

2022-03-03 17:42 UTC, zivkan requested changes
NuGet has many, many different feature areas. I doubt this PR is fixing them all. Please update the title to something more meaningful and specific.

2022-03-04 12:19 UTC, closed without merging