Improve ci initialization script
NuGet/NuGet.Client pull request #4810
Opened 2022-09-20 00:35 UTC by heng-liu

## Bug

Fixes:https://github.com/NuGet/Client.Engineering/issues/1864

Regression? Last working version:

## Description
Cherry-pick https://github.com/NuGet/NuGet.Client/commit/9c349a023da147ba81a865f94ca1e52eb5ac028c commit into release-6.0.x branch. This is to fix a bug when build is triggered by "Approved for CI" label.

If the build is triggered by "Approved for CI" label, the "Configure VSTS CI Environment" step will fail to find the localization branch: [build](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=6695587&view=logs&j=d80b2849-30d4-52dd-74cd-d6536ba98fe0&t=64c204f9-1df6-57fc-6b34-ec5bd3372627&l=15)
```
Looking for branch 'head' in NuGet.Build.Localization
NuGet.Build.Localization Branch: head
git update NuGet.Build.Localization at D:\a\_work\1\s\submodules\NuGet.Build.Localization
fatal: couldn't find remote ref head
```

After cherry-pick this commit, the "Configure VSTS CI Environment" step will be like: [build](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=6699945&view=logs&j=d80b2849-30d4-52dd-74cd-d6536ba98fe0&t=64c204f9-1df6-57fc-6b34-ec5bd3372627&l=14)
```
Looking for branch 'head' in NuGet.Build.Localization
NuGet.Build.Localization Branch: dev
git update NuGet.Build.Localization at D:\a\_work\1\s\submodules\NuGet.Build.Localization
```

## PR Checklist

- [ ] PR has a meaningful title
- [ ] PR has a linked issue.
- [ ] Described changes

- **Tests**
  - [ ] Automated tests added
  - **OR**
  
  - [ ] Test exception
  - **OR**
  - [ ] N/A 

- **Documentation**
  
  - [ ] Documentation PR or issue filled
  - **OR**
  - [ ] N/A

2022-09-20 00:49 UTC, zivkan submitted a review, later dismissed
You didn't fill out the checklist.

2022-09-20 22:31 UTC, zivkan requested changes, later dismissed

2022-09-20 22:31 UTC, zivkan commented on src/NuGet.Clients/NuGet.VisualStudio/NuGet.VisualStudio.csproj
> +    <AssemblyVersion>$(NuGetSdkVsSemanticVersion).0</AssemblyVersion>
This is going to change the package and assembly version scheme, which we should not do in a patch version of 6.0

2022-09-20 22:31 UTC, zivkan commented on src/NuGet.Clients/NuGet.VisualStudio.Contracts/NuGet.VisualStudio.Contracts.csproj
> +    <AssemblyVersion>$(NuGetSdkVsSemanticVersion).0</AssemblyVersion>
This is going to change the package and assembly version scheme, which we should not do in a patch version of 6.0

2022-09-23 22:38 UTC, zivkan commented
@NuGet/nuget-client need reviews/approvals please

2022-09-24 00:07 UTC, erdembayar approved these changes
LGTM

2022-09-26 17:10 UTC, jeffkl approved these changes

2022-09-26 21:28 UTC, merged