Simplify direct comparison to bool
NuGet/NuGet.Client pull request #4869
Opened 2022-10-23 16:02 UTC by AtariDreams

Just have the bool directly in the if statements

## Bug

Fixes:

Regression? Last working version:

## Description

## PR Checklist

- [ ] PR has a meaningful title
- [ ] PR has a linked issue.
- [ ] Described changes

- **Tests**
  - [ ] Automated tests added
  - **OR**
  
  - [ ] Test exception
  - **OR**
  - [ ] N/A 

- **Documentation**
  
  - [ ] Documentation PR or issue filled
  - **OR**
  - [ ] N/A

2022-10-24 16:33 UTC, erdembayar commented on src/NuGet.Clients/NuGet.PackageManagement.PowerShellCmdlets/NuGetPowerShellBaseCommand.cs
> +                else if (!exists )
Please remove the extra space at the end.

2022-10-24 16:41 UTC, erdembayar reviewed
Thank for your contribution. 
Please make sure code compiles on your local, I left 2 comments where it should fail and there're more. Please revert unnecessary changes.

2022-10-24 16:41 UTC, erdembayar commented on src/NuGet.Clients/NuGetConsole.Host.PowerShell/Utils/InstalledPackageEnumerator.cs
> +            if (installedRefs?.Any())
Does it compile on your local? It should fail because it's nullable expression.

2022-10-24 16:41 UTC, erdembayar commented on src/NuGet.Core/NuGet.CommandLine.XPlat/Commands/PackageReferenceCommands/AddPackageReferenceCommandRunner.cs
> +            if (packageReferenceArgs.Frameworks?.Any())
Same here

2022-10-24 18:34 UTC, nkolev92 requested changes

2022-10-24 18:34 UTC, nkolev92 commented on src/NuGet.Clients/NuGet.PackageManagement.PowerShellCmdlets/NuGetPowerShellBaseCommand.cs
> +                else if (!exists )
this should probably be formatted.

2022-10-24 18:34 UTC, nkolev92 commented on src/NuGet.Clients/NuGet.PackageManagement.UI/Models/PackageDetailControlModel.cs
> +                if (installed && _projectVersionConstraints.Any(e => e.IsAutoReferenced && e.VersionRange?.Satisfies(version.version)))
This is nullable so this change is gonna make compilation fail.

2022-10-31 15:54 UTC, erdembayar commented on src/NuGet.Clients/NuGet.PackageManagement.UI/Automation/ToggleableItemAutomationPeer.cs
> +            if (patternInterface == PatternInterface.Toggle && _ownerParent?.IsItemSelectionEnabled)
This still should fail. Please revert all nullable type changes.

2022-10-31 15:56 UTC, erdembayar commented on src/NuGet.Clients/NuGet.PackageManagement.UI/Xamls/PackageManagerControl.xaml.cs
> +            int recommendedCount = _packageList.PackageItems.Where(item => item.Recommended).Count();
I feel this one conveys intention of code, I prefer to keep the `true` here.

2023-02-16 00:01 UTC, closed without merging