[release-5.11.x] Create user specific NuGetScratch on Linux
NuGet/NuGet.Client pull request #5236
Opened 2023-06-14 21:33 UTC by heng-liu

## Bug

This is part of a work in https://github.com/NuGet/Client.Engineering/issues/2249

Regression? Last working version:

## Description
Create user specific NuGetScratch folder on Linux, also changed naming to append username on Linux platform.

## PR Checklist

- [ ] PR has a meaningful title
- [ ] PR has a linked issue.
- [ ] Described changes

- **Tests**
  - [ ] Automated tests added
  - **OR**
  
  - [ ] Test exception
  - **OR**
  - [ ] N/A 

- **Documentation**
  
  - [ ] Documentation PR or issue filled
  - **OR**
  - [ ] N/A

2023-06-14 21:35 UTC, nkolev92 approved these changes, later dismissed

2023-06-14 23:44 UTC, kartheekp-ms commented
I would have updated the patch version in different PR, but I guess it is okay.

2023-06-14 23:48 UTC, kartheekp-ms requested changes
I guess we should update the product version here https://github.com/NuGet/NuGet.Client/blob/release-5.11.x/src/NuGet.Clients/NuGet.Tools/NuGetPackage.cs#L86

For reference https://github.com/NuGet/NuGet.Client/pull/4911/files

If possible, please create seperate PR one for  NuGetScratch work and another updating the release branding.

2023-06-15 00:04 UTC, heng-liu commented
Thanks for reviewing! Hi @kartheekp-ms , I revert the change on patch version. Pls take another look. Thanks!

2023-06-15 01:14 UTC, kartheekp-ms approved these changes

2023-06-15 02:13 UTC, merged