Remove 'Checking compatibility...' log
NuGet/NuGet.Client pull request #5362
Opened 2023-08-16 17:21 UTC by Nigusu-Allehu

## Bug

Fixes: https://github.com/NuGet/Home/issues/10383

Regression? Last working version:

## Description

Remove "Checking compatibility ..." logs. 
## PR Checklist

- [ ] PR has a meaningful title
- [ ] PR has a linked issue.
- [ ] Described changes

- **Tests**
  - [ ] Automated tests added
  - **OR**
  
  - [ ] Test exception
  - **OR**
  - [ ] N/A 

- **Documentation**
  
  - [ ] Documentation PR or issue filled
  - **OR**
  - [ ] N/A

2023-08-16 18:39 UTC, jeffkl submitted a review, later dismissed
It's fascinating that there are no unit tests to update/remove as well.

2023-08-16 20:51 UTC, aortiz-msft commented
Please fill out the PR description and under manual tests, describe what manual testing you performed to validate this change.

2023-08-16 20:52 UTC, aortiz-msft requested changes
Please fill out the PR description and under manual tests, describe what manual testing you performed to validate this change.

2023-08-18 18:33 UTC, aortiz-msft approved these changes, later dismissed

2023-08-18 18:33 UTC, aortiz-msft commented on src/NuGet.Core/NuGet.Commands/RestoreCommand/RestoreCommand.cs
Could you please remove the empty line after the {?

2023-08-21 17:07 UTC, nkolev92 approved these changes

2023-08-22 19:25 UTC, aortiz-msft approved these changes

2023-08-22 22:22 UTC, merged