Update Newtonsoft.Json from 13.0.1 to 13.0.3
NuGet/NuGet.Client pull request #5385
Opened 2023-08-29 13:27 UTC by mthalman

.NET repos currently have a mix of Newtonsoft.Json versions that we're trying to get consolidated into the latest version. This is particularly necessary for the .NET's [source-build](https://github.com/dotnet/source-build) which can only reference one version of a dependency.

Related to https://github.com/dotnet/source-build-externals/pull/195

2023-08-29 13:27 UTC, mthalman commented
cc @MichaelSimons for review

2023-08-29 14:50 UTC, MichaelSimons approved these changes

2023-08-29 16:44 UTC, nkolev92 requested changes
Hey @mthalman 

Thanks for the PR. 
Please follow the PR template. We depend on that for automation. For product changes like this, we need a NuGet/Home tracking issue as per the template. 

I don't think we need to change the test code either. Those tests are not run in source build scenarios anyways.

2023-08-29 16:44 UTC, nkolev92 commented on test/EndToEnd/tests/BuildIntegratedTest.ps1
> -    $project1 | Install-Package Newtonsoft.Json -Version 13.0.1
This is test code. Please revert this.

2023-08-29 17:26 UTC, nkolev92 approved these changes
Change looks good. Our insertions are blocked today, so not sure if this would stand a chance at making P2 in VS. 

The SDK seems to be using 13.0.1. https://github.com/dotnet/sdk/blob/main/eng/Versions.props#L31. 
Do we need to coordinate with them?

2023-08-29 17:29 UTC, mthalman commented
> The SDK seems to be using 13.0.1. https://github.com/dotnet/sdk/blob/main/eng/Versions.props#L31.

Yes, I've got a PR for the SDK changes: https://github.com/dotnet/sdk/pull/35008

Back-references for all PRs related to this work can be found at https://github.com/dotnet/source-build-externals/pull/195.

2023-08-31 00:47 UTC, heng-liu approved these changes

2023-08-31 05:00 UTC, zivkan approved these changes

2023-08-31 05:01 UTC, merged