Add new ctor for PackageIdentity
NuGet/NuGet.Client pull request #5815
Opened 2024-05-23 12:52 UTC by jairbubbles

Syntaxic sugar allowing to instantiate like that

```csharp
var package = new PackageIdentity("Newtonsoft.json", "13.0.1");
```

Rather than

```csharp
var package = new PackageIdentity("Newtonsoft.json",  new NuGetVersion("13.0.1"));
```

2024-05-23 17:50 UTC, nkolev92 requested changes
Given that there's only 1 constructor, and the simplification is small, I don't think we should take this. 

@NuGet/nuget-client @zivkan Thoughts?

2024-05-23 18:26 UTC, Nigusu-Allehu commented
I second @nkolev92 . In addition, since the existing constructor is called with a null version value in multiple places in our tests, this will lead to multiple ambiguities. You can see that in the failed job of the pipeline

2024-05-23 20:32 UTC, donnie-msft reviewed
Since there isn't a linked issue, could you describe the problem that this constructor solves?There's already `NuGetVersion.Parse(value)` to help in creating the type.

2024-05-23 22:01 UTC, zivkan commented
In general, some of our APIs are not easy to use, and I don't think it's a bad thing to make it easier to use.

However, this specific example can be achieved rather easily by creating a helper class/method, so instead of `new PackageIdentity("package.id", NuGetVersion.Parse("1.2.3")` you'd call your own `NuGetHelper.CreateIdendity("package.id", "1.2.3")`. It does mean that every repo that wants such a helper needs to re-implement it, but it's also trivial. The .NET BCL doesn't try to do everything and provide every overload, so we can use the BCL as prior art in not accepting such a new overload.

I could go either way, but I'd lean towards not accepting this new public API. Thanks to C#'s expression-bodied members, it's literally a one-liner to create your own helper method.

2024-05-24 07:26 UTC, jairbubbles commented
> You can see that in the failed job of the pipeline

I guess next time, I should compile before sending the PR. 😅

> Could you describe the problem that this constructor solves?

It's really just to simplify using the API. The context is that we were previously using a custom NuGet library where we re-implemented a lot of things. We're now switching to a new one, which is just a thin wrapper over the official NuGet library but to simplify its usage.

In the old library we had a `NuGetPackage` class which was practical but not well designed as it grew over time and was doing too much things.

The idea is to switch to `PackageIdentity` and add some extensions methods over this type to simplify the use. Example:

```csharp
var client = new EzNuGetClient();

var package = new PackageIdentity("Newtonsoft.Json", new NuGetVersion("13.0.1"));

await client.InstallPackageInGlobalCache(logger, package);

var installationFolder = package.GetInstallationPathInGlobalCache(client);
```

All this is internal code but I'd be happy to share more info if you're interested.

> However, this specific example can be achieved rather easily by creating a helper class/method, so instead of new PackageIdentity("package.id", NuGetVersion.Parse("1.2.3") you'd call your own NuGetHelper.CreateIdendity("package.id", "1.2.3"). It does mean that every repo that wants such a helper needs to re-implement it, but it's also trivial. The .NET BCL doesn't try to do everything and provide every overload, so we can use the BCL as prior art in not accepting such a new overload.

Yes I agree but it's less discoverable.

2024-05-28 17:50 UTC, nkolev92 commented
Closing per the discussion.

2024-05-28 17:50 UTC, closed without merging