Update System.Text.Json from 8.0.4 to 8.0.5
NuGet/NuGet.Client pull request #6101
Opened 2024-10-15 17:28 UTC by dtivel

# Bug

Fixes:  https://github.com/NuGet/Home/issues/13857

## Description

This change updates System.Text.Json from 8.0.4 (with [security vulnerability](https://github.com/advisories/GHSA-8g4q-xg66-9fp4)) to 8.0.5 (latest release).

## PR Checklist

- [X] Meaningful title, helpful description and a linked NuGet/Home issue
- [ ] ~~Added tests~~ N/A
- [ ] ~~Link to an issue or pull request to update docs if this PR changes settings, environment variables, new feature, etc.~~ N/A

2024-10-15 17:57 UTC, aortiz-msft commented
@marcpopMSFT  - This change is going into 17.13. Is this good to merge now?

2024-10-15 19:12 UTC, jeffkl commented
MSBuild has been updated, its probably safe: https://github.com/dotnet/msbuild/pull/10776/files#diff-af84f50fd5aa2e8bfc3479cb6ddf7882bc084ce1af01de6dd49ff93aa2d1718cR138

2024-10-15 19:37 UTC, Nigusu-Allehu commented
> MSBuild has been updated, its probably safe: https://github.com/dotnet/msbuild/pull/10776/files#diff-af84f50fd5aa2e8bfc3479cb6ddf7882bc084ce1af01de6dd49ff93aa2d1718cR138

Should we not wait for VS as well?

2024-10-15 20:16 UTC, donnie-msft approved these changes
Thanks, Damon! I saw this error with local builds. Not sure why CI doesn't fail because of it.

2024-10-15 20:20 UTC, zivkan requested changes
We need confirmation this isn't going to cause problems, before we merge. See also:

* https://github.com/NuGet/NuGet.Client/pull/6089
* https://github.com/NuGet/NuGet.Client/pull/6093

I still need to port a more advanced version of this PR to the dev branch:
* https://github.com/NuGet/NuGet.Client/pull/6015

The the PR description of this last PR for more details about why we can't upgrade some packages (like this one) until our downstream components are ready to take the change

2024-10-15 20:28 UTC, zivkan commented
Apex tests were useful in this case.  We can see that VS main branch is still shipping an older version of System.Text.Json, so NuGet in VS is failing because of an assembly load failure.

2024-10-15 20:47 UTC, dtivel commented
> Apex tests were useful in this case. We can see that VS main branch is still shipping an older version of System.Text.Json, so NuGet in VS is failing because of an assembly load failure.

Yep, super useful!  @zivkan, should I close this PR?

2024-10-15 21:38 UTC, marcpopMSFT commented
@rainersigwald has been traying to coordinate the update of VS on STJ. I believe it's too late for 17.11, he plans to talk to the QB for 17.12, and we definitely want it for 17.13 but it has to be coordinated with MS Build AND VS. Not sure if the VS work for 17.13 is done yet.

2024-10-15 22:06 UTC, rainersigwald commented
We MUST NOT reference STJ 8.0.5 for NuGet 6.12/SDK 9.0.100/VS 17.12. For 17.13/9.0.200/6.13 you will be clear to reference 8.0.5 as soon as MSBuild can manage to insert (any minute now; currently that's https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/585290). So I wouldn't close, but maybe pause for a day or two?

2024-10-16 18:51 UTC, Nigusu-Allehu approved these changes
I think we are good to go now. The MSBuild insertion updating STJ in VS to 8.05 is through.

2024-10-16 18:53 UTC, rainersigwald approved these changes
Yup, :shipit: 

cc @YuliiaKovalova -- yell at NuGet if we have to revert STJ in VS for some reason.

2024-10-16 20:10 UTC, zivkan approved these changes

2024-10-16 20:10 UTC, merged