Add Localization and A11y testing to PR template
NuGet/NuGet.Client pull request #6120
Opened 2024-10-24 17:58 UTC by aortiz-msft

# Bug

Fixes: 

## Description

Add Localization and A11y testing to the PR template.

## PR Checklist

- [x ] Meaningful title, helpful description and a linked NuGet/Home issue
- [ ] Added tests - N/A
- [ ] Link to an issue or pull request to update docs if this PR changes settings, environment variables, new feature, etc. - N/A

2024-10-24 17:58 UTC, donnie-msft submitted a review, later dismissed

2024-10-24 18:37 UTC, donnie-msft approved these changes

2024-10-24 22:36 UTC, nkolev92 requested changes

2024-10-24 22:36 UTC, nkolev92 commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] If the PR adds UI:
Our PR template has evolved over the years, but recent learnings/adjustments are that people won't fill it out if the template is too long. 

In https://github.com/NuGet/NuGet.Client/pull/5907, we simplified it to the 3 checkboxes that we have today. 
The idea with those 3 is that they're the most common and apply to a large majority of PRs. 

UI PRs aren't the majority of changes, so I don't think it's something that should be part of the template that covers all kinds of PRs. 

That being said, we do have places where call out localization and accessibility passes in our developer docs. IN particular, https://github.com/NuGet/NuGet.Client/blob/dev/docs/feature-guide.md#visual-studio-ui-considerations. 
We also have https://github.com/NuGet/NuGet.Client/blob/dev/docs/ui-guidelines.md which goes in a lot more detail. Maybe we can improve the reachability of this documentation?

2024-11-08 18:24 UTC, closed without merging

2024-11-08 18:50 UTC, aortiz-msft commented
We will instead add actions that add comments for changes that include xaml files.