Updated README that this repository superceedes Nuget2
NuGet/NuGet.Client pull request #815
Opened 2016-08-09 21:46 UTC by droyad

Related to Nuget/Home#3287

2016-08-09 21:46 UTC, dnfclas commented
Hi __@droyad__, I'm your friendly neighborhood .NET Foundation Pull Request Bot (You can call me DNFBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no Contribution License Agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, DNFBOT;

2017-01-30 03:00 UTC, dnfclas commented
__@droyad__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, DNFBOT;

2017-03-02 00:57 UTC, emgarten requested changes

2017-03-02 00:57 UTC, emgarten commented on README.md
> +This repository contains v3.0 and later of the NuGet client libraries, replacing the Nuget2 repository and the NuGet.Core package.
Would you link to the NuGet2 repository here to make this more clear?

2017-04-06 23:03 UTC, mishra14 commented
@emgarten - can you close this?

2017-11-10 23:40 UTC, emgarten commented
Closing due to lack of response.

2017-11-10 23:40 UTC, closed without merging