Add TestableVSCredentialProvider
NuGet/NuGet.Client pull request #870
Opened 2016-09-14 18:41 UTC by pspill

Test providers for use with NuGet/Home#2909

2016-09-15 16:24 UTC, alpaix commented on test/TestExtensions/TestableVSCredentialProvider/TestableVSCredentialProvider.csproj
> +    <OutputPath>..\..\..\artifacts\TestableVSCredentialProvider\14.0\Debug\</OutputPath>
Default values are defined in `common.props` file. Please import it here as well.

2016-09-15 16:29 UTC, alpaix requested changes
Please update the project file to import default values.

2016-09-23 01:51 UTC, pspill commented on test/TestExtensions/TestableVSCredentialProvider/TestableVSCredentialProvider.csproj
> +    <OutputPath>..\..\..\artifacts\TestableVSCredentialProvider\14.0\Debug\</OutputPath>
Thanks @alpaix, imported and removed a bunch of unnecessary stuff from the .csproj

2016-09-28 16:50 UTC, alpaix approved these changes

2016-10-04 18:52 UTC, joelverhagen commented
Is there some steps on how to use with along with the VSIX? Can both be used in the same experimental instance?

2016-10-04 21:53 UTC, pspill commented
@joelverhagen added a readme explaining usage

2016-10-04 22:32 UTC, joelverhagen approved these changes

2016-10-04 23:38 UTC, merged