Properly request DTE service from the components service provider
NuGet/NuGet.Client pull request #871
Opened 2016-09-15 15:12 UTC by kzu

The previous approach failed if the MEF component happened to be
instantiated from a background thread (i.e. another MEF component
requested in a background thread depended these exports). Since
MEF components aren't guaranteed to initialize on the UI thread,
this caused heard to track and unfriendly errors, such as
NuGet/Home#3419.

The requirement came from the helper class which used a static
service locator and therefore had no way of knowing if it was
being properly invoked, and therefore resorted to just throwing
if not.

This fix changes the way these services are requested from the
MEF components so that they use the built-in mechanism provided
by VSMEF to retrieve VS services properly from a MEF component:
the IServiceProvider import.

Since the helper does not need to retrieve the service itself
anymore, it receives the DTE as a parameter instead.

This fixes NuGet/Home#3419

The previous issue can be easily reproduced with the following
VS package code:

	[ProvideAutoLoad(UIContextGuids.SolutionExists)]
	[PackageRegistration(UseManagedResourcesOnly = true)]
	[Guid(PackageGuidString)]
	public sealed class NuGetBreakingPackage : Package
	{
		public const string PackageGuidString = "3FF684D3-61BF-417C-A1C0-17CD9B81BFE6";

		protected override void Initialize()
		{
			base.Initialize();

			var components = (IComponentModel)GetService(typeof(SComponentModel));

			System.Threading.Tasks.Task.Run(() =>
			{
				try
				{
					var solution = components.DefaultExportProvider.GetExportedValue<object>("NuGet.PackageManagement.ISolutionManager");
				}
				catch (Exception ex)
				{
					Debug.Fail(ex.ToString());
				}
			});
		}
	}

2016-09-15 20:15 UTC, craigajohnson commented
Nice work.

2016-09-16 05:23 UTC, emgarten commented
The goal of throwing if not on the UI thread is to ensure that this code fails consistently if there is a problem, which there appears to be here since DTE should only be used from the UI thread per the VS threading guidelines.

This change would probably solve the issue, but it seems like a JTF should be used here to ensure that this gets onto the UI thread to perform the DTE operations.

2016-09-16 09:50 UTC, kzu commented
I don't have a problem with that, but switching threads isn't free and as
proven in the linked issue, it's obviously not needed for this particular
narrow case of retrieving the version.

I doubt changing this to use JTF will change the intention of not fixing
this in nuget though. We'll likely fix it in Xamarin, and it will then be
just a matter of time until some other component triggers this same issue.

Given how non-obvious it was for me to find the cause (even if this is not
the root cause), I'd totally take the opportunity to fix it here.

On Fri, Sep 16, 2016, 2:23 AM Justin Emgarten <notifications@github.com>
wrote:

> The goal of throwing if not on the UI thread is to ensure that this code
> fails consistently if there is a problem, which there appears to be here
> since DTE should only be used from the UI thread per the VS threading
> guidelines.
>
> This change would probably solve the issue, but it seems like a JTF should
> be used here to ensure that this gets onto the UI thread to perform the DTE
> operations.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/NuGet/NuGet.Client/pull/871#issuecomment-247520696>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAKW6zIdKSB3NnaiL_I4fGFiKw_bDGPVks5qqifAgaJpZM4J9_KA>
> .
>
-- 
/kzu from mobile

2016-10-15 17:07 UTC, alpaix requested changes

2016-10-15 17:07 UTC, alpaix commented on src/NuGet.Clients/PackageManagement.VisualStudio/IDE/VSSolutionManager.cs
> +        public VSSolutionManager([Import(typeof(SVsServiceProvider))] IServiceProvider serviceProvider)
I like the idea of passing `IServiceProvider` to the constructor via MEF import.

2016-10-15 17:07 UTC, alpaix commented on src/NuGet.Clients/PackageManagement.VisualStudio/IDE/VSSolutionManager.cs
> +                new UserAgentStringBuilder().WithVisualStudioSKU(VSVersionHelper.GetFullVsVersionString(_dte)));
We shouldn't perform any DTE queries in a constructor which is hard to control in MEF. I'd suggest moving this statement to `NuGetPackage.Initialize`.

2016-10-15 17:07 UTC, alpaix commented on src/NuGet.Clients/PackageManagement.VisualStudio/Utility/VSVersionHelper.cs
> -            ThreadHelper.ThrowIfNotOnUIThread();
Thread guards should stay.

2016-10-15 17:07 UTC, alpaix commented on src/NuGet.Clients/PackageManagement.VisualStudio/Utility/VSVersionHelper.cs
> -            ThreadHelper.ThrowIfNotOnUIThread();
Same here.

2016-10-15 17:07 UTC, alpaix commented on src/NuGet.Clients/PackageManagement.VisualStudio/VSMachineWideSettings.cs
> +                        VSVersionHelper.GetSKU(dte));
Have to find away to bypass this call from the constructor.

2016-10-15 17:41 UTC, kzu commented
Not touching this anymore. There doesn't seem to be a willingness to fix it at proposed anyway.

2016-10-15 17:41 UTC, closed without merging

2016-10-15 17:45 UTC, alpaix commented
That's sad. Although I'm about to borrow the import technique in my Restore Manager work. I'll just copy few statements from this PR.