Adding logs to locals -clear temp
NuGet/NuGet.Client pull request #929
Opened 2016-10-11 21:37 UTC by mishra14

Adding log to clearTempCache method to indicate that the temp cache is also cleared.
Also adding some comments to other log strings.

```
E:\nuget\NuGet.Client [dev-anmishr-3607]> .\artifacts\VS14\NuGet.exe locals -clear all
Clearing NuGet HTTP cache: C:\Users\anmishr\AppData\Local\NuGet\v3-cache
Clearing NuGet global packages cache: C:\Users\anmishr\.nuget\packages\
Clearing NuGet Temp cache: C:\Users\anmishr\AppData\Local\Temp\NuGetScratch
Local resources cleared.
```

Fixes: https://github.com/NuGet/Home/issues/3607

2016-10-12 13:52 UTC, dtivel requested changes
Can you add a test verifying that the CLI now displays this message?  The test can easily cover each cache similar to [LocalsCommand_Success_ValidLocalResource_ListMessage](https://github.com/NuGet/NuGet.Client/blob/68729efe3362ca609d4cebb760b6bde76c38f644/test/NuGet.Clients.Tests/NuGet.CommandLine.Test/NuGetLocalsCommandTest.cs#L88)

2016-10-13 13:00 UTC, alpaix commented on src/NuGet.Core/NuGet.Commands/LocalsCommandRunner.cs
> +            var success = true;
nit: In general, initial assumption should be that `success` is `false`.

2016-10-13 14:08 UTC, joelverhagen requested changes
As @dtivel said, let's have a test validating this behavior.

2016-10-13 20:57 UTC, mishra14 commented on src/NuGet.Core/NuGet.Commands/LocalsCommandRunner.cs
> +            var success = true;
Sure. But incase the path is not present then we return true, since the path/folder/cache is effectively cleared.

2016-10-19 02:14 UTC, mishra14 commented
@joelverhagen  @dtivel : I have added asserts in test cases in XPlatLocalsTests.cs.

2016-10-19 02:39 UTC, dtivel approved these changes

2016-10-19 15:26 UTC, joelverhagen approved these changes

2016-10-19 16:16 UTC, alpaix approved these changes

2016-10-19 19:20 UTC, merged