Improve packages cache and better handling of cancellation token.
NuGet/NuGet.Client pull request #941
Opened 2016-10-18 21:40 UTC by jainaashish

It does following things:
- Reduce memory consumption for packages cache in-memory by ~70% by avoiding JToken or JArray objects lazy initialization, instead parse and save actual objects.
- It makes sure that we only have single ui loading/ refresh update packages task at any given point in time by properly cancelling previous tasks. Also whenever a new refresh update packages task starts, it makes sure to clean existing cache so that it doesn't block unnecessary memory in there.
- It also makes sure to cancel running tasks when manager ui is being closed.

Fixes https://github.com/NuGet/Home/issues/3661

@rrelyea @emgarten @dtivel @joelverhagen @alpaix

2016-10-19 04:42 UTC, dtivel approved these changes

2016-10-19 16:00 UTC, alpaix commented on src/NuGet.Core/NuGet.Protocol.Core.v3/Model/PackageSearchMetadata.cs
> +        public VersionInfo[] OnDemandParsedVersions { get; private set; }
Converter is not needed when using raw type. Consider removing it. 
Also as it's not parsed on-demand anymore it'd be great renaming the attribute as well to avoid confusion.

2016-10-19 16:12 UTC, alpaix commented on src/NuGet.Clients/PackageManagement.UI/Xamls/PackageManagerControl.xaml.cs
> +            _refreshCts?.Cancel();
`CancellationTokenSource` is disposable. It should be disposed directly or indirectly.

2016-10-19 16:16 UTC, alpaix requested changes
Please address cts disposal and json converter concerns.

2016-10-19 17:08 UTC, joelverhagen approved these changes

2016-10-19 19:25 UTC, emgarten commented
As @alpaix mentioned, all token sources need to be disposed

2016-10-20 23:06 UTC, jainaashish commented on src/NuGet.Core/NuGet.Protocol.Core.v3/Model/PackageSearchMetadata.cs
> +        public VersionInfo[] OnDemandParsedVersions { get; private set; }
Removed Converter

2016-10-20 23:06 UTC, jainaashish commented on src/NuGet.Clients/PackageManagement.UI/Xamls/PackageManagerControl.xaml.cs
> +            _refreshCts?.Cancel();
Fixed

2016-10-20 23:44 UTC, alpaix approved these changes

2016-10-21 00:35 UTC, merged