Referencing new MS.VS.Services.Client dll
NuGet/NuGet.Client pull request #958
Opened 2016-10-24 23:08 UTC by mishra14

Fixes: https://github.com/NuGet/Home/issues/3670

Triggered by internal bug 278033. Microsoft.VisualStudio.Services.ClientInteractive.dll has been renamed to Microsoft.VisualStudio.Services.Client.Interactive.dll.

Still waiting on folks from VSCS team to validate that this fixes the issue. But good to have some eyes on this before that.

//cc: @rrelyea @emgarten @joelverhagen @dtivel @drewgil @jainaashish @alpaix @zhili1208 @rohit21agrawal

2016-10-25 01:27 UTC, joelverhagen commented on test/NuGet.Clients.Tests/NuGet.PackageManagement.UI.Test/project.json
> +    "Newtonsoft.Json": "6.0.0"
This should match the VS version (`6.0.4`)

2016-10-25 01:28 UTC, joelverhagen commented
NuGet should start using Newtonsoft.Json 8.0.x for dev15, right?

2016-10-25 01:29 UTC, joelverhagen requested changes
Should this PR include the changes to newer Newtonsoft.Json in VS?

2016-10-25 21:38 UTC, mishra14 commented
@joelverhagen  : Fixed the requested change and created an issue to track the other comments - https://github.com/NuGet/Home/issues/3770

2016-10-25 21:39 UTC, joelverhagen approved these changes

2016-10-26 22:20 UTC, mishra14 commented
Merged: https://github.com/NuGet/NuGet.Client/commit/072270773bafb3e2ef22178b7b5fc791e23c5891

2016-10-26 22:20 UTC, closed without merging