Select a subset of TFMs when installing a single package to .NET Core
NuGet/NuGet.Client pull request #976
Opened 2016-10-27 22:39 UTC by joelverhagen

Fixes https://github.com/NuGet/Home/issues/3721.
Supersedes https://github.com/NuGet/NuGet.Client/pull/962.

The initial preview restore is executed. If the following conditions are all true about the result, the package is installed to the subset of the project's target frameworks that are compatible:

1. Only a single package is being installed.
1. There are one or more compatible frameworks.
1. There are one or more incompatible frameworks.
1. The preview restore failed.
1. The package is not already installed (it's not an upgrade).

This uses the new `IConditionalPackageReferencesService` API from CPS.

/cc @alpaix @drewgil @emgarten @natidea

2016-10-27 22:48 UTC, joelverhagen commented on src/NuGet.Clients/PackageManagement.VisualStudio/ProjectSystems/CpsPackageReferenceProject.cs
> +            return Task.FromResult(Path.Combine(
This was a bug. `OutputPath` is the directory but this method is supposed to return the full path. Compare to the other build integrated flavors.

2016-10-28 00:08 UTC, emgarten requested changes

2016-10-28 00:08 UTC, emgarten commented on src/NuGet.Clients/PackageManagement.VisualStudio/ProjectSystems/CpsPackageReferenceProject.cs
> +                    return true;
This install is just silently skipped without this service?

2016-10-28 00:08 UTC, emgarten commented on src/NuGet.Core/NuGet.ProjectManagement/Projects/BuildIntegratedNuGetProject.cs
> +            PackageIdentity packageIdentity,
This should really take an id and VersionRange from the start, the UI may not support it yet, but limiting this to a single version and disallowing stars will only make this harder to fix in the UI later.

2016-10-28 00:08 UTC, emgarten commented on src/NuGet.Clients/PackageManagement.VisualStudio/ProjectSystems/CpsPackageReferenceProject.cs
> +                        framework.GetShortFolderName());
Is something in CPS modifying this to match the actual framework string? 

Example: `netstandard1.6` is not the same as `netstandard16` in msbuild conditions

2016-10-28 00:08 UTC, emgarten commented on src/NuGet.Core/NuGet.PackageManagement/NuGetPackageManager.cs
> +                .ToList();
Consider RID restores where a TFM will exist for multiple graphs.

This needs a .Distinct() at minimum

For the scenario where a package is compatible in the RID-less graph but incompatible with the RID graph do we want to install anyways? The result there depends on more than just the TFM, it's not clear that the TFM should be skipped.

2016-10-28 00:08 UTC, emgarten commented on src/NuGet.Core/NuGet.PackageManagement/NuGetPackageManager.cs
> +                !PackageSpecOperations.HasPackage(originalPackageSpec, firstAction.PackageIdentity.Id))
nit: Add a comment that upgrades are not allowed here

2016-10-28 00:08 UTC, emgarten commented on src/NuGet.Core/NuGet.ProjectManagement/Projects/BuildIntegratedNuGetProject.cs
> +            IEnumerable<NuGetFramework> unsucessfulFrameworks,
Should there be another overload that doesn't take frameworks and applies it for all?

2016-10-28 00:11 UTC, joelverhagen commented on src/NuGet.Clients/PackageManagement.VisualStudio/ProjectSystems/CpsPackageReferenceProject.cs
> +                        framework.GetShortFolderName());
Ah, good point. I'm not sure how to get the original string from CPS yet. I'll look into it.

2016-10-28 00:13 UTC, joelverhagen commented on src/NuGet.Clients/PackageManagement.VisualStudio/ProjectSystems/CpsPackageReferenceProject.cs
> +                    return true;
I see a similar behavior in the unconditional case when `configuredProject` is null or if the `result` is null (both exceptional cases AFAIK). I had assumed this was by design. Alternatives include logging or throwing. Preference?

2016-10-28 00:14 UTC, joelverhagen commented on src/NuGet.Core/NuGet.ProjectManagement/Projects/BuildIntegratedNuGetProject.cs
> +            PackageIdentity packageIdentity,
Sounds good.

2016-10-28 00:16 UTC, joelverhagen commented on src/NuGet.Core/NuGet.ProjectManagement/Projects/BuildIntegratedNuGetProject.cs
> +            IEnumerable<NuGetFramework> unsucessfulFrameworks,
`NuGetPackageManager` will always have something from the project action to pass in here. An alternative would be to not have this overload on Legacy and P.J. (only on P.R.). I'll try that.

2016-10-28 00:17 UTC, joelverhagen commented on src/NuGet.Core/NuGet.PackageManagement/NuGetPackageManager.cs
> +                .ToList();
Yes, a `Distinct()` is correct. If the RID graph is incompatible, the whole TFM should be excluded.

2016-10-28 00:26 UTC, joelverhagen commented on src/NuGet.Core/NuGet.ProjectManagement/Projects/BuildIntegratedNuGetProject.cs
> +            IEnumerable<NuGetFramework> unsucessfulFrameworks,
Yikes, that would take as-casting during the execute step. Sure, I'll add the overload.

2016-10-28 00:32 UTC, joelverhagen commented on src/NuGet.Core/NuGet.ProjectManagement/Projects/BuildIntegratedNuGetProject.cs
> +            IEnumerable<NuGetFramework> unsucessfulFrameworks,
Actually, I thought about this some more and I don't think this overload would add any value. Current P.J. and legacy implementations ignore these parameters. I think this is actually preferable than forking the code to call the two different overloads.

2016-10-28 00:53 UTC, emgarten commented on src/NuGet.Clients/PackageManagement.VisualStudio/ProjectSystems/CpsPackageReferenceProject.cs
> +                        framework.GetShortFolderName());
It should be under RestoreMetadata.OriginalTargetFrameworks

2016-10-28 01:04 UTC, emgarten commented on src/NuGet.Clients/PackageManagement.VisualStudio/ProjectSystems/CpsPackageReferenceProject.cs
> +                    return true;
throwing seems better than quietly finishing the install without adding the package

if there's a scenario where this is expected and not a blocker I'm fine with ignoring

2016-10-28 02:51 UTC, joelverhagen commented on src/NuGet.Clients/PackageManagement.VisualStudio/ProjectSystems/CpsPackageReferenceProject.cs
> +                    return true;
Fixed.

2016-10-28 03:14 UTC, joelverhagen commented on src/NuGet.Core/NuGet.PackageManagement/NuGetPackageManager.cs
> +                !PackageSpecOperations.HasPackage(originalPackageSpec, firstAction.PackageIdentity.Id))
Fixed.

2016-10-28 03:14 UTC, joelverhagen commented on src/NuGet.Core/NuGet.PackageManagement/NuGetPackageManager.cs
> +                .ToList();
Fixed.

2016-10-28 03:15 UTC, joelverhagen commented on src/NuGet.Core/NuGet.ProjectManagement/Projects/BuildIntegratedNuGetProject.cs
> +            PackageIdentity packageIdentity,
Fixed.

2016-10-28 03:15 UTC, joelverhagen commented on src/NuGet.Clients/PackageManagement.VisualStudio/ProjectSystems/CpsPackageReferenceProject.cs
> +                        framework.GetShortFolderName());
Fixed, but waiting on https://github.com/NuGet/Home/issues/3739

2016-10-28 03:23 UTC, emgarten approved these changes
Good refactoring 👏

2016-10-28 03:23 UTC, emgarten commented on src/NuGet.Clients/PackageManagement.VisualStudio/ProjectSystems/CpsPackageReferenceProject.cs
> +                        Strings.UnableToGetCPSPackageInstallationService,
👍

2016-10-28 03:23 UTC, emgarten commented on src/NuGet.Clients/PackageManagement.VisualStudio/ProjectSystems/LegacyCSProjPackageReferenceProject.cs
> +            BuildIntegratedInstallationContext installationContext,
👍

2016-10-28 05:40 UTC, merged