[WIP] Adding CPS project locking around restore commits
NuGet/NuGet.Client pull request #984
Opened 2016-10-30 08:16 UTC by emgarten

Adding CPS project locking around restore commits

//cc @drewgil @rrelyea

2016-10-30 18:55 UTC, alpaix requested changes

2016-10-30 18:55 UTC, alpaix commented on src/NuGet.Clients/PackageManagement.VisualStudio/ProjectSystems/CpsPackageReferenceProject.cs
> +                return Task.FromResult<INuGetLock>(projectLock);
simply 
```c#
 return projectLock;
```

2016-10-30 18:55 UTC, alpaix commented on src/NuGet.Clients/VisualStudio.Facade/ProjectSystem/CPSProjectLock.cs
> +using System.Threading;
sort

2016-10-30 18:55 UTC, alpaix commented on src/NuGet.Clients/VisualStudio.Facade/ProjectSystem/CPSProjectLock.cs
> +    internal class CPSProjectLock : INuGetLock
is it actually `LegacyCPSProjectLock`?

2016-10-30 18:55 UTC, alpaix commented on src/NuGet.Clients/VisualStudio.Facade/NuGet.VisualStudio.Facade.csproj
> +    <Compile Include="ProjectSystem\CPSProjectLock.cs" />
Why can't it be conditionally included in `PackageManagement.VisualStudio`?

2016-10-30 18:55 UTC, alpaix commented on src/NuGet.Clients/VisualStudio.Facade/ProjectSystem/CPSProjectLock.cs
> +                // Since all calls happen on the UI thread no additional locking is needed
Can you add a short doc comment on top of the class saying it's thread-safe by design?

2016-10-30 18:55 UTC, alpaix commented on src/NuGet.Clients/VisualStudio.Facade/ProjectSystem/CPSProjectLock.cs
> +        public CPSProjectLock(Project project, IVsHierarchy hierarchy, string projectPath)
null check for all 3 arguments

2016-10-30 18:55 UTC, alpaix commented on src/NuGet.Clients/VisualStudio.Facade/ProjectSystem/CPSProjectLock.cs
> +                    UnconfiguredProject unconfiguredProject = ProjectHelper.GetUnconfiguredProject(vsProject);
use `var`

2016-10-30 18:55 UTC, alpaix commented on src/NuGet.Clients/VisualStudio.Facade/ProjectSystem/CPSProjectLock.cs
> +                    if (unconfiguredProject != null)
I'd suggest throwing `InvalidOperationException` here

2016-10-30 18:55 UTC, alpaix commented on src/NuGet.Clients/VisualStudio.Facade/ProjectSystem/CPSProjectLock.cs
> +    internal class CPSProjectLock : INuGetLock
To clarify the purpose of it `LegacyCPSProjectWriteLock`

2016-10-30 18:55 UTC, alpaix commented on src/NuGet.Core/NuGet.Commands/RestoreCommand/RestoreRunner.cs
> +        public static Task<IReadOnlyList<RestoreSummary>> Run(RestoreArgs restoreContext)
`RunAsync`?

2016-10-30 18:55 UTC, alpaix commented on src/NuGet.Core/NuGet.Commands/RestoreCommand/RestoreRunner.cs
> +        public static async Task<IReadOnlyList<RestoreSummary>> Run(
`RunAsync`

2016-10-30 18:55 UTC, alpaix commented on src/NuGet.Core/NuGet.Commands/RestoreCommand/RestoreRunner.cs
> +        private static async Task<RestoreSummary> ExecuteAndCommit(
`ExecuteAndCommitAsync`

2016-10-30 18:55 UTC, alpaix commented on src/NuGet.Core/NuGet.Commands/RestoreCommand/RestoreRunner.cs
> +        public static async Task<RestoreSummary> CommitInLock(RestoreResultPair result, IEnumerable<INuGetLock> locks)
`CommitInLockAsync`

2016-10-30 18:55 UTC, alpaix commented on src/NuGet.Core/NuGet.Commands/RestoreCommand/RestoreRunner.cs
> +                foreach (var current in locks)
I'd suggest adding and using `CompositeLock` class to wrap it

2016-10-30 18:55 UTC, alpaix commented on src/NuGet.Core/NuGet.Common/INuGetLock.cs
> +    public interface INuGetLock : IDisposable
1. `IDisposable` is implementation specific and shouldn't be part of the interface declaration.
2. I can't find it's actually used anywhere.

2016-10-30 18:55 UTC, alpaix commented on src/NuGet.Core/NuGet.PackageManagement/BuildIntegration/DependencyGraphRestoreUtility.cs
> +        private static async Task<List<INuGetLock>> GetLocksFromSolution(ISolutionManager solutionManager)
I'd suggest moving this method to `ISolutionManager`

2016-10-30 18:55 UTC, alpaix commented on src/NuGet.Core/NuGet.PackageManagement/NuGetPackageManager.cs
> +
Missing `AcquireAsync`?

2016-10-30 18:55 UTC, alpaix commented on src/NuGet.Core/NuGet.Commands/RestoreCommand/RestoreRunner.cs
> +        private static Dictionary<string, List<INuGetLock>> GetIdToLocks(IEnumerable<INuGetLock> locks)
Multiple locks per project?

2016-10-30 19:03 UTC, alpaix commented
I'd suggest improving the design by having a class like this
```c#
public class ProjectSystemCompositeLock
{
    private readonly Dictionary<string, INuGetLock> locks;
    
    public INuGetLock GetProjectLock(string projectPath);
}
```

And also a method `ISolutionManager.GetProjectSystemLock` returning an instance.

Thoughts?

2016-10-31 03:39 UTC, emgarten commented
``ProjectSystemCompositeLock`` could be nice, it would make it more obvious how to find the lock for a specific project. Also, yes I think allowing multiple per project makes sense since here the lock is for CPS, not for NuGet. If nuget wanted to add it's own machine wide lock for each project to keep VS and nuget.exe from conflicting it could then be done by just adding another lock here.

I'd like to see the CPS lock actually solve the restore problem before doing any refactoring on this, this was just to make it possible.

2016-11-04 03:31 UTC, joelverhagen commented on src/NuGet.Clients/VisualStudio.Facade/ProjectSystem/CPSProjectLock.cs
> +                return await asyncAction();
When could we not get the lock? This seems kind of risky to not understand.

2016-11-04 03:41 UTC, emgarten commented on src/NuGet.Clients/VisualStudio.Facade/ProjectSystem/CPSProjectLock.cs
> +                return await asyncAction();
There may be scenarios where the project isn't loaded, in those cases the lock isn't needed.

2016-11-04 16:35 UTC, closed without merging