Block Solution Restore while auto restore is running
NuGet/NuGet.Client pull request #985
Opened 2016-10-30 20:47 UTC by alpaix

Resolves NuGet/Home#3797.

Added `IsBusy` attribute to evaluate active restore operation is
in-progress.

Refactored restore operation implementation to use `JoinableTask` when
chaining subsequent operations. This technique is supposed to prevent
deadlocks we were seeing lately.

//cc @rrelyea @emgarten @joelverhagen @jainaashish

2016-10-30 23:42 UTC, alpaix commented
This change solves the deadlock issue when Solution Restore is invoked while background auto-restore is running. Although it makes VS UI freeze for a few seconds. Additional improvements needed for better UX is to bring progress dialog earlier (when detecting auto-restore is running). Also we should consider printing Solution Restore output to the Package Manager output window pane.

2016-10-31 03:31 UTC, emgarten commented on src/NuGet.Clients/PackageManagement.VisualStudio/SolutionRestore/SolutionRestoreWorker.cs
> +            DrainPendingRequestQueue(token);
This seems reasonable if all restores are solution wide, but does this also need to combine the settings on each request? For example if one request has force=true in the queue shouldn't the next restore force?

2016-10-31 17:14 UTC, emgarten requested changes
waiting on answer to the pruning vs merging

2016-10-31 17:16 UTC, alpaix commented on src/NuGet.Clients/PackageManagement.VisualStudio/SolutionRestore/SolutionRestoreWorker.cs
> +            DrainPendingRequestQueue(token);
Good point. But currently all auto restore requests in the queue are of the same origin (scheduled via nomination API).

2016-10-31 17:25 UTC, emgarten commented on src/NuGet.Clients/PackageManagement.VisualStudio/SolutionRestore/SolutionRestoreWorker.cs
> +            DrainPendingRequestQueue(token);
So those flags aren't used yet?

2016-10-31 17:52 UTC, alpaix commented on src/NuGet.Clients/PackageManagement.VisualStudio/SolutionRestore/SolutionRestoreWorker.cs
> +            DrainPendingRequestQueue(token);
Flags are used from:
- an auto-restore request fetched from the queue earlier (line 144), if the job was triggered by background queue listener;
- or from an on-build/explicit restore request that beats the auto-restore flags.

2016-10-31 18:33 UTC, emgarten approved these changes
If merging the restore flags in the queue isn't needed then this looks good.

2016-10-31 22:47 UTC, jainaashish approved these changes
Looks good

2016-10-31 22:56 UTC, alpaix commented
Abandoning this one in favor of simpler less risky solution #986

2016-10-31 22:56 UTC, closed without merging