Fix auto restore to wait until normal solution load is completed
NuGet/NuGet.Client pull request #990
Opened 2016-11-02 00:30 UTC by jainaashish

Since we call EnsureSolutionIsLoaded() api before restore to make sure all projects are loaded, regressed solution load time when solution was already being loaded in background. So this code change will make auto restore to wait until solution load is completed via OnAfterBackgroundSolutionLoadComplete event handler.

Fixes https://github.com/NuGet/Home/issues/3844 

@rrelyea @emgarten @alpaix @mishra14

2016-11-02 00:36 UTC, emgarten requested changes
Looks fine overall

2016-11-02 00:36 UTC, emgarten commented on src/NuGet.Clients/PackageManagement.VisualStudio/SolutionRestore/SolutionRestoreWorker.cs
> +            _solutionManager = _componentModel.GetService<IVsSolutionManager>();
Should this new code be conditional on the VS15 compiler flag? It looks like it won't be used for VS14. It would just help reduce noise there.

2016-11-02 00:43 UTC, jainaashish commented on src/NuGet.Clients/PackageManagement.VisualStudio/SolutionRestore/SolutionRestoreWorker.cs
> +            _solutionManager = _componentModel.GetService<IVsSolutionManager>();
Make sense, will update it.

2016-11-02 00:47 UTC, emgarten approved these changes

2016-11-02 04:03 UTC, alpaix commented on src/NuGet.Clients/PackageManagement.VisualStudio/SolutionRestore/SolutionRestoreWorker.cs
> +            _solutionManager = _componentModel.GetService<IVsSolutionManager>();
add a constructor parameter `solutionManager` to let the mef resolve it instead.

2016-11-02 04:04 UTC, alpaix commented on src/NuGet.Clients/PackageManagement.VisualStudio/SolutionRestore/SolutionRestoreWorker.cs
> +            IVsSolution vsSolution = serviceProvider.GetService(typeof(SVsSolution)) as IVsSolution;
`var`

2016-11-02 04:10 UTC, alpaix commented on src/NuGet.Clients/PackageManagement.VisualStudio/SolutionRestore/SolutionRestoreWorker.cs
> +            if (vsSolution != null)
Must throw here. The instance will be not functional without event subscription.

2016-11-02 04:14 UTC, alpaix commented on src/NuGet.Clients/PackageManagement.VisualStudio/SolutionRestore/SolutionRestoreWorker.cs
> +                Trace.TraceInformation($"Scheduling background solution restore. The background runner's status is '{runner.Status}'");
The trace message relates to a schedule operation. It's redundant here.

2016-11-02 04:19 UTC, alpaix commented on src/NuGet.Clients/PackageManagement.VisualStudio/SolutionRestore/SolutionRestoreWorker.cs
> +        public int OnAfterCloseSolution(object pUnkReserved)
Consider moving the implementation of `SolutionEvents_AfterClosing` to here. Single event subscription method will be easier to maintain.

2016-11-02 04:28 UTC, alpaix requested changes
Address the comments.

2016-11-02 04:29 UTC, alpaix commented
Have to handle ProjectAdded as well for cases when new CPS project being added to an existing solution.

2016-11-02 04:36 UTC, jainaashish commented on src/NuGet.Clients/PackageManagement.VisualStudio/SolutionRestore/SolutionRestoreWorker.cs
> +            _solutionManager = _componentModel.GetService<IVsSolutionManager>();
why we need that? when service provider is already passed in then why cant we resolve inside?

2016-11-02 04:36 UTC, jainaashish commented on src/NuGet.Clients/PackageManagement.VisualStudio/SolutionRestore/SolutionRestoreWorker.cs
> +            IVsSolution vsSolution = serviceProvider.GetService(typeof(SVsSolution)) as IVsSolution;
Fixed

2016-11-02 04:38 UTC, jainaashish commented on src/NuGet.Clients/PackageManagement.VisualStudio/SolutionRestore/SolutionRestoreWorker.cs
> +            if (vsSolution != null)
there won't be a case where it will be null except for tests which is why i kept it as null check. But i'm open to throw as well.

2016-11-02 04:40 UTC, alpaix commented on src/NuGet.Clients/PackageManagement.VisualStudio/SolutionRestore/SolutionRestoreWorker.cs
> +            _solutionManager = _componentModel.GetService<IVsSolutionManager>();
all mef imports/dependencies should be declared in one place as constructor parameters: for consistency, maintenance and testing.

2016-11-02 04:42 UTC, jainaashish commented on src/NuGet.Clients/PackageManagement.VisualStudio/SolutionRestore/SolutionRestoreWorker.cs
> +        public int OnAfterCloseSolution(object pUnkReserved)
I'm not sure if both are exactly the same thing besides i want the minimum code change. So would like to keep it that way for now?

2016-11-02 04:43 UTC, jainaashish commented on src/NuGet.Clients/PackageManagement.VisualStudio/SolutionRestore/SolutionRestoreWorker.cs
> +                Trace.TraceInformation($"Scheduling background solution restore. The background runner's status is '{runner.Status}'");
It's only printed once here when we actually start runner. Would you like to remove this trace message altogether?

2016-11-02 04:48 UTC, alpaix commented on src/NuGet.Clients/PackageManagement.VisualStudio/SolutionRestore/SolutionRestoreWorker.cs
> +            if (vsSolution != null)
Exactly. The product code ought to be clean of test related assumptions. In this particular case no test exists that demands this condition.

2016-11-02 04:49 UTC, alpaix commented on src/NuGet.Clients/PackageManagement.VisualStudio/SolutionRestore/SolutionRestoreWorker.cs
> +        public int OnAfterCloseSolution(object pUnkReserved)
Agree. Can wait for post-RC.

2016-11-02 04:51 UTC, jainaashish commented on src/NuGet.Clients/PackageManagement.VisualStudio/SolutionRestore/SolutionRestoreWorker.cs
> +            _solutionManager = _componentModel.GetService<IVsSolutionManager>();
But this is not an mef import or dependency... SolutionManager is NuGet internal interface and its implementation. I still don't understand why its required...

2016-11-02 04:52 UTC, alpaix commented on src/NuGet.Clients/PackageManagement.VisualStudio/SolutionRestore/SolutionRestoreWorker.cs
> +                Trace.TraceInformation($"Scheduling background solution restore. The background runner's status is '{runner.Status}'");
I added this to track scheduled restores. It is useless here.

2016-11-02 05:00 UTC, alpaix commented on src/NuGet.Clients/PackageManagement.VisualStudio/SolutionRestore/SolutionRestoreWorker.cs
> +            _solutionManager = _componentModel.GetService<IVsSolutionManager>();
First, it is. `VsSolutionManager` class declares MEF export attribute `[Export(typeof(IVsSolutionManager))]`. In your change the instance is resolved explicitly via MEF composition container interface `IComponentModel`.

Then, everywhere else across the NuGet code base the convention was to put all MEF imports in a constructor parameters. See for ex., `VsPackageInstaller`, `VsPackageInstallerServices`, `VsTemplateWizard`, and few more.

2016-11-02 05:37 UTC, jainaashish commented on src/NuGet.Clients/PackageManagement.VisualStudio/SolutionRestore/SolutionRestoreWorker.cs
> +            _solutionManager = _componentModel.GetService<IVsSolutionManager>();
I didn't notice that `[Export(typeof(IVsSolutionManager))]` Will add it as constructor param.

2016-11-02 16:43 UTC, jainaashish commented
`Have to handle ProjectAdded as well for cases when new CPS project being added to an existing solution.`

Wouldn't that be already loaded project in that solution? why do we need to handle it separately?

2016-11-02 17:42 UTC, jainaashish commented
Discussed offline with @alpaix for ProjectAdded case and will handle that as well.

2016-11-02 17:57 UTC, alpaix approved these changes
:clap:

2016-11-04 19:23 UTC, emgarten approved these changes

2016-11-07 19:29 UTC, merged