Add RestoreLegacyPackagesDirectory MSBuild property to restore original case packages
NuGet/NuGet.Client pull request #994
Opened 2016-11-03 18:50 UTC by joelverhagen

Fixes https://github.com/NuGet/Home/issues/3618.

/cc @emgarten

A follow-up step would be updating the version in dotnet/sdk and dotnet/cli repos, right?

2016-11-03 19:09 UTC, emgarten commented
Should this be a switch or a project property? What happens if a solution has a mix of 1.0 and 1.1?

2016-11-03 22:15 UTC, joelverhagen commented
@emgarten, thanks for the great feedback. 

We spoke offline and decided that each project should be allowed to set its own `RestoreLegacyPackagesDirectory` property. To do this, I added the property to the `PackageSpec.RestoreMetadata`.

2016-11-03 22:42 UTC, jainaashish commented on src/NuGet.Core/NuGet.Commands/RestoreCommand/RequestFactory/DependencyGraphSpecRequestProvider.cs
> +            request.IsLowercasePackagesDirectory = !(project.PackageSpec?.RestoreMetadata?.RestoreLegacyPackagesDirectory ?? false);
how about having a constant for default value?

2016-11-03 22:44 UTC, jainaashish approved these changes

2016-11-03 22:53 UTC, joelverhagen commented on src/NuGet.Core/NuGet.Commands/RestoreCommand/RequestFactory/DependencyGraphSpecRequestProvider.cs
> +            request.IsLowercasePackagesDirectory = !(project.PackageSpec?.RestoreMetadata?.RestoreLegacyPackagesDirectory ?? false);
sure

2016-11-03 23:06 UTC, joelverhagen commented on src/NuGet.Core/NuGet.Commands/RestoreCommand/RequestFactory/DependencyGraphSpecRequestProvider.cs
> +            request.IsLowercasePackagesDirectory = !(project.PackageSpec?.RestoreMetadata?.RestoreLegacyPackagesDirectory ?? false);
Fixed.

2016-11-03 23:47 UTC, emgarten requested changes

2016-11-03 23:47 UTC, emgarten commented on src/NuGet.Core/NuGet.Commands/RestoreCommand/RequestFactory/RestoreArgs.cs
> +            if (IsLowercaseGlobalPackagesFolder.HasValue)
👍

2016-11-03 23:47 UTC, emgarten commented on src/NuGet.Core/NuGet.ProjectModel/ProjectRestoreMetadata.cs
> +        public bool RestoreLegacyPackagesDirectory { get; set; }
Add support to the PackageSpec reader/writer also, otherwise it is really easy to drop the value

2016-11-04 00:32 UTC, joelverhagen commented on src/NuGet.Core/NuGet.ProjectModel/ProjectRestoreMetadata.cs
> +        public bool RestoreLegacyPackagesDirectory { get; set; }
Done. Tests too.

2016-11-04 01:26 UTC, emgarten approved these changes

2016-11-04 01:28 UTC, merged